### ISSUE TITLE
responses package里fmt的使用会导致调用过程中出现一些非预期的中间结果

### ISSUE THREAD

**Issue by liulizhi** [aliyun/alibaba-cloud-sdk-go#1]
package responses

import (
    "bytes"
    "encoding/json"
    "encoding/xml"
    _`"fmt"`_
    "io/ioutil"
    "net/http"
    "strconv"
    "strings"
)

func Unmarshal(response AcsResponse, httpResponse *http.Response, format string) (err error) {
    err = response.parseFromHttpResponse(httpResponse)
    _`fmt.Println(response.GetHttpContentString())`_
    if err != nil {
        return
    }
    if strings.ToUpper(format) == "JSON" {
        err = json.Unmarshal(response.GetHttpContentBytes(), response)
    } else if strings.ToUpper(format) == "XML" {
        err = xml.Unmarshal(response.GetHttpContentBytes(), response)
    }
    return
}

斜体标注处，会在调用方法时产生非预期的中间结果输出，请帮忙确认下是否合理，谢谢！

**Comment by gaort** [comment]
@liulizhi 
十分感谢您的反馈！
的确这块是我们的疏忽，我们会尽快将类似代码清理掉
再次感谢您的反馈，您的支持是我们最大的动力！

**Comment by gaort** [comment]
@liulizhi 您好，您提到的问题已经解决了：D
