### ISSUE TITLE
Error on DescribeUserDomains: failed to unmarshal DescribeUserDomainsResponse.Domains

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#10]
When calling cdn.Client.DescribeUserDomains, it got the following error:
> json: cannot unmarshal object into Go struct field DescribeUserDomainsResponse.Domains of type []struct { DomainName string "json:\"DomainName\""; Cname string "json:\"Cname\""; CdnType string "json:\"CdnType\""; DomainStatus string "json:\"DomainStatus\""; GmtCreated string "json:\"GmtCreated\""; GmtModified string "json:\"GmtModified\""; Description string "json:\"Description\""; SourceType string "json:\"SourceType\""; SslProtocol string "json:\"SslProtocol\""; ResourceGroupId string "json:\"ResourceGroupId\""; Sandbox string "json:\"Sandbox\""; Sources []string "json:\"Sources\"" }

And calling codes are as following:
> 		gInput := cdn.CreateDescribeUserDomainsRequest()
>		// TODO: Workaround
>		gInput.Domain = "cdn.aliyuncs.com"
>		gInput.RegionId = iaasRegion
>		gInput.PageSize = utils.FormatInt64(PageSize)
>		gInput.PageNumber = utils.FormatInt64(pageNumber)
>		gOutput, err := factory.GetCdnClient().DescribeUserDomains(gInput)

Maybe it's owing to definition inconsistency between Go struct and REST API.

**Supplementary Info[2017/12/28]:**
content of gOutput.GetHttpContentBytes() is:
>{
  "RequestId": "41BEE10D-8C81-4F0B-9076-061B1CABA231",
  "PageNumber": 1,
  "PageSize": 50,
  "TotalCount": 0,
  "Domains": {
    **"PageData"**: [      
    ]
  }
}

It can be found that an extra filed "PageData" shoud be nested in "Domains" field.

**Comment by gaort** [comment]
@jancco2012 thanks for the feedback

you can ignore the error, and take the original response by invoke
`gOutput.GetHttpContentString()` `gOutput.GetHttpContentBytes()` or `gOutput.GetOriginHttpResponse`

If you find it convenient, can you tell us about the response you got through this method so that we can debug this problem, thank you very much

**Comment by jancco2012** [comment]
@gaort I've added some supplementary info in the root thread, it may be helpful for you to fix this issue.

**Comment by conan425** [comment]
fixed
