### ISSUE TITLE
Error on DescribeSnapshots: failed to unmarshal .SourceDiskSize of type string

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#11]
When calling cdn.Client.DescribeUserDomains, it got the following error:
> json: cannot unmarshal number into Go struct field .SourceDiskSize of type string

And calling codes are as following:
> 		gInput := ecs.CreateDescribeSnapshotsRequest()
>		// TODO: Workaround
>		gInput.Domain = "ecs.aliyuncs.com"
>		gInput.RegionId = iaasRegion
>		gInput.PageSize = utils.FormatInt64(PageSize)
>		gInput.PageNumber = utils.FormatInt64(pageNumber)
>		gOutput, err := factory.GetEcsClient().DescribeSnapshots(gInput)

Maybe it's owing to definition inconsistency between Go struct and REST API.

**Supplementary Info[2017/12/28]:**
content of gOutput.GetHttpContentBytes() is:
>{
  "PageNumber": 1,
  "PageSize": 50,
  "TotalCount": 1,
  "RequestId": "F94FC9F9-B46D-4804-B986-093FB8D36926",
  "Snapshots": {
    "Snapshot": [
      {
        "CreationTime": "2017-11-08T03:58:14Z",
        "Description": "",
        "Encrypted": false,
        "ProductCode": "",
        "Progress": "100%",
        "SnapshotId": "s-m5eacq02ar6zb64oic40",
        "SnapshotName": "snp-test-20171108",
        "SourceDiskId": "d-m5efbha9mr8doraejejb",
        "SourceDiskSize": 40,
        "SourceDiskType": "system",
        "SourceStorageType": "disk",
        "Status": "accomplished",
        "Tags": {
          "Tag": [
          ]
        },
        "Usage": "none"
      }
    ]
  }
}

And it can be found that this issue is caused by wrong data type of "SourceDiskSize". And to change its data type as int (not int64), this issue will be fixed.

**Comment by gaort** [comment]
@jancco2012 
I think it's same as #10 
If you agree, shall we talk over there?

**Comment by jancco2012** [comment]
@gaort I supplemented some info in the source post. And for this issue has to be fixed in the different codes than #10, so it may be better to keep it open.

**Comment by conan425** [comment]
fixed
