### ISSUE TITLE
CreateCreateDBInstanceRequest增加autoRenew参数

### ISSUE THREAD

**Issue by bringyou** [aliyun/alibaba-cloud-sdk-go#118]
创建rds的gui上有个“自动续费”的选项，看请求应该是autoRenew变量。目前的sdk（rds.CreateDBInstanceRequest这个结构体）并没有这个。
请问有支持的计划吗

**Comment by JacksonTian** [comment]
因为这个涉及到 OpenAPI 的设计，所以在 SDK 层面我暂时先关闭掉了。问题我会转给 RDS 团队。

**Comment by miaoben** [comment]
> 创建rds的gui上有个“自动续费”的选项，看请求应该是autoRenew变量。目前的sdk（rds.CreateDBInstanceRequest这个结构体）并没有这个。
> 请问有支持的计划吗

您创建的是包年包月实例吗。

**Comment by bringyou** [comment]
@miaoben 先说声不好意思，这个close以后就没有怎么关注了，回复晚了。

> 您创建的是包年包月实例吗。

是的，是包年包月的实例。但有时候会创建一些按量付费的实例进行测试。
