### ISSUE TITLE
计费相关的SDK

### ISSUE THREAD

**Issue by hantmac** [aliyun/alibaba-cloud-sdk-go#120]
Hi, 
计费相关的sdk阿里云有提供吗？

**Comment by hantmac** [comment]
在sdk/endpoints/endpoint_config.go里面添加一个obs的服务：
 "  {" +
485     "    \"code\": \"obs\"," +
486     "    \"document_id\": \"34962\"," +
487     "    \"location_service_code\": \"obs\"," +
488     "    \"regional_endpoints\": []," +
489     "    \"global_endpoint\": \"billing.aliyuncs.com\"," +
490     "    \"regional_endpoint_pattern\": \"\"" +
491     "  }," +


这code,document_id, location_service_code, regional_endpoints, global_endpoint, regional_endpoint_pattern几个字段该填什么？
谢谢！
ps:由于工作需要， AliYun OBS的SDK我自己实现了一下，里面有些不清楚的问题，已经在issue里说明，若有需要，我可以fork一个分支，将该OBS部分代码让大家review一下

**Comment by JacksonTian** [comment]
see #121
