### ISSUE TITLE
BSS费用中心SDK, 没有默认endpoint

### ISSUE THREAD

**Issue by jokimina** [aliyun/alibaba-cloud-sdk-go#123]
panic: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"BssOpenApi","RegionId":"cn-beijing","LocationProduct":"","LocationEndpointType":""}), please check your accessKey with secret, and read the user guid

**Comment by hantmac** [comment]
这个问题我也遇到了，我在../sdk/endpoints/endpoint_config.go里面添加上就可以了
昨天提了issue和P&R，阿里云的开发人员回复我说这类产品可以自动生成，但是不知道他们为什么没有在OBS 和BSS里面加上这类endpoints config.

**Comment by jokimina** [comment]
> 这个问题我也遇到了，我在../sdk/endpoints/endpoint_config.go里面添加上就可以了
> 昨天提了issue和P&R，阿里云的开发人员回复我说这类产品可以自动生成，但是不知道他们为什么没有在OBS 和BSS里面加上这类endpoints config.

```
		resolvers = []Resolver{
			&SimpleHostResolver{},
			&MappingResolver{},
			&LocationResolver{},
			&LocalRegionalResolver{},
			&LocalGlobalResolver{},
		}
```
有几个resolver解析出endpoint的 , 自动生成的应该是指LocationResolver会根据ServiceCode和LocationEndpointType从location-readonly.aliyuncs.com解析出对应的endpoint的, 然而后面的sdk 比如我用的ram, bssopenapi在Create Request的时候ServiceCode和LocationEndpointType都是空的...就读本地的endpoint_config了, 然而又有缺失....... test case不知道咋跑过的 (⊙﹏⊙)b

**Comment by hantmac** [comment]
> > 这个问题我也遇到了，我在../sdk/endpoints/endpoint_config.go里面添加上就可以了
> > 昨天提了issue和P&R，阿里云的开发人员回复我说这类产品可以自动生成，但是不知道他们为什么没有在OBS 和BSS里面加上这类endpoints config.
> 
> ```
> 		resolvers = []Resolver{
> 			&SimpleHostResolver{},
> 			&MappingResolver{},
> 			&LocationResolver{},
> 			&LocalRegionalResolver{},
> 			&LocalGlobalResolver{},
> 		}
> ```
> 有几个resolver解析出endpoint的 , 自动生成的应该是指LocationResolver会根据ServiceCode和LocationEndpointType从location-readonly.aliyuncs.com解析出对应的endpoint的, 然而后面的sdk 比如我用的ram, bssopenapi在Create Request的时候ServiceCode和LocationEndpointType都是空的...就读本地的endpoint_config了, 然而又有缺失....... test case不知道咋跑过的 (⊙﹏⊙)b

是的，并没有自动生成，提了相关issue后他们也没有去修正，还是告诉我可以自动生成。

**Comment by JacksonTian** [comment]
如果需要默认的 endpoint，需要 location 里面有相关的数据。

可以先用 func AddEndpointMapping(regionId, productId, endpoint string) 方法来添加本地的映射关系。

**Comment by hantmac** [comment]
我手动在alibaba-cloud-sdk-go/sdk/endpoints/endpoints_config.go里面添加上：
```
 "  {" +
        "    \"code\": \"bssopenapi\"," +
        "    \"document_id\": \"34962\"," +
        "    \"location_service_code\": \"bssopenapi\"," +
        "    \"regional_endpoints\": []," +
        "    \"global_endpoint\": \"business.aliyuncs.com\"," +
        "    \"regional_endpoint_pattern\": \"\"" +
        "  }," +

```

然后在query_monthly_bill这类文件中的CreateQueryMonthlyBillRequest函数中，添加
```
request.InitWithApiInfo("BssOpenApi", "2017-12-14", "QueryMonthlyBill", "bssopenapi", "openAPI")
```

就可以正常使用了

**Comment by JacksonTian** [comment]
@hantmac 请使用 request.Domain = "business.aliyuncs.com" 的形式，而不是改 vendor。
