### ISSUE TITLE
BssOpenApi report error when use request parameters

### ISSUE THREAD

**Issue by hantmac** [aliyun/alibaba-cloud-sdk-go#146]
Hi~
    I use a method of bssopenapi named  'QueryMonthlyInstanceConsumption'  as the description of [this website](https://help.aliyun.com/document_detail/87991.html?spm=a2c4g.11186623.2.11.39b13990kzevQF). 
The code as flows:

```
aliSecretId, aliSecretKey := config.ReadAliCredIni()
	bssClient, err := bssopenapi.NewClientWithAccessKey(
		"",
		aliSecretId,
		aliSecretKey)

	if err != nil {
		panic(err)
	}

	request := bssopenapi.CreateQueryMonthlyInstanceConsumptionRequest()
	request.BillingCycle = "2018-11"
	request.PageSize = requests.Integer(20)
	// request.PageNum = requests.Integer(2)

	response, err := bssClient.QueryMonthlyInstanceConsumption(request)


	if err != nil {
		panic(err)
	}
```

The problem is when I wanna to use request.PageSize and request.PageNum, I wil get an error like this:
```
 Message: Specified parameter PageSize is not valid.

or 

Message: Specified parameter PageNum is not valid.
```

And I have checked the final generated URL , it contains the parameter `PageNum` or  ` PageSize`.

Thank you!

**Comment by JacksonTian** [comment]
Could you submit an work order in alibaba cloud console.

**Comment by hantmac** [comment]
> Could you submit an work order in alibaba cloud console.

I have resolved this problem using the next code:
```
	request.QueryParams["PageSize"] = "100"
        request.QueryParams["PageNum"] = "2"
```


 So, I think you should modify your SDK document about bssopenapi,  because in your document the type of PageSize and PageNum is int, and the use of this parameter is  ```request.PageSize = 10``` which is wrong. 

 **I feel that it is necessary to be strict with programming.**
