### ISSUE TITLE
shall we upgrade uuid package from v1.1.x to v1.2.0

### ISSUE THREAD

**Issue by xiefulaithu** [aliyun/alibaba-cloud-sdk-go#147]
"github.com/satori/go.uuid“ 这个包在版本 V1.2.0中，uuid.NewV4()返回值为两个。

目前sdk-go中使用的老版本。

问题：

使用 go mod tidy 安装依赖，默认安装的是V1.2.0版本。go build 会报错。

用go mod edit -require github.com/satori/go.uuid@v1.0.0 能解决问题，希望升级uuid包到最新版本。

THX~

**Comment by JacksonTian** [comment]
我们的 go.uuid 是在 vendor 目录下的，会冲突吗？

**Comment by wenzuochao** [comment]
> "github.com/satori/go.uuid“ 这个包在版本 V1.2.0中，uuid.NewV4()返回值为两个。
> 
> 目前sdk-go中使用的老版本。
> 
> 问题：
> 
> 使用 go mod tidy 安装依赖，默认安装的是V1.2.0版本。go build 会报错。
> 
> 用go mod edit -require github.com/satori/go.uuid@v1.0.0 能解决问题，希望升级uuid包到最新版本。
> 
> THX~

你好， 1.2.0版本的newv4也只有一个返回值

**Comment by xiefulaithu** [comment]
1

经过确认，1.2.0版本的NewV4返回值为1个。master分支的NewV4返回值为2个。

close
