### ISSUE TITLE
STS not working.

### ISSUE THREAD

**Issue by wangxingge** [aliyun/alibaba-cloud-sdk-go#148]
stsReq := sts.CreateAssumeRoleRequest()
stsReq.RoleArn = "acs:ram::xxxxxxxxxxxxxxxxxxx:xxx/xxxxxxxxxx"
stsReq.DurationSeconds = requests.NewInteger(3600)
response, err := stsClient.AssumeRole(stsReq)

Response: Your request is denied as lack of ssl protect.

**Comment by JacksonTian** [comment]
能否提供稍微全一点的信息。

**Comment by wangxingge** [comment]
需要指定 https..  好像默认的是http不是 ssl的。

**Comment by JacksonTian** [comment]
Ok.

**Comment by dxcswl** [comment]
我想知道这个最后怎么解决了？

**Comment by wenzuochao** [comment]
> 我想知道这个最后怎么解决了？

request.SetScheme = "https" 就可以了
