### ISSUE TITLE
使用最新master，原来正常的出错

### ISSUE THREAD

**Issue by gogolxdong** [aliyun/alibaba-cloud-sdk-go#15]
Error json: cannot unmarshal number into Go struct field .CpuCoreCount of type requests.Integer
Error json: cannot unmarshal number into Go struct field .DiscountPrice of type requests.Float

**Comment by gaort** [comment]
@gogolxdong 感谢您的反馈
这可能是由于我们最近的一次更新带来的bug，我们会尽快确认并修复，谢谢您的反馈！

**Comment by yueyongyue** [comment]
希望尽快修复

**Comment by gaort** [comment]
@yueyongyue
十分抱歉给您带来的困扰，这的确是我们的bug，我们会尽快修复后重新发布
在这之前，您有两种方式可以绕过这个bug带来的使用问题
1. 您可以参考#10中，我的回复，忽略err，可以从response中提取未反序列化之前的json串以及httpresponse
2. 使用之前的版本
再次向您道歉，给您带来了不便，十分抱歉

**Comment by gaort** [comment]
@yueyongyue
您提交的问题已在0.7.1中修复:D
给您带来了不便，再次向您道歉
也再次感谢您的支持和反馈，谢谢！

**Comment by yueyongyue** [comment]
好了，多谢了
