### ISSUE TITLE
Update DM Service version and parameter to latest

### ISSUE THREAD

**Issue by lincanli** [aliyun/alibaba-cloud-sdk-go#152]
Update DM Service (SMS) version and parameter to latest
Specifically, current parameters sent by alibaba-cloud-sdk-go is invalid and result in following err:

```
ErrorCode: InvalidVersion
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidVersion&source=PopGw
RequestId: D8689137-831B-4B01-8410-647E03F8015A
Message: Specified parameter Version is not valid.
````

By simple change to following can fix this

![default](https://user-images.githubusercontent.com/4588539/50077686-0655b500-0220-11e9-8b36-4fa576625ba5.png)

**Comment by qjk1234** [comment]
hi，this SingleSendSms  is too old api.  This API  is not available at present.
please look this page  “https://api.aliyun.com/#product=Dysmsapi&api=SendSms&params={}&tab=DEMO&lang=GO“

SingleSendSms这个接口太老了，已经下线了，目前是不可用的。
使用新版接口SendSms，地址https://api.aliyun.com/#product=Dysmsapi&api=SendSms&params={}&tab=DEMO&lang=GO   参数说明可以查看https://help.aliyun.com/document_detail/55284.html

**Comment by JacksonTian** [comment]
@lincanli Please use the new product to send sms and use new SDK.

Now I close it. If any question, feel free to reopen this issue.

**Comment by lincanli** [comment]
好的，可以你们提供的是 ComenAPI 的发送方法，确实能用，但是不准备提供生产好的 struct 嘛？
