### ISSUE TITLE
sdk does not support windows os

### ISSUE THREAD

**Issue by liukeyou** [aliyun/alibaba-cloud-sdk-go#154]
panic: open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path
 specified.

goroutine 1 [running]:  xxxx/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils.GetTimeInFormatISO860
1(0x1a9dc60, 0xc04230b2c0)
-------------------------------------------------

if err != nil {
    loc = time.Local
}

**Comment by JacksonTian** [comment]
Could you please report more stack?

**Comment by xiaowenhuyuehu** [comment]
![image](https://user-images.githubusercontent.com/38806082/50768534-b8324f80-12bb-11e9-98b6-ef2db2d34481.png)

确实在win下面用不了，zoneinfo.zip的问题，怎么解决呢

**Comment by xiaowenhuyuehu** [comment]
已经解决，手动指定GOROOT，并将.zip拷贝到任意lib/time目录即可。

**Comment by JacksonTian** [comment]
所以这个问题是 windows 的环境下默认没有 zoneinfo.zip 导致的，对吧。

**Comment by xiaowenhuyuehu** [comment]
> 所以这个问题是 windows 的环境下默认没有 zoneinfo.zip 导致的，对吧。

是的。

**Comment by wenzuochao** [comment]
> ![image](https://user-images.githubusercontent.com/38806082/50768534-b8324f80-12bb-11e9-98b6-ef2db2d34481.png)
> 
> 确实在win下面用不了，zoneinfo.zip的问题，怎么解决呢

您好，我注意到您的goroot路径是 “/usr/local/go” 并且报错信息中出现 “/home” 路径，这在windows上是不可能出现的。又因为您的截图过于模糊，无法看清完整报错信息，所以我们暂时无法定位问题代码，希望您能提供清晰的报错信息和一些您认为可以帮助我们定位问题的其他信息。

**Comment by wenzuochao** [comment]
> panic: open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path
> specified.
> 
> ## goroutine 1 [running]: xxxx/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils.GetTimeInFormatISO860
> 1(0x1a9dc60, 0xc04230b2c0)
> if err != nil {
> loc = time.Local
> }

我们已经修改了相关代码，欢迎您下载最新的代码，相信您的问题已经得到了解决，感谢您的支持
