### ISSUE TITLE
SLB describe_load_balancer_attribute.go 中ListenerPortsAndProtocal 及ListenerPortsAndProtocol

### ISSUE THREAD

**Issue by yueyongyue** [aliyun/alibaba-cloud-sdk-go#16]
在SLB调用的过程中，使用DescribeLoadBalancerAttribute 方法发现 ListenerPortsAndProtocal 及ListenerPortsAndProtocol两个结构，里面的内容也是相同的，不知道是不是多写了，查看官方API说明https://help.aliyun.com/document_detail/27583.html 并没有ListenerPortsAndProtocal 的说明

**Comment by gaort** [comment]
@yueyongyue 
十分感谢您的反馈，我们会尽快与相关同事沟通确认此事
