### ISSUE TITLE
SLB 调用DescribeLoadBalancerAttribute 方法

### ISSUE THREAD

**Issue by yueyongyue** [aliyun/alibaba-cloud-sdk-go#17]
错误信息 json: cannot unmarshal number into Go struct field .ListenerPort of type string 
describe_load_balancer_attribute.go  文件

ListenerPorts      struct {
		ListenerPort []string `json:"ListenerPort" xml:"ListenerPort"`
} `json:"ListenerPorts" xml:"ListenerPorts"`

ListenerPort 类型应该是这个整形的数组吧

**Comment by gaort** [comment]
same as #16

**Comment by gaort** [comment]
fixed
