### ISSUE TITLE
[bug] QueryAvailableInstances

### ISSUE THREAD

**Issue by xiefulaithu** [aliyun/alibaba-cloud-sdk-go#187]
## 示例代码

```golang
	client, err := bssopenapi.NewClientWithAccessKey(
		"cn-beijing", ak, sk)
	if err != nil {
		return
	}
	request := bssopenapi.CreateQueryAvailableInstancesRequest()
	request.Domain = "business.aliyuncs.com"
	request.ProductCode = "ecs"

	response, err := client.QueryAvailableInstances(request)
```

## sdk 版本
github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190130090545-97fb8dcd4a63

## 报错信息
在上面这个版本中，QueryAvailableInstances 报错如下：
```bash
bssopenapi.QueryAvailableInstancesResponse.Data: bssopenapi.Data.InstanceList: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|nceList":[{"Status":|..., bigger context ...|unt":42,"PageSize":20,"PageNum":1,"InstanceList":[{"Status":"Normal","SubStatus":"Normal","Subscript|...
```

## 报错原因
response.body里的数据看起来比较老，最新的QueryAvailableInstancesResponse的json格式不一致

**Comment by wenzuochao** [comment]
> ## 示例代码
> ```go
> 	client, err := bssopenapi.NewClientWithAccessKey(
> 		"cn-beijing", ak, sk)
> 	if err != nil {
> 		return
> 	}
> 	request := bssopenapi.CreateQueryAvailableInstancesRequest()
> 	request.Domain = "business.aliyuncs.com"
> 	request.ProductCode = "ecs"
> 
> 	response, err := client.QueryAvailableInstances(request)
> ```
> 
> ## sdk 版本
> github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190130090545-97fb8dcd4a63
> 
> ## 报错信息
> 在上面这个版本中，QueryAvailableInstances 报错如下：
> 
> ```shell
> bssopenapi.QueryAvailableInstancesResponse.Data: bssopenapi.Data.InstanceList: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|nceList":[{"Status":|..., bigger context ...|unt":42,"PageSize":20,"PageNum":1,"InstanceList":[{"Status":"Normal","SubStatus":"Normal","Subscript|...
> ```
> 
> ## 报错原因
> response.body里的数据看起来比较老，最新的QueryAvailableInstancesResponse的json格式不一致

您好，非常感谢您的宝贵意见。这边想问一下您使用的最新的master分支的代码吗？

**Comment by xiefulaithu** [comment]
> > ## 示例代码
> > ```go
> > 	client, err := bssopenapi.NewClientWithAccessKey(
> > 		"cn-beijing", ak, sk)
> > 	if err != nil {
> > 		return
> > 	}
> > 	request := bssopenapi.CreateQueryAvailableInstancesRequest()
> > 	request.Domain = "business.aliyuncs.com"
> > 	request.ProductCode = "ecs"
> > 
> > 	response, err := client.QueryAvailableInstances(request)
> > ```
> > 
> > 
> > ## sdk 版本
> > github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190130090545-97fb8dcd4a63
> > ## 报错信息
> > 在上面这个版本中，QueryAvailableInstances 报错如下：
> > ```shell
> > bssopenapi.QueryAvailableInstancesResponse.Data: bssopenapi.Data.InstanceList: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|nceList":[{"Status":|..., bigger context ...|unt":42,"PageSize":20,"PageNum":1,"InstanceList":[{"Status":"Normal","SubStatus":"Normal","Subscript|...
> > ```
> > 
> > 
> > ## 报错原因
> > response.body里的数据看起来比较老，最新的QueryAvailableInstancesResponse的json格式不一致
> 
> 您好，非常感谢您的宝贵意见。这边想问一下您使用的最新的master分支的代码吗？

不是最新的master分支

刚才用 `github.com/aliyun/alibaba-cloud-sdk-go@v0.0.0-20190203032130-408505a5fba8` 重新测试了一下，仍旧出现上述问题。

**Comment by xiefulaithu** [comment]
补充一下：使用tag 1.51.22 报错，回退到 1.51.10 之后，business.aliyuncs.com 返回的 ecs describeInstances 结果能正常解析

**Comment by wenzuochao** [comment]
> 补充一下：使用tag 1.51.22 报错，回退到 1.51.10 之后，business.aliyuncs.com 返回的 ecs describeInstances 结果能正常解析

您去掉request的ProductCode试一下？business的ProductCode不是ecs

**Comment by xiefulaithu** [comment]
> > 补充一下：使用tag 1.51.22 报错，回退到 1.51.10 之后，business.aliyuncs.com 返回的 ecs describeInstances 结果能正常解析
> 
> 您去掉request的ProductCode试一下？business的ProductCode不是ecs

@wenzuochao  非常感谢回复。为了进一步清晰问题，我直接补充一下我的代码吧：

```golang
// 获取某个账号下所有的 ecs regions
func descEcsRegions(alias, ak, sk string) error {
	client, err := bssopenapi.NewClientWithAccessKey("cn-beijing", ak, sk)
	if err != nil {
		return fmt.Errorf("Aliyun access key id: %s/%s INVALID, Err: %v", alias, ak, err)
	}

	request := bssopenapi.CreateQueryAvailableInstancesRequest()
	request.Domain = "business.aliyuncs.com"
	//request.ProductCode = "ecs" // 注释 or 不注释 都会报错

	response, err := client.QueryAvailableInstances(request)
	if err != nil {
                // 报错位置 @wenzuochao 
		return fmt.Errorf("QueryAvailableInstances Err: %v, ak: %s/%s", err, alias, ak)
	}
	if !response.IsSuccess() {
		return fmt.Errorf("QueryAvailableInstances Fail: %v, Code: %v, ak: %s/%s", response.GetHttpContentString(), response.Code, alias, ak)
	}

	if response.Data.TotalCount > len(response.Data.InstanceList.Instance) {
		time.Sleep(1 * time.Second)
		// reset PageSize, and request again
		request.PageSize = requests.Integer(strconv.Itoa(response.Data.TotalCount))
		response, err = client.QueryAvailableInstances(request)
		if err != nil {
			return fmt.Errorf("QueryAvailableInstances Err: %v, ak: %s/%s", err, alias, ak)
		}
		if !response.IsSuccess() {
			return fmt.Errorf("QueryAvailableInstances Fail: %v, Code: %v, ak: %s/%s", response.GetHttpContentString(), response.Code, alias, ak)
		}
	}
	regions = make([]string, 0)
	m := make(map[string]bool)
	for _, instant := range response.Data.InstanceList.Instance {
		region := instant.Region
		if _, ok := m[region]; !ok {
			m[region] = true
			regions = append(regions, region)
		}
	}

	totalCount = response.Data.TotalCount
	glog.Infof("[%s] query ecs region list SUCCESS, Maintained Region: %d", alias, len(regions))

	return nil
}
```

报错信息:

```bash
[SDK.JsonUnmarshalError] Failed to unmarshal response, but you can get the data via response.GetHttpStatusCode() and response.GetHttpContentString()
caused by:
bssopenapi.QueryAvailableInstancesResponse.Data: bssopenapi.Data.InstanceList: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|nceList":[{"Status":|..., bigger context ...|unt":71,"PageSize":20,"PageNum":1,"InstanceList":[{"Status":"Normal","SubStatus":"Normal","Subscript|...
```

**Comment by xiefulaithu** [comment]
@wenzuochao 

根据报错信息，business.aliyuncs.com返回的body中，`response.Data.InstanceList.Instance` InstanceList是一个slice，而不是struct。

下面是我打印的 `response.GetHttpContentString()`

```bash
{"Data":{"TotalCount":42,"PageSize":20,"PageNum":1,"InstanceList":[...]},"Message":"Successful!","RequestId":"BDFFDF30-24AB-4D86-93DC-4xxxxxxxxxxxx242","Success":true,"Code":"Success"}
```

**Comment by xiefulaithu** [comment]
@wenzuochao 

或者您提供一个QueryAvailableInstances函数的调用Demo？

**Comment by wenzuochao** [comment]
> @wenzuochao
> 
> 或者您提供一个latest版本的 QueryAvailableInstances 函数的调用 Demo ？

可能是bssopenapi的服务老旧，我们会尽快更新相应服务，感谢您的指正

**Comment by xiefulaithu** [comment]
@wenzuochao 

请问这个issue有新的进展吗？bssopenapi的返回值结构更新了吗？

**Comment by wenzuochao** [comment]
> @wenzuochao
> 
> 请问这个issue有新的进展吗？bssopenapi的返回值结构更新了吗？

这个很抱歉，目前还没更新，预计明天就能更新好，因为是生成器存在的问题，所以影响比较大

**Comment by xiefulaithu** [comment]
> > @wenzuochao
> > 请问这个issue有新的进展吗？bssopenapi的返回值结构更新了吗？
> 
> 这个很抱歉，目前还没更新，预计这周就能更新好，因为是生成器存在的问题，所以影响比较大

复测了一下，问题还在。mark。

**Comment by wenzuochao** [comment]
> > > @wenzuochao
> > > 请问这个issue有新的进展吗？bssopenapi的返回值结构更新了吗？
> > 
> > 
> > 这个很抱歉，目前还没更新，预计这周就能更新好，因为是生成器存在的问题，所以影响比较大
> 
> 复测了一下，问题还在。mark。
感谢您的关注，我们已经更新了最新代码，欢迎您下载最新的代码，相信您的问题已经能得到解决，感谢您的支持
