### ISSUE TITLE
创建请求时能否允许传递赋好值的指针

### ISSUE THREAD

**Issue by bringyou** [aliyun/alibaba-cloud-sdk-go#188]
现在的sdk，我们在使用的时候，一般需要先`createXXXRequest()`，获得基本的request对象后在往里面塞各种数据，就像下面这个
```go
accountReq := rds.CreateCreateAccountRequest()
accountReq.DBInstanceId = instanceId
accountReq.AccountName = "accountName"
accountReq.AccountPassword = generatePassword()
accountReq.AccountType = "Super"
```
能否提供带有request入参的函数，方便我们在调用的时候就赋值了？就像下面那样
```go
accountReq:=rds.CreateCreateAccountRequest(&CreateAccountRequest{
  AccountType:"Super",
})
```

**Comment by wenzuochao** [comment]
> 现在的sdk，我们在使用的时候，一般需要先`createXXXRequest()`，获得基本的request对象后在往里面塞各种数据，就像下面这个
> 
> ```go
> accountReq := rds.CreateCreateAccountRequest()
> accountReq.DBInstanceId = instanceId
> accountReq.AccountName = "accountName"
> accountReq.AccountPassword = generatePassword()
> accountReq.AccountType = "Super"
> ```
> 
> 能否提供带有request入参的函数，方便我们在调用的时候就赋值了？就像下面那样
> 
> ```go
> accountReq:=rds.CreateCreateAccountRequest(&CreateAccountRequest{
>   AccountType:"Super",
> })
> ```

感谢您的宝贵意见，但是我们这边的createXXXRequest()都是生成器统一生成的，暂不会做修改。
