### ISSUE TITLE
github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/utils.go:34:22: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by denverdino** [aliyun/alibaba-cloud-sdk-go#190]
* **Product and API**: All
* **Platform**: All
* **How to Reproduce** Include alibaba-cloud-sdk-go in the vendor of project, and without introduce the version 1.1.0 for github.com/satori/go.uuid

**Comment by wenzuochao** [comment]
> * **Product and API**: All
> * **Platform**: All
> * **How to Reproduce** Include alibaba-cloud-sdk-go in the vendor of project, and without introduce the version 1.1.0 for github.com/satori/go.uuid

Thank you for your advice, can you show me your code which will cause the error?

**Comment by denverdino** [comment]
From * github.com/satori/go.uuid version 1.2.0+, the signature for the NewV4 is changed

https://github.com/satori/go.uuid/blob/master/generator.go

func (g *rfc4122Generator) NewV4() (UUID, error)

**Comment by wenzuochao** [comment]
> From * github.com/satori/go.uuid version 1.2.0+, the signature for the NewV4 is changed
> 
> https://github.com/satori/go.uuid/blob/master/generator.go
> 
> func (g *rfc4122Generator) NewV4() (UUID, error)

Thank you! I will add description of the version of go.uuid in code soon!

**Comment by wenzuochao** [comment]
> > From * github.com/satori/go.uuid version 1.2.0+, the signature for the NewV4 is changed
> > https://github.com/satori/go.uuid/blob/master/generator.go
> > func (g *rfc4122Generator) NewV4() (UUID, error)
> 
> Thank you! I will add description of the version of go.uuid in code soon!

We have declared the version of go.uuid in https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/Gopkg.toml!

**Comment by denverdino** [comment]
Shall we update the dependency to the latest release? There are some conflicts when integrating with other packages.

**Comment by wenzuochao** [comment]
> Shall we update the dependency to the latest release? There are some conflicts when integrating with other packages.

But go.uuid's latest version is 1.2.0,  in 1.2.0, the signature for the NewV4 is not changed

**Comment by denverdino** [comment]
Ok, thanks
