### ISSUE TITLE
open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory

### ISSUE THREAD

**Issue by kaisawind** [aliyun/alibaba-cloud-sdk-go#193]
* **产品和接口**:
`ProcessCommonRequest`
* **平台**:
`docker 17.03.0-ce`
* **最小代码**:
```Go
response, err := client.ProcessCommonRequest(request)
	if err != nil {
		logrus.Errorln("ProcessCommonRequest Error:", err)
		return err
	}
```
---
使用了docker运行服务，但是docker当中没有zoneinfo.zip文件，所以会出错。
如果有error为什么不进行返回而要panic呢？

**Comment by wenzuochao** [comment]
> * **产品和接口**:
>   `ProcessCommonRequest`
> * **平台**:
>   `docker 17.03.0-ce`
> * **最小代码**:
> 
> ```go
> response, err := client.ProcessCommonRequest(request)
> 	if err != nil {
> 		logrus.Errorln("ProcessCommonRequest Error:", err)
> 		return err
> 	}
> ```
> 
> 使用了docker运行服务，但是docker当中没有zoneinfo.zip文件，所以会出错。
> 如果有error为什么不进行返回而要panic呢？

感谢您的建议，能麻烦您提供一下具体的报错信息吗？

**Comment by JacksonTian** [comment]
您可以参照这篇文章解决一下您的问题：http://blog.swiftflamel.com/tag/open-usrlocalgolibtimezoneinfo-zip/

**Comment by kaisawind** [comment]
@wenzuochao 
报错的信息没有保留，panic的位置参考
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/utils/utils.go#L59
SDK里面还有很多panic。Go语言不支持try catch，所以panic的话，服务就会退出。

@JacksonTian 
谢谢。问题解决并不难。我只是觉得不应该在SDK里主动panic。

**Comment by wenzuochao** [comment]
> @wenzuochao
> 报错的信息没有保留，panic的位置参考
> https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/utils/utils.go#L59
> SDK里面还有很多panic。Go语言不支持try catch，所以panic的话，服务就会退出。
> 
> @JacksonTian
> 谢谢。问题解决并不难。我只是觉得不应该在SDK里主动panic。

我们已经修改了相关代码，欢迎您下载最新代码，相信你的问题已经得到了解决，感谢您的支持
