### ISSUE TITLE
关于消息服务以及内容安全服务的支持

### ISSUE THREAD

**Issue by qiqizjl** [aliyun/alibaba-cloud-sdk-go#2]
刚发现阿里云官方居然出GoLang的SDK了。赞一个

但是我目前发现支持的服务有点少，是否后续有计划支持消息服务以及内容安全呢。

btw 是否可以提交PR，如果可以那么有对应的代码规范之类的么~

**Comment by qiqizjl** [comment]
咦 很奇怪的是 我在0.3的sdk看到了 但是在0.3.1又给删除了。。请问这有什么问题么。。0.3.0的sdk是否可用于生产呢。。

**Comment by gaort** [comment]
@qiqizjl 
首先十分感谢您的关注与反馈：D
go sdk会陆续扩展可以支持的产品，最终达到与官方Java SDK一样的支持范围，我们正在着手这件事情，所以这个周期不会很长。
当然是可以提交PR的:D，而且我们非常非常非常欢迎大家提交PR，目前相关的代码规范还没有编写完成，可以提前告知您的是，由于services目录下的代码全部是由代码生成器生成的，所以我们只接受对sdk目录(也就是core包)的PR。
0.3.0中的sdk可能会存在API Version错误的情况，会导致您的请求无法被正确处理，所以在0.3.1中移除了所有可能存在问题的sdk，因此暂时不建议您使用，建议您稍加等待。
如果您急需消息服务和内容安全服务的go sdk的话，您也可以使用common api来发送请求，相关的使用方法已经写在了README.md中。
如果有任何疑问可以直接在issue中提出，我们会尽快为您解答。
再次感谢您的反馈！

**Comment by qiqizjl** [comment]
非常感谢 我先使用common api调用

**Comment by qiqizjl** [comment]
@gaort 我看下了commonapi和green的api发现相差有点大。 green的api使用uri而不是apiname。而且请求用的是POST~ 看起来没法直接用commonapi来调用green 有什么办法兼容么~

**Comment by gaort** [comment]
@qiqizjl 收到
commonApi是可以支持green的这种调用风格的，你可以参考这段代码
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/client_test.go#L320
当PathPattern有值时，ApiName可以不填写

另外，我们刚刚发布了一个和此场景有关的bugfix，建议您更新下
