### ISSUE TITLE
dep导包失败

### ISSUE THREAD

**Issue by twojin** [aliyun/alibaba-cloud-sdk-go#201]
`$dep ensure -v -add github.com/aliyun/alibaba-cloud-sdk-go/sd`
? attempt github.com/aliyun/alibaba-cloud-sdk-go with 2 pkgs; 368 versions to try
(25)      try github.com/aliyun/alibaba-cloud-sdk-go@1.53.4
(26)  ✗   constraint ^0.2.2 on github.com/jmespath/go-jmespath disjoint with other dependers:
(26)    0b12d6b5 from github.com/aws/aws-sdk-go@v1.15.52 (no overlap)
(25)      try github.com/aliyun/alibaba-cloud-sdk-go@1.53.3
(26)  ✗   constraint ^0.2.2 on github.com/jmespath/go-jmespath disjoint with other dependers:
(26)    0b12d6b5 from github.com/aws/aws-sdk-go@v1.15.52 (no overlap)
(25)      try github.com/aliyun/alibaba-cloud-sdk-go@1.53.2
(26)  ✗   constraint ^0.2.2 on github.com/jmespath/go-jmespath disjoint with other dependers:
(26)    0b12d6b5 from github.com/aws/aws-sdk-go@v1.15.52 (no overlap)
(25)      try github.com/aliyun/alibaba-cloud-sdk-go@1.53.1
(26)  ✗   constraint ^0.2.2 on github.com/jmespath/go-jmespath disjoint with other dependers:
(26)    0b12d6b5 from github.com/aws/aws-sdk-go@v1.15.52 (no overlap)

![image](https://user-images.githubusercontent.com/31733409/53403101-f6abd700-39ed-11e9-8bc4-03e0e1e1bbf1.png)

**Comment by wenzuochao** [comment]
> constraint ^0.2.2 on github.com/jmespath/go-jmespath disjoint with other dependers:

Thanks for your advice! Could you tell me which version of jmespath you used?

**Comment by twojin** [comment]
不知道版本号，这是dep自动生成文件的信息：
`[[projects]]
digest = "1:6f49eae0c1e5dab1dafafee34b207aeb7a42303105960944828c2079b92fc88e"

name = "github.com/jmespath/go-jmespath"

packages = ["."]

pruneopts = ""

revision = "0b12d6b5"`

**Comment by twojin** [comment]
dep ensure -add 失败的原因是此sdk跟其他包使用的jmespath的版本不一样，导致冲突。然后我不用dep进行包管理，直接把此sdk复制到vendor目录下，使用短信服务时发生以下报错:
`[SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little?\ncaused by:\nPost https://dysmsapi.aliyuncs.com/?AccessKeyId=XXXXXX&Action=SendSms&Format=JSON&PhoneNumbers=XXXXXX&RegionId=default&SignName=XXXXXX&Signature=XXXXXX&SignatureMethod=HMAC-SHA1&SignatureNonce=XXXXXX&SignatureType=&SignatureVersion=1.0&TemplateCode=XXXXXX&TemplateParam=XXXXXX&Timestamp=2019-02-27T03%3A59%3A41Z&Version=2017-05-25: x509: failed to load system roots and no roots provided`

一个短信服务搞这么麻烦干什么？以前的rest api为什么不提供了？

**Comment by wenzuochao** [comment]
> dep ensure -add 失败的原因是此sdk跟其他包使用的jmespath的版本不一样，导致冲突。然后我不用dep进行包管理，直接把此sdk复制到vendor目录下，使用短信服务时发生以下报错:
> `[SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little?\ncaused by:\nPost https://dysmsapi.aliyuncs.com/?AccessKeyId=XXXXXX&Action=SendSms&Format=JSON&PhoneNumbers=XXXXXX&RegionId=default&SignName=XXXXXX&Signature=XXXXXX&SignatureMethod=HMAC-SHA1&SignatureNonce=XXXXXX&SignatureType=&SignatureVersion=1.0&TemplateCode=XXXXXX&TemplateParam=XXXXXX&Timestamp=2019-02-27T03%3A59%3A41Z&Version=2017-05-25: x509: failed to load system roots and no roots provided`
> 
> 一个短信服务搞这么麻烦干什么？以前的rest api为什么不提供了？

您的问题是由于访问第三方 ssl 的服务，缺少ca证书导致，如果方便的话，你可以安装一下root ca证书，然后重新调用该接口，或者您可以使用
`NewClientWithOptions(regionId string, config *Config, credential auth.Credential)` 来创建client，构造config时，您可以加入`config := sdk.NewConfig()
	config.HttpTransport = &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}`来跳过校验。

**Comment by twojin** [comment]
可以了使用了。
还存在的问题：别的包和这个sdk有相同的依赖包，但是dep配置的版本不同，就不能使用`dep ensure -add`添加这个sdk了。

**Comment by wenzuochao** [comment]
> 可以了使用了。
> 还存在的问题：别的包和这个sdk有相同的依赖包，但是dep配置的版本不同，就不能使用`dep ensure -add`添加这个sdk了。

您好，现在的问题是，如果我们去掉约束的话，当用户使用与我们sdk不兼容的包时，还是会出现错误，所以这个还是需要进一步的研究探讨之后才能确定下来。感谢您对我们的支持！
