### ISSUE TITLE
go 1.12 运行报错

### ISSUE THREAD

**Issue by zhuguofeng** [aliyun/alibaba-cloud-sdk-go#207]
..\github.com\aliyun\alibaba-cloud-sdk-go\sdk\utils\utils.go:30:9: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

**Comment by wenzuochao** [comment]
> ..\github.com\aliyun\alibaba-cloud-sdk-go\sdk\utils\utils.go:30:9: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

请问您使用的是什么版本的uuid呢？

**Comment by wenzuochao** [comment]
> > ..\github.com\aliyun\alibaba-cloud-sdk-go\sdk\utils\utils.go:30:9: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> 
> 请问您使用的是什么版本的uuid呢？

请问您的问题得到解决了吗？如果可以的话，麻烦您回复一下您的问题？希望在3月15号之后能得到您的回复，感谢您的支持。
