### ISSUE TITLE
ROA 风格的客户端疑似无法通过 MappingResolver 来获取 Endpoints

### ISSUE THREAD

**Issue by xh4n3** [aliyun/alibaba-cloud-sdk-go#208]
* **产品和接口**:任意 ROA 产品，使用任何接口
* **平台**: 任意平台
* **最小代码**:
```golang
package main

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints"
	"github.com/aliyun/alibaba-cloud-sdk-go/services/cr"
	"log"
)

func main() {
	req := cr.CreateGetNamespaceListRequest()
        // 打开以下注释就可以访问，用了 SimpleHostResolver
	//req.SetDomain("cr.cn-hongkong.aliyuncs.com")
        // MappingResolver 无法找到 endpoints，原因是其 TryResolve 方法中 param.Product 为空
	endpoints.AddEndpointMapping("cn-hongkong", "CR", "cr.cn-hongkong.aliyuncs.com")

	client, err := cr.NewClientWithOptions("cn-hongkong", sdk.NewConfig(),
		credentials.NewAccessKeyCredential("ID", "KEY"))
	if err != nil {
		log.Fatalln(err)
	}

	res, err := client.GetNamespaceList(req)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(res.GetHttpContentString())
}
```

在 https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/requests/roa_request.go#L137 这里，request.product = product 被注释掉了，但是 product 是在私有变量里面，无法在外部设置。

**Comment by JacksonTian** [comment]
直接用 SimpleHostResolver 不是更好吗

**Comment by xh4n3** [comment]
当然用 SimpleHostResolver 能绕过这个问题，但是用户需要在每次构造的 request 里面设置一下 endpoint。
我理解 MappingResolver 本来就是为了解决这个问题的吧。

**Comment by wenzuochao** [comment]
> 当然用 SimpleHostResolver 能绕过这个问题，但是用户需要在每次构造的 request 里面设置一下 endpoint。
> 我理解 MappingResolver 本来就是为了解决这个问题的吧。

我们已经合入相应的pr来解决问题了，您可以拉去最新的代码看一下问题是否得到解决，感谢您的支持！ #214

**Comment by xh4n3** [comment]
> > 当然用 SimpleHostResolver 能绕过这个问题，但是用户需要在每次构造的 request 里面设置一下 endpoint。
> > 我理解 MappingResolver 本来就是为了解决这个问题的吧。
> 
> 我们已经合入相应的pr来解决问题了，您可以拉去最新的代码看一下问题是否得到解决，感谢您的支持！ #214

多谢！
