### ISSUE TITLE
ecs.DescribeInstances 返回值 CreationTime 时间格式不正确

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#21]
问题描述：
首先，调用 ecs.DescribeInstances；然后，解析其返回值中 Instances.Instance 元素的 CreationTime 属性，会返回如下错误信息：
> parsing time "2017-01-17T09:41Z" as "2006-01-02T15:04:05Z07:00": cannot parse "Z" as ":"

问题分析：
应该是返回值 CreationTime 属性的格式不符合默认格式：time.RFC3339（"2006-01-02T15:04:05Z07:00"）。

**Comment by gaort** [comment]
@jancco2012 非常感谢您的反馈
建议您尝试指定格式来解析
因为不同语种下的默认时间格式可能不同，api设计时可能不会采用某个特定语言的默认格式:D

**Comment by jancco2012** [comment]
@gaort 好的，了解，谢谢！
