### ISSUE TITLE
translation to english missing

### ISSUE THREAD

**Issue by ellerbrock** [aliyun/alibaba-cloud-sdk-go#23]
hi alibaba team,

thanks for all the open source projects!
i'm e.g. currently in germany and would love to read through the docs :(
could we agree to use english as default language for the future?

![english please](https://media.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

cheers maik

**Comment by gaort** [comment]
@ellerbrock 
thanks for your feedback :D
we will publish these soon:
1. change README.md to English version, and mv current README.md to README_zh_cn.md
2. add English/Chinese comments in source codes
3. publish English version docs for this go sdk on www.alibabacloud.com

**Comment by ellerbrock** [comment]
@gaort thanks a lot!
the open source community will be very grateful for that decision.

![thank you](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif)
