### ISSUE TITLE
推送服务: 结构PushRequest里面, iOS相关部分的参数, 没有找到设置方法

### ISSUE THREAD

**Issue by zhongguo168a** [aliyun/alibaba-cloud-sdk-go#246]
结构PushRequest里面, iOS相关部分的参数, 没有找到设置方法

* **最小代码**:
代码位置: github.com/aliyun/alibaba-cloud-sdk-go/services/push/push.go: 77行

ps:  希望将来会有golang的demo :)

**Comment by wenzuochao** [comment]
> 结构PushRequest里面, iOS相关部分的参数, 没有找到设置方法
> 
> * **最小代码**:
>   代码位置: github.com/aliyun/alibaba-cloud-sdk-go/services/push/push.go: 77行
> 
> ps: 希望将来会有golang的demo :)
很抱歉对你造成困扰，对于您提出的问题，我们提了相关的pr #248 。欢迎您拉取最新的代码，相信您的问题已经得到了解决。至于golang的demo方面，欢迎您访问 https://api.aliyun.com/#/?product=Push&api=Push&params={}&tab=DEMO&lang=GO 这个网址，我们已经为您提供了相应的服务，感谢您对我们项目的支持。
