### ISSUE TITLE
关于openSearch的api支持不健全

### ISSUE THREAD

**Issue by Alllfred** [aliyun/alibaba-cloud-sdk-go#252]
关于openSearch的接口貌似目前只支持`listapps`，有计划支持更多如文档上报，搜索等接口吗？

**Comment by wenzuochao** [comment]
> 关于openSearch的接口貌似目前只支持`listapps`，有计划支持更多如文档上报，搜索等接口吗？

感谢您对我们项目的关注，我查询了一下关于openSearch的接口，目前只支持`listapps`，至于其他的接口什么时候能支持，是由openSearch相关产品的人员来决定的，所以我也无法给您准确的信息，非常抱歉，我们能做的就是在产品对我们开放了相关的接口之后，我们会尽快在sdk中进行更新。
