### ISSUE TITLE
使用 http.RoundTripper 作为 sdk.Config.HttpTransport 的参数类型

### ISSUE THREAD

**Issue by GotaX** [aliyun/alibaba-cloud-sdk-go#259]
* **产品和接口**:
```
sdk.NewClientWithOptions(regionId string, config *Config, credential auth.Credential) (client *Client, err error)
```
* **平台**:
* **最小代码**:
```
client, err = driver.NewClientWithOptions(
	region, &sdk.Config{HttpTransport: &ochttp.Transport{}}, cred)
```

Go 标准库中 `http.Client.Transport` 的类型实际上是 `http.RoundTripper` 接口, 而 config 中则使用的是 `*http.Transport`, 导致类似 opencensus 这样的 tracing 库无法通过设置 transport 的方式集成. 建议把这个参数改成 `http.RoundTripper` 接口类型.

**Comment by wenzuochao** [comment]
> opencensus 这样的 tracing 库无法通过设置 transport 的方式集成.

感谢您的建议，现在使用config的用户都是用的*http.Transport，修改类型可能导致很多用户无法正常使用，如果您有这个需求的话，那给client增加一个setTransport()方法，这样您就能集成tracing库了。对于这样的解决方案，您觉得怎么样呢？

**Comment by GotaX** [comment]
> 那给client增加一个setTransport()方法
这个简单的修复也不错, 不过我觉得最好是在 Config 里增加一个 RoundTriper 字段, 然后把老的 *Transport 字段标记为弃用, 之后的版本再逐步换掉. 因为 RoundTripper 算是包含 *Transport 的. 这样也算是保持设置的参数都还在 Config 里.

**Comment by wenzuochao** [comment]
> > 那给client增加一个setTransport()方法
> 
> 这个简单的修复也不错, 不过我觉得最好是在 Config 里增加一个 RoundTriper 字段, 然后把老的 *Transport 字段标记为弃用, 之后的版本再逐步换掉. 因为 RoundTripper 算是包含 *Transport 的. 这样也算是保持设置的参数都还在 Config 里.

感谢您提出的方法，我们会考虑您的建议，不过这个涉及到所有的请求，还需要进一步的评估，可能还需要一段时间才能实现。

**Comment by GotaX** [comment]
好的，我再补充一下。其实就算是把原先 config 的字段直接换成 RoundTriper 也是可以的，并不会影响到老的调用代码，因为 *Transport 本身就实现了 RoundTriper，这样这个字段的类型范围实际上是比原来更宽泛了。

**Comment by wenzuochao** [comment]
> 好的，我再补充一下。其实就算是把原先 config 的字段直接换成 RoundTriper 也是可以的，并不会影响到老的调用代码，因为 *Transport 本身就实现了 RoundTriper，这样这个字段的类型范围实际上是比原来更宽泛了。

有些用户写了个withTransPort（），然后入参是*Transport类型的，这个时候就有问题了，所以这个还需要再评估一下

**Comment by GotaX** [comment]
> 有些用户写了个withTransPort（），然后入参是*Transport类型的

有稍微具体的例子吗? 照理说即使入参是 *Transport 也是能直接被当作 RoundTriper 接口使用的

**Comment by wenzuochao** [comment]
> > 有些用户写了个withTransPort（），然后入参是*Transport类型的
> 
> 有稍微具体的例子吗? 照理说即使入参是 *Transport 也是能直接被当作 RoundTriper 接口使用的

主要是入参类型是*Transport，但是他传入的值为config. Transport,所以如果把config. Transport改为接口，就会出现问题了

**Comment by GotaX** [comment]
可以直接写个最简单的示例代码吗? 这样比较好理解.

**Comment by wenzuochao** [comment]
> 可以直接写个最简单的示例代码吗? 这样比较好理解.

func WithTransport(ts *http.Transport) 这么一个函数，如果传入config.Transport是不是就有问题了，如果Transport改成接口类型的话

**Comment by GotaX** [comment]
哦, 懂了, 原来是这个意思, 那确实是有这个问题. 那看来除了简单类型外, 结构体的配置还是写成 Option 接口的方式兼容性比较好, 不用直接对外暴露具体的类型.

**Comment by wenzuochao** [comment]
> 哦, 懂了, 原来是这个意思, 那确实是有这个问题. 那看来除了简单类型外, 结构体的配置还是写成 Option 接口的方式兼容性比较好, 不用直接对外暴露具体的类型.

这个就属于遗留问题，在修改的时候还是要考虑到兼容性的问题，所以还需要评估之后才能出方案

**Comment by wenzuochao** [comment]
很抱歉现在才回复你，这个我们仔细看了一下，因为现在我们的超时，代理这些操作都是基于http.Transport来实现的，当前版本不好做改动，感谢您对我们项目的支持。
