### ISSUE TITLE
Is there an api to get all resource groups?

### ISSUE THREAD

**Issue by lsytj0413** [aliyun/alibaba-cloud-sdk-go#266]
* **Product and API**:
* **Platform**:
* **How to Reproduce**

**Comment by wenzuochao** [comment]
Ecs:  DescribeSecurityGroups
Do you need this api?  If not, tell me which product you want to use.

**Comment by lsytj0413** [comment]
thanks for your reply. I need the api for resoruce group, witch is descibe at [this page](https://help.aliyun.com/document_detail/60203.html?spm=a2c4g.11186623.6.573.6b9a4673InIwNn), not the security group.

The other resource(such as ecs) have a ResourceGroupId field to associate with the resource group, it defined with the code blow:

```
type RunInstancesRequest struct {
	*requests.RpcRequest
	LaunchTemplateName          string                          `position:"Query" name:"LaunchTemplateName"`
	ResourceOwnerId             requests.Integer                `position:"Query" name:"ResourceOwnerId"`
	UniqueSuffix                requests.Boolean                `position:"Query" name:"UniqueSuffix"`
	HpcClusterId                string                          `position:"Query" name:"HpcClusterId"`
	SecurityEnhancementStrategy string                          `position:"Query" name:"SecurityEnhancementStrategy"`
	KeyPairName                 string                          `position:"Query" name:"KeyPairName"`
	SpotPriceLimit              requests.Float                  `position:"Query" name:"SpotPriceLimit"`
	ResourceGroupId             string                          `position:"Query" name:"ResourceGroupId"`
```

how can i get the ResourceGroupIp from any api?

**Comment by wenzuochao** [comment]
> thanks for your reply. I need the api for resoruce group, witch is descibe at [this page](https://help.aliyun.com/document_detail/60203.html?spm=a2c4g.11186623.6.573.6b9a4673InIwNn), not the security group.
> 
> The other resource(such as ecs) have a ResourceGroupId field to associate with the resource group, it defined with the code blow:
> 
> ```
> type RunInstancesRequest struct {
> 	*requests.RpcRequest
> 	LaunchTemplateName          string                          `position:"Query" name:"LaunchTemplateName"`
> 	ResourceOwnerId             requests.Integer                `position:"Query" name:"ResourceOwnerId"`
> 	UniqueSuffix                requests.Boolean                `position:"Query" name:"UniqueSuffix"`
> 	HpcClusterId                string                          `position:"Query" name:"HpcClusterId"`
> 	SecurityEnhancementStrategy string                          `position:"Query" name:"SecurityEnhancementStrategy"`
> 	KeyPairName                 string                          `position:"Query" name:"KeyPairName"`
> 	SpotPriceLimit              requests.Float                  `position:"Query" name:"SpotPriceLimit"`
> 	ResourceGroupId             string                          `position:"Query" name:"ResourceGroupId"`
> ```
> how can i get the ResourceGroupIp from any api?

I'm sorry to tell you that the api is not published, you  can only inquire it by viewing web page. Thanks for your support to our project.

**Comment by lsytj0413** [comment]
Is there any plan to publish this api?

**Comment by wenzuochao** [comment]
> Is there any plan to publish this api?

Sorry,  there is  not exact time yet.
