### ISSUE TITLE
cdn封禁相关没有支持

### ISSUE THREAD

**Issue by matao3754** [aliyun/alibaba-cloud-sdk-go#267]
BlockObjectCaches 这个接口相关功能没有支持

**Comment by wenzuochao** [comment]
> BlockObjectCaches 这个接口相关功能没有支持

产品发布是由产品方去操作的，我们会把你们的需求跟产品方说明，让他们尽快发布该接口

**Comment by wenzuochao** [comment]
> > BlockObjectCaches 这个接口相关功能没有支持
> 
> 产品发布是由产品方去操作的，我们会把你们的需求跟产品方说明，让他们尽快发布该接口。如果发布了，我们会尽快通知您。

与产品方联系确认，该接口不对外开放，所以sdk无法支持该接口。感谢您对我们sdk的支持。
