### ISSUE TITLE
iot模块缺失

### ISSUE THREAD

**Issue by Jack-Ji** [aliyun/alibaba-cloud-sdk-go#274]
OpenAPI Explorer中给出了Go语言的IOT服务调用示例，如下图：
![image](https://user-images.githubusercontent.com/1416077/57746165-8c5c2600-7702-11e9-9694-fb959bfe8b57.png)

然而我在sdk中未能找到对应的iot模块

**Comment by wenzuochao** [comment]
> OpenAPI Explorer中给出了Go语言的IOT服务调用示例，如下图：
> ![image](https://user-images.githubusercontent.com/1416077/57746165-8c5c2600-7702-11e9-9694-fb959bfe8b57.png)
> 
> 然而我在sdk中未能找到对应的iot模块

产品这块是由相关产品的人负责的，我帮您问一下情况，如果允许的话，会发布iot产品。感谢您对我们项目的支持。

**Comment by JacksonTian** [comment]
@Jack-Ji 在产品方没有发布独立的产品 SDK 之前，您可以使用 CommonRequest 的形式来使用 IoT 的OpenAPI： https://github.com/aliyun/alibaba-cloud-sdk-go#rpc-request

**Comment by Jack-Ji** [comment]
好的，谢谢 @JacksonTian

**Comment by JacksonTian** [comment]
我们合并了 IoT 的版本。请更新代码后使用。感谢您的反馈。

**Comment by Jack-Ji** [comment]
非常感谢！

另外我有个疑问，go sdk未来有没可能支持http2订阅iot设备状态通知？

Jackson Tian <notifications@github.com>于2019年5月16日 周四17:04写道：

**Comment by JacksonTian** [comment]
@Jack-Ji 有这个可能。

**Comment by Jack-Ji** [comment]
好的，希望能够尽快，因为有些设备厂商不支持rrpc调用的，大部分还是推荐订阅方式

Jackson Tian <notifications@github.com>于2019年5月16日 周四19:11写道：
