### ISSUE TITLE
支持go mod

### ISSUE THREAD

**Issue by coolyrat** [aliyun/alibaba-cloud-sdk-go#275]
使用go mod目前不能拉取tag,只能拉取到master.希望能够支持go mod
```bash
go get -u github.com/aliyun/alibaba-cloud-sdk-go/sdk
go: finding github.com/aliyun/alibaba-cloud-sdk-go/sdk latest
go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
go: finding github.com/jmespath/go-jmespath latest
```

**Comment by wenzuochao** [comment]
> 使用go mod目前不能拉取tag,只能拉取到master.希望能够支持go mod
> 
> ```shell
> go get -u github.com/aliyun/alibaba-cloud-sdk-go/sdk
> go: finding github.com/aliyun/alibaba-cloud-sdk-go/sdk latest
> go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
> go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
> go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
> go: finding github.com/jmespath/go-jmespath latest
> ```

Thanks for your advice! We wil fix it quickly.

**Comment by wenzuochao** [comment]
> > 使用go mod目前不能拉取tag,只能拉取到master.希望能够支持go mod
> > ```shell
> > go get -u github.com/aliyun/alibaba-cloud-sdk-go/sdk
> > go: finding github.com/aliyun/alibaba-cloud-sdk-go/sdk latest
> > go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
> > go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
> > go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190514094931-991357e60f09
> > go: finding github.com/jmespath/go-jmespath latest
> > ```
> 
> Thanks for your advice! We wil fix it quickly.

We hava fixed it in pr #276 , you can update latest code and try again. Glad to help you. We will close this issue after two days if you don't reply again.

**Comment by coolyrat** [comment]
I clean the old dependency and get again, there's an error occurred
```bash
go get github.com/aliyun/alibaba-cloud-sdk-go
go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
go: github.com/aliyun/alibaba-cloud-sdk-go@v0.0.0-20190515080340-55098cbcd2b3: parsing go.mod: unexpected module path "alibaba-cloud-sdk-go"
go: error loading module requirements
```

**Comment by dulumao** [comment]
go mod errors

go get -u github.com/aliyun/alibaba-cloud-sdk-go/sdk
go: finding github.com/aliyun/alibaba-cloud-sdk-go/sdk latest
go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
go: github.com/aliyun/alibaba-cloud-sdk-go@v0.0.0-20190515080340-55098cbcd2b3: parsing go.mod: unexpected module path "alibaba-cloud-sdk-go"
go get: error loading module requirements

**Comment by wenzuochao** [comment]
Sorry for my fault. I have reverted the commit. We will support go mod soon.

**Comment by wenzuochao** [comment]
> Sorry for my fault. I have reverted the commit. We will support go mod soon.

I have fixed it at the pull request #280,  and I have tested it, you can update latest code and try again. Glad to help you. We will close this issue after two days if you don't reply again.

**Comment by coolyrat** [comment]
I'm sorry, I think I'm not making myself clear enough. What I meant support go mod is to pull the latest tag when we use go get. Right now when I execute go get, I pull down a master branch. I think the tag should have a prefix v, e.g. v1.2.3. [more information](https://github.com/golang/go/wiki/Modules#what-are-some-implications-of-tagging-my-project-with-major-version-v0-v1-or-making-breaking-changes-with-v2)

**Comment by wenzuochao** [comment]
> I'm sorry, I think I'm not making myself clear enough. What I meant support go mod is to pull the latest tag when we use go get. Right now when I execute go get, I pull down a master branch. I think the tag should have a prefix v, e.g. v1.2.3. [more information](https://github.com/golang/go/wiki/Modules#what-are-some-implications-of-tagging-my-project-with-major-version-v0-v1-or-making-breaking-changes-with-v2)

Sorry for my misunderstanding. You can use `go get` with @version to pull the latest tag, when you meet the error of `cannot use path@version syntax in GOPATH mode`, you can  export GO111MODULE=on to avoid the error.

**Comment by coolyrat** [comment]
```bash
go get -u github.com/aliyun/alibaba-cloud-sdk-go@1.60.14
go: finding github.com/aliyun/alibaba-cloud-sdk-go 1.60.14
go: finding golang.org/x/time latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/baiyubin/aliyun-sts-go-sdk latest
go: finding github.com/jmespath/go-jmespath latest
go: finding golang.org/x/tools latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/smartystreets/assertions latest
go: finding github.com/gopherjs/gopherjs latest
go: finding github.com/smartystreets/goconvey latest
go: finding github.com/goji/httpauth latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest

go/src/testgomod
▶ cat go.mod
module testgomod

go 1.12

require (
	github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190518152016-3f5ef586ad4e // indirect
	github.com/aliyun/aliyun-oss-go-sdk v1.9.6 // indirect
	github.com/gopherjs/gopherjs v0.0.0-20190430165422-3e4dfb77656c // indirect
	github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af // indirect
	github.com/json-iterator/go v1.1.6 // indirect
	github.com/kr/pty v1.1.4 // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	github.com/smartystreets/assertions v0.0.0-20190401211740-f487f9de1cd3 // indirect
	github.com/stretchr/objx v0.2.0 // indirect
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/net v0.0.0-20190514140710-3ec191127204 // indirect
	golang.org/x/sys v0.0.0-20190516110030-61b9204099cb // indirect
	golang.org/x/text v0.3.2 // indirect
	golang.org/x/tools v0.0.0-20190517183331-d88f79806bbd // indirect
)
```

It's not showing a valid form in go.mod. But it solved my problem since you add the go.mod file. My colleagues will download the same version dependencies. Thank you.
