### ISSUE TITLE
SDK里有DescribeDBInstanceSwitchLog接口吗

### ISSUE THREAD

**Issue by welyss** [aliyun/alibaba-cloud-sdk-go#278]
主备切换日志的api有支持吗，查了api文档没找到
请求里action=DescribeDBInstanceSwitchLog
但是拉了sdk的源码搜了一下，好像也没找到

**Comment by wenzuochao** [comment]
> 主备切换日志的api有支持吗，查了api文档没找到
> 请求里action=DescribeDBInstanceSwitchLog
> 但是拉了sdk的源码搜了一下，好像也没找到

很抱歉没能及时回复您，您问的这个接口在sdk里是没有的，我们暂时无法做支持。请问你这个api的名字从哪里获知的呢？

**Comment by welyss** [comment]
我是从阿里rds管理页面里->日志管理->主备切换日志里，查询后查看request的action看到的，这个api好像是能用的，我直接通过api调传action=DescribeDBInstanceSwitchLog能调通，但是sdk里确实是没找到，暂时先用api传参的形式解决需求了

**Comment by wenzuochao** [comment]
> 我是从阿里rds管理页面里->日志管理->主备切换日志里，查询后查看request的action看到的，这个api好像是能用的，我直接通过api调传action=DescribeDBInstanceSwitchLog能调通，但是sdk里确实是没找到，暂时先用api传参的形式解决需求了

sdk的产品api都是由我们产品的人来统一发布的，这个api他们定为私有，我们这边是无法生成sdk提供给您的，只能劳烦您使用api传参的形式解决需求。
