### ISSUE TITLE
Data type of DescribeSnapshotsResponse...SourceDiskSize inconsistent with API document

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#28]
**Issue Description:**

As for property ecs.DescribeSnapshotsResponse.Snapshots.Snapshot[i].SourceDiskSize:
- In API document, its type is "Integer". (Ref: https://help.aliyun.com/document_detail/25641.html)
- In SDK, its type is "string".

Namely, their types are inconsistent.

PS: Their types are consistent in the previous version.

**Comment by gaort** [comment]
@jancco2012 
感谢您的反馈，这块是ecs的apiMeta出现了错误，我们已经将问题反馈给相关同事
