### ISSUE TITLE
调用pop的version无法修改，建议开放权限，其他语言都可以修改的

### ISSUE THREAD

**Issue by mark5678** [aliyun/alibaba-cloud-sdk-go#287]
* **产品和接口**:
* **平台**:
* **最小代码**:

![image](https://user-images.githubusercontent.com/51438141/59017196-8ecf1d00-8875-11e9-8748-af7642bf5fcd.png)

**Comment by wenzuochao** [comment]
> * **产品和接口**:
> * **平台**:
> * **最小代码**:
> 
> ![image](https://user-images.githubusercontent.com/51438141/59017196-8ecf1d00-8875-11e9-8748-af7642bf5fcd.png)

已经为request添加了SetVersion方法修改version，欢迎拉取最新的sdk代码。我将关闭该issue，如果您还有其他使用的问题，可以重新提issue，感谢您的使用。
