### ISSUE TITLE
aliyun-oss-go-sdk/sample/sign_url.go

### ISSUE THREAD

**Issue by wNee** [aliyun/alibaba-cloud-sdk-go#294]
这个用例里
```
signedURL, err = bucket.SignURL(objectKey, oss.HTTPGet, 60)
	if err != nil {
		HandleError(err)
	}
```
如果直接用浏览器打开signedURL，下载的文件会带有文件的信息，格式为 文件夹1名字_filename
有什么方式获得临时的url，下载的文件不带有文件夹路径的信息吗？

**Comment by wenzuochao** [comment]
> 这个用例里
> 
> ```
> signedURL, err = bucket.SignURL(objectKey, oss.HTTPGet, 60)
> 	if err != nil {
> 		HandleError(err)
> 	}
> ```
> 
> 如果直接用浏览器打开signedURL，下载的文件会带有文件的信息，格式为 文件夹1名字_filename
> 有什么方式获得临时的url，下载的文件不带有文件夹路径的信息吗？

您好， go sdk目前并不包含oss相关的业务，对于oss的接口我们这边也不太清楚，请在 https://github.com/aliyun/aliyun-oss-go-sdk/issues/new 创建issue。
