### ISSUE TITLE
建议版本号添加v字母开头，否则golang mod并不会识别

### ISSUE THREAD

**Issue by fifsky** [aliyun/alibaba-cloud-sdk-go#298]
如下，go get的依旧还是master最后一次commit的版本
```
go get github.com/aliyun/alibaba-cloud-sdk-go
go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190708083059-aab58a5390fe
go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190708083059-aab58a5390fe
```

然后，是否要删除一些古老的release tags，可能是因为tag实在太多了，经常拉不下来，报错如下

```
go get github.com/aliyun/alibaba-cloud-sdk-go
go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190705031012-59037b446353
package github.com/aliyun/alibaba-cloud-sdk-go: unknown import path "github.com/aliyun/alibaba-cloud-sdk-go": zip: not a valid zip file
```

**Comment by wenzuochao** [comment]
> 如下，go get的依旧还是master最后一次commit的版本
> 
> ```
> go get github.com/aliyun/alibaba-cloud-sdk-go
> go: finding github.com/aliyun/alibaba-cloud-sdk-go latest
> go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190708083059-aab58a5390fe
> go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190708083059-aab58a5390fe
> ```
> 
> 然后，是否要删除一些古老的release tags，可能是因为tag实在太多了，经常拉不下来，报错如下
> 
> ```
> go get github.com/aliyun/alibaba-cloud-sdk-go
> go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190705031012-59037b446353
> package github.com/aliyun/alibaba-cloud-sdk-go: unknown import path "github.com/aliyun/alibaba-cloud-sdk-go": zip: not a valid zip file
> ```

如果您是在main module下使用go get，是可以使用package@version来拉取指定的版本的。另外，我们的master跟最新的 release 几乎没差别，所以请放心使用。

**Comment by fifsky** [comment]
OK 谢谢

**Comment by stanxing** [comment]
这不是好的解决方案，建议还是应该按照 golang 的官方标准做 release，我也疑惑了半天为什么 go mod 安装出来的依赖版本是 v0.0.0 ...当然我也理解过程中可能会有很多历史遗留问题。

![Screenshot from 2019-11-11 20-00-09](https://user-images.githubusercontent.com/23288646/68585707-fab94f80-04bd-11ea-8e17-7143e5acd1c8.png)

https://blog.golang.org/publishing-go-modules
