### ISSUE TITLE
[Feature Request] 命名嵌套 struct 类型

### ISSUE THREAD

**Issue by morlay** [aliyun/alibaba-cloud-sdk-go#3]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/vpc/describe_vpcs.go#L85
嵌套类型不太方便用户使用的，比如数据的转存映射，不得不写到请求调用的函数中，不利于测试，代码风格也会比较混乱。

建议用 Action 作为前缀，以命名嵌套的 struct 类型，像这样
https://github.com/morlay/aliyun-go/blob/master/clients/vpc/operations.go#L2336

（几日前没注意官方有 go sdk，故从 java-sdk 中抓取生成了一版本 https://github.com/morlay/aliyun-go ）

另外，为什么 返回的 json 中
VSwitchIds 是 []VSwitchId
NatGatewayIds 是 []NatGatewayIds 而 RouterTableIds 是 []RouterTableIds

**Comment by gaort** [comment]
@morlay 
感谢您的反馈
1. 十分感谢您的建议，目前使用嵌套类型是因为在部分api中，存在“多个struct包含同名但不同结构的子struct”的场景，我们正在梳理这部分api，梳理完成后，会尝试修改为您建议的结构。
2. json中复数命名不规范的情况，已帮您转发给VPC的同事，相关回复我会通过这个issue传达给您。也建议您直接发起工单询问，可以得到更快更准确的回答。

**Comment by morlay** [comment]
@gaort 

问题 2 可由 Unmarshal interface 暴力处理。
List<xxx> Marshal 出来的 JSON 的格式固定, 但总会有多余的 wrapper，可以这样处理

```go
type DescribeNatGatewaysResponse struct {
	RequestId   string
	TotalCount  int
	PageNumber  int
	PageSize    int
	NatGateways DescribeNatGatewaysNatGatewayList
}

type DescribeNatGatewaysNatGatewayList []DescribeNatGatewaysNatGateway

func (list *DescribeNatGatewaysNatGatewayList) UnmarshalJSON(data []byte) error {
	m := make(map[string][]DescribeNatGatewaysNatGateway)
	err := json.Unmarshal(data, &m)
	if err != nil {
		return err
	}
	for _, v := range m {
		*list = v
		break
	}
	return nil
}
```
同时简化 struct 结构。

**Comment by gaort** [comment]
@morlay 了解
请问目前是vpc相关的sdk存在反序列化异常的情况吗？

**Comment by morlay** [comment]
@gaort
List 那种嵌套结构在 Go 里，只要 field 名称对应上，不会 Unmarshal 异常，只会丢失。

第一个版本 我是用的 https://github.com/denverdino/aliyungo 但接口更新不够及时，故抓取 Java SDK 自动生成 Go SDK。

但在抓取生成中，我只能通过 Java SDK 中的一些通用定义来生成代码。因此生成出来会是这样

```go
type XXX struct {
   NatGatewayIds struct {
      NatGatewayId []string
   }
}
```

但 JSON 中 NatGatewayIds 的值在 NatGatewayIds.NatGatewayId, 所以这个版本 NatGatewayId 信息 Unmarshal 的时候就拿不到值了。

所以干脆就生成 UnmarshalJSON 暴力取值以解决。

（目前，没计划迁移到官方 Go SDK，因为 issue 提到的那个问题，现在迁移改动还是比较大的）

**Comment by gaort** [comment]
@morlay 明白了，十分感谢您的详尽描述
我们会尽快支持[1]中提到的feature，届时我会第一时间在这个issue中反馈给您
再次感谢您的反馈

**Comment by gaort** [comment]
@morlay 
应答内部类抽离已经在pre-release分支解决
计划会在最近几天内发布
