### ISSUE TITLE
app推送设置IOSApnsEnv无效问题

### ISSUE THREAD

**Issue by shiguanghuxian** [aliyun/alibaba-cloud-sdk-go#300]
github.com/aliyun/alibaba-cloud-sdk-go/services/push/push.go
这个文件的92行中标签打错了，应该是

`	IOSApnsEnv                     string           `position:"Query" name:"iOSApnsEnv"``

**Comment by wenzuochao** [comment]
> github.com/aliyun/alibaba-cloud-sdk-go/services/push/push.go
> 这个文件的92行中标签打错了，应该是
> 
> `	IOSApnsEnv string `position:"Query" name:"iOSApnsEnv"``

对此我感到很抱歉，这个问题已经解决了，您可以拉取最新的 push 代码，再试一下。感谢您对我们项目的支持。

**Comment by shiguanghuxian** [comment]
push包无法编译，很多函数重复定义，是不是生成的代码，生成错了😂

**Comment by shiguanghuxian** [comment]
删除这两个文件就好了
![image](https://user-images.githubusercontent.com/13268627/61443040-52660500-a97b-11e9-9cd8-31f468c94673.png)

**Comment by wenzuochao** [comment]
> 删除这两个文件就好了
> ![image](https://user-images.githubusercontent.com/13268627/61443040-52660500-a97b-11e9-9cd8-31f468c94673.png)

非常抱歉，这是两个 go 文件的文件名不同，导致替换失败，所以出现这个问题，现在已经提pr解决这个问题了 #301 ,等 ci 过了就能合入。
