### ISSUE TITLE
需求建议：对 instance_type 进行模糊匹配

### ISSUE THREAD

**Issue by wangwenpei** [aliyun/alibaba-cloud-sdk-go#303]
你好，我们是Terraform重度用户，最后想了想，还是把 feature提到这里。

感谢阿里云对Terraform的支持，在国内厂商属于很靠前的厂商了，为我们带来了极大的便利性。

不过有一个痛点希望能解决下，阿里云的instance_type希望可以进行模糊的匹配。
我们现在经常遇到这样的情况，比如：开通2核4G的机器，因为阿里云2核4G有很多种机器，经常会导致原来配置好的Terraform因为机器售罄的缘故，我们要修改配置。这太不方便了。

从用户角度来说，我们不会特别在意2核4G不同机器之间的性能差距，如果有性能需求，我们会考虑增大核数和内存。

希望可以有类似的特性：

instance_type="generic-2-4096"         # 检查当generic-作为起始时，判定模糊匹配，选用2核4G的非突发性实例，不关心具体的实例类型 （最好能价格便宜的优先😂）。

**Comment by xiaozhu36** [comment]
@wangwenpei 你好，非常感谢你的需求建议，也非常欢迎使用阿里云的Terraform Provider. 有关实例规格库存这块儿，暂时没有好的办法。我们在返回数据前是会将那些库存的实例规格给过滤掉的，但是过滤之后，在创建实例时如果所选规格售罄，这种问题就只能靠云产品增加库存了。
有关模糊匹配的提议很好，但是现在云产品还不支持这个功能，terraform如果要支持，对现有的使用方式有影响，terraform 高度的状态一致性要求初入参都得保持一致，可能会存在一些未知的错误，这个需要评估。
2核4G的非突发性实例也会出现售罄的问题。

另外，下次如果有terraform的相关的问题，可以直接在 https://github.com/terraform-providers/terraform-provider-alicloud/issues 提交，以便快速解答。谢谢。

**Comment by wangwenpei** [comment]
好的，本来是想提交在provider项目的，但是扫了下代码，其实这个地方还是在SDK改动，上层直接使用比较好，所以就提在这里了。

**Comment by JacksonTian** [comment]
收到～我们内部先研究一下。

**Comment by wenzuochao** [comment]
你好，你这个问题还是需要产品去支持，sdk 并不是只支持这一个 api，不可能说为了一个 api 做这样的改动，但是产品可以为这个 api 做处理，麻烦您提个工单给产品，向他们说明情况。
