### ISSUE TITLE
提供媒体处理功能吗

### ISSUE THREAD

**Issue by JeffreyBool** [aliyun/alibaba-cloud-sdk-go#304]
提供媒体处理功能吗？

音视频转码。

**Comment by wenzuochao** [comment]
> 提供媒体处理功能吗？
> 
> 音视频转码。

这个功能是支持的，你可以使用https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/vod/submit_transcode_jobs.go 来完成该操作。具体的操作可以参考：https://help.aliyun.com/document_detail/68570.html?spm=a2c4g.11186623.2.47.60fc3f89eTkXZo

**Comment by JeffreyBool** [comment]
创建HLS标准加密工作流吗？ 

 https://help.aliyun.com/document_detail/59877.html?spm=a2c4g.11186623.6.780.182a4adeeM5Kog

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/62096732-46e9d680-b2b7-11e9-8f5d-37b554f58593.png)
这些功能都有哪些。还是全都有

**Comment by JeffreyBool** [comment]
是提供媒体处理吗？ 不是视频点播

**Comment by wenzuochao** [comment]
暂不支持媒体处理，这个是否支持是由产品方来决定的，不过您可以使用commonrequest来实现，我们这边会联系产品的人咨询情况，如果允许的话，该产品会尽快在sdk中提供使用。

**Comment by JeffreyBool** [comment]
commonrequest 在哪？

**Comment by JeffreyBool** [comment]
噢噢。自己实现是吧？

**Comment by JeffreyBool** [comment]
可以参照视频点播的 sdk 吗

**Comment by JeffreyBool** [comment]
想使用 https://help.aliyun.com/document_detail/101577.html?spm=a2c4g.11186623.6.979.4f4d6a583rd88H 

提交转码作业-HLS标准加密 这个。媒体处理 实现这个功能应该和视频点播差别不大吧

**Comment by wenzuochao** [comment]
> 想使用 https://help.aliyun.com/document_detail/101577.html?spm=a2c4g.11186623.6.979.4f4d6a583rd88H
> 
> 提交转码作业-HLS标准加密 这个。媒体处理 实现这个功能应该和视频点播差别不大吧

您好，我们已经发布了该产品的sdk，欢迎您下载使用。https://github.com/aliyun/alibaba-cloud-sdk-go/tree/master/services/mts

**Comment by JeffreyBool** [comment]
请问有 sdk 的文档吗

**Comment by wenzuochao** [comment]
如果您想了解如何使用sdk的话，您可以参考我们的readme文档：https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/README-CN.md

**Comment by JeffreyBool** [comment]
老哥啊。这没有 mts sdk 相关的说明呀

**Comment by wenzuochao** [comment]
> 老哥啊。这没有 mts sdk 相关的说明呀

你是想要类似与你发的链接里那种详细的操作吗？那个是没有的。

**Comment by JeffreyBool** [comment]
哪 sdk 提供 mts HLS标准加密 工作流的封装吗

**Comment by JeffreyBool** [comment]
不对。 这不是 mps 媒体处理。 是 mts 转码吧。。  媒体处理和媒体转码是同一个吗？ 有点懵逼

**Comment by wenzuochao** [comment]
> 不对。 这不是 mps 媒体处理。 是 mts 转码吧。。 媒体处理和媒体转码是同一个吗？ 有点懵逼

是同一个的，你可以找到对应的api的

**Comment by wenzuochao** [comment]
您要的HLS标准加密工作流可以通过AddMediaWorkflow这个api来实现。

**Comment by JeffreyBool** [comment]
谢谢了。可以加个 QQ 或者微信吗？ 有问题方便咨询你一下

**Comment by wenzuochao** [comment]
> 谢谢了。可以加个 QQ 或者微信吗？ 有问题方便咨询你一下

不好意思，我们这边不允许这样做，不过可以使用钉钉联系。可以的话，我加您。

**Comment by JeffreyBool** [comment]
我钉钉 17600085955
