### ISSUE TITLE
client创建之后能否复用

### ISSUE THREAD

**Issue by guader** [aliyun/alibaba-cloud-sdk-go#307]
请问可否全局创建一个client，多处并发使用该client进行诸如oss的client.PutObject()操作

**Comment by wenzuochao** [comment]
> 请问可否全局创建一个client，多处并发使用该client进行诸如oss的client.PutObject()操作

可以全局创建client，不过不同产品的client是不一样的

**Comment by guader** [comment]
> > 请问可否全局创建一个client，多处并发使用该client进行诸如oss的client.PutObject()操作
> 
> 可以全局创建client，不过不同产品的client是不一样的

也就是说vod的client可以只创建一个，然后放心地在各个协程中使用对吗？

**Comment by wenzuochao** [comment]
> > > 请问可否全局创建一个client，多处并发使用该client进行诸如oss的client.PutObject()操作
> > 
> > 
> > 可以全局创建client，不过不同产品的client是不一样的
> 
> 也就是说vod的client可以只创建一个，然后放心地在各个协程中使用对吗？

因为我们给client增加了一些例如超时这样的机制，这样的话，同个client在多个协程中会出现数据争用的情况，所以无法在各个协程中使用

**Comment by guader** [comment]
> > > > 请问可否全局创建一个client，多处并发使用该client进行诸如oss的client.PutObject()操作
> > > 
> > > 
> > > 可以全局创建client，不过不同产品的client是不一样的
> > 
> > 
> > 也就是说vod的client可以只创建一个，然后放心地在各个协程中使用对吗？
> 
> 因为我们给client增加了一些例如超时这样的机制，这样的话，同个client在多个协程中会出现数据争用的情况，所以无法在各个协程中使用

了解，非常感谢！
