### ISSUE TITLE
Prefix tags with 'v'

### ISSUE THREAD

**Issue by ialidzhikov** [aliyun/alibaba-cloud-sdk-go#308]
From [Go modules wiki in golang/go](https://github.com/golang/go/wiki/Modules):
> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. 

Note that
> The leading v is required.

Currently `github.com/aliyun/alibaba-cloud-sdk-go` module does not add the leading `v`.

---

Without the leading `v` in the tags, projects vendoring aliyun/alibaba-cloud-sdk-go and using go modules (de facto the standard) will have the following pseudo-version in their `go.mod`:

```
require (
	github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190603021944-12ad9f921c0b
)
```

which in this case corresponds to tag 1.60.33 (commit hash 12ad9f921c0b). 

If the tag is with the leading `v`, the `go.mod` would look like

```
require (
	github.com/aliyun/alibaba-cloud-sdk-go v1.60.33
)
```

**Comment by wenzuochao** [comment]
Thank you for your advice. I know what you mean, but you can use `go mod edit -require=""` to modify the version of sdk, such as `go mod edit  -require="github.com/aliyun/alibaba-cloud-sdk-go@1.60.7"`, and use `go mod tidy` to update your vendoring.

**Comment by nevill** [comment]
@wenzuochao Even though, I still think it's a good idea to follow [golang's smever](https://golang.org/pkg/cmd/go/internal/semver/), it's a package built by Go anyway.

**Comment by wenzuochao** [comment]
> @wenzuochao Even though, I still think it's a good idea to follow [golang's smever](https://golang.org/pkg/cmd/go/internal/semver/), it's a package built by Go anyway.

We  don't  release a new version  when we merge a pr about core, but when we  merge a pr about product, so we want user to use master branch.If without `v`, when you pull sdk, you will pull the master rather than latest release.

**Comment by wenzuochao** [comment]
if could，i will close this issue in two days. If you have any problem about other, welcome to open an issue.
