### ISSUE TITLE
Client.go 中的 DoActionWithSigner 导致TCP 连接耗尽

### ISSUE THREAD

**Issue by WalkerLiuFei** [aliyun/alibaba-cloud-sdk-go#310]
* **产品和接口**:
* **平台**:
* **最小代码**:

**Comment by WalkerLiuFei** [comment]
产品和接口:
平台:
最小代码:

**Comment by JacksonTian** [comment]
亲，有进一步的信息吗

**Comment by WalkerLiuFei** [comment]
> 亲，有进一步的信息吗
不好意思，我使用的产品是KMS，我照着文档拼接的参数，在大量调用 DoAction 这个方法后，会造成TCP连接没有释放。

我大概看了下 client.go 中 DoActionWithSigner方法源码，好像是 在读取完毕Reponse 的Body后没有主动对Body 进行Close, 导致TCP连接没有复用，造成的资源泄露，麻烦你们确认下哪？

**Comment by WalkerLiuFei** [comment]
`func doKmsRequest(actionName, text string) *C.char {
	var result string
	var err error
	defer func() {
		if r := recover(); r != nil {
			//limit function can't be delete
		}
	}()
	client, _ := sdk.NewClientWithAccessKey(REGION_ID, ACCESS_KEY_ID, ACCESS_SECRET_ID)
	c := credentials.NewAccessKeyCredential(ACCESS_KEY_ID, ACCESS_SECRET_ID)
	s := signers.NewAccessKeySigner(c)
	// set request parameters
	request := requests.NewCommonRequest() // Make a common request
	request.ConnectTimeout = time.Second * 3
	request.Method = "GET"
	request.Domain = DOMAIN
	request.Port = PORT
	request.Scheme = requests.HTTPS
	request.Version = VERSION
	request.AcceptFormat = FORMAT
	request.ApiName = actionName
	if actionName == ENCRYPT {
		request.QueryParams["KeyId"] = KEY_ID
		request.QueryParams["Plaintext"] = text
	} else if actionName == DECRYPT {
		request.QueryParams["CiphertextBlob"] = text
	}
	request.TransToAcsRequest()
	auth.Sign(request, s, REGION_ID)
	response := &responses.CommonResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	err = client.DoAction(request, response)
	if err != nil {
		str := err.Error()
		str = strings.Replace(str, ACCESS_KEY_ID, "", -1)
		str = strings.Replace(str, ACCESS_SECRET_ID, "", -1)
		str = strings.Replace(str, KEY_ID, "", -1)
		return C.CString("Exception Occur : " + str)
	}
	responseMap := make(map[string]string)
	json.Unmarshal(response.GetHttpContentBytes(), &responseMap)
	if actionName == ENCRYPT {
		result = responseMap["CiphertextBlob"]
	} else if actionName == DECRYPT {
		result = responseMap["Plaintext"]
	} else {
		result = "Decrypt / Encrypt failed"
	}
	return C.CString(result)
}`

**Comment by WalkerLiuFei** [comment]
以上是我的代码

**Comment by wenzuochao** [comment]
> 以上是我的代码

能发一下报错信息吗？

**Comment by WalkerLiuFei** [comment]
> > 以上是我的代码
> 
> 能发一下报错信息吗？

 [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
caused by:
Get https://kms.cn-hongkong.aliyuncs.com:443/?AccessKeyId=&Action=Encrypt&Format=json&KeyId=&Plaintext=2bb70c7a514e83b9f51ac63fbc2dde1d&RegionId=cn-hongkong&Signature=NsP0EVilLTZlvl7U2DoCBTVKiIQ%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=1e887086f684228792965e1adabcf65a&SignatureType=&SignatureVersion=1.0&Timestamp=2019-08-06T08%3A05%3A08Z&Version=2016-01-20: dial tcp 47.89.5.101:443: i/o timeout

**Comment by wenzuochao** [comment]
> > > 以上是我的代码
> > 
> > 
> > 能发一下报错信息吗？
> 
> [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
> caused by:
> Get https://kms.cn-hongkong.aliyuncs.com:443/?AccessKeyId=&Action=Encrypt&Format=json&KeyId=&Plaintext=2bb70c7a514e83b9f51ac63fbc2dde1d&RegionId=cn-hongkong&Signature=NsP0EVilLTZlvl7U2DoCBTVKiIQ%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=1e887086f684228792965e1adabcf65a&SignatureType=&SignatureVersion=1.0&Timestamp=2019-08-06T08%3A05%3A08Z&Version=2016-01-20: dial tcp 47.89.5.101:443: i/o timeout

这个是连接超时，请求服务端都没请求成功，可能是网络原因，你这边可以重试一下，或者把ConnectTimeout调大一点

**Comment by JacksonTian** [comment]
就是国内到香港的网络问题吧。

**Comment by WalkerLiuFei** [comment]
我犯了个致命错误，没有 reuse  client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。

**Comment by theharveyz** [comment]
> 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。

请问你最后是如何解决的？ client 重用的逻辑能分享下吗？

**Comment by wenzuochao** [comment]
> > 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。
> 
> 请问你最后是如何解决的？ client 重用的逻辑能分享下吗？
你好，请问你这边使用上出现什么问题呢？能把报错信息发一下吗？

**Comment by theharveyz** [comment]
> > > 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。
> > 
> > 
> > 请问你最后是如何解决的？ client 重用的逻辑能分享下吗？
> > 你好，请问你这边使用上出现什么问题呢？能把报错信息发一下吗？

您好，报错信息如下：
```
[SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
```
我们最近新上线功能逻辑是定时同步阿里云资源以及指标，在10月2号某一刻同步突然暂停；查看日志发现大量如上报错信息；并观察到自程序上线之后，连接数缓慢上升。 重启服务后，同步继续。
目前是每次同步时 都会 new 一个 ECS、VPC、监控等的Client，我是不是需要对client进行全局缓存（根据配置的 access key，region 等作为唯一key）？

**Comment by wenzuochao** [comment]
> > > > 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。
> > > 
> > > 
> > > 请问你最后是如何解决的？ client 重用的逻辑能分享下吗？
> > > 你好，请问你这边使用上出现什么问题呢？能把报错信息发一下吗？
> 
> 您好，报错信息如下：
> 
> ```
> [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
> ```
> 
> 我们最近新上线功能逻辑是定时同步阿里云资源以及指标，在10月2号某一刻同步突然暂停；查看日志发现大量如上报错信息；并观察到自程序上线之后，连接数缓慢上升。 重启服务后，同步继续。
> 目前是每次同步时 都会 new 一个 ECS、VPC、监控等的Client，我是不是需要对client进行全局缓存（根据配置的 access key，region 等作为唯一key）？

您可以对client全局缓存，应该能解决你的问题。

**Comment by theharveyz** [comment]
> > > > > 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。
> > > > 
> > > > 
> > > > 请问你最后是如何解决的？ client 重用的逻辑能分享下吗？
> > > > 你好，请问你这边使用上出现什么问题呢？能把报错信息发一下吗？
> > 
> > 
> > 您好，报错信息如下：
> > ```
> > [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
> > ```
> > 
> > 
> > 我们最近新上线功能逻辑是定时同步阿里云资源以及指标，在10月2号某一刻同步突然暂停；查看日志发现大量如上报错信息；并观察到自程序上线之后，连接数缓慢上升。 重启服务后，同步继续。
> > 目前是每次同步时 都会 new 一个 ECS、VPC、监控等的Client，我是不是需要对client进行全局缓存（根据配置的 access key，region 等作为唯一key）？
> 
> 您可以对client全局缓存，应该能解决你的问题。

通过阅读源码，我发现问题出在这里：
[](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/client.go#L490)
```
func (client *Client) setTimeout(request requests.AcsRequest) {
	readTimeout, connectTimeout := client.getTimeout(request)
	client.httpClient.Timeout = readTimeout
	if trans, ok := client.httpClient.Transport.(*http.Transport); ok && trans != nil {
		trans.DialContext = Timeout(connectTimeout)
		client.httpClient.Transport = trans
	} else {
                // 每次 new Client 都会创建一个连接池    <-----------------
		client.httpClient.Transport = &http.Transport{
			DialContext: Timeout(connectTimeout),
		}
	}
}
```
我建议上面在新创建 http.Transport 时，能够将 IdleConnTimeout 设置成与 DefaultTransport 一致的值（90s）。

**Comment by wenzuochao** [comment]
> > > > > > 我犯了个致命错误，没有 reuse client，导致App 和 KMS之间的 TCP 连接没有断开，最后耗尽了TCP连接，造成资源泄露。
> > > > > 
> > > > > 
> > > > > 请问你最后是如何解决的？ client 重用的逻辑能分享下吗？
> > > > > 你好，请问你这边使用上出现什么问题呢？能把报错信息发一下吗？
> > > 
> > > 
> > > 您好，报错信息如下：
> > > ```
> > > [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
> > > ```
> > > 
> > > 
> > > 我们最近新上线功能逻辑是定时同步阿里云资源以及指标，在10月2号某一刻同步突然暂停；查看日志发现大量如上报错信息；并观察到自程序上线之后，连接数缓慢上升。 重启服务后，同步继续。
> > > 目前是每次同步时 都会 new 一个 ECS、VPC、监控等的Client，我是不是需要对client进行全局缓存（根据配置的 access key，region 等作为唯一key）？
> > 
> > 
> > 您可以对client全局缓存，应该能解决你的问题。
> 
> 通过阅读源码，我发现问题出在这里：
> https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/client.go#L490
> 
> ```
> func (client *Client) setTimeout(request requests.AcsRequest) {
> 	readTimeout, connectTimeout := client.getTimeout(request)
> 	client.httpClient.Timeout = readTimeout
> 	if trans, ok := client.httpClient.Transport.(*http.Transport); ok && trans != nil {
> 		trans.DialContext = Timeout(connectTimeout)
> 		client.httpClient.Transport = trans
> 	} else {
>                 // 每次 new Client 都会创建一个连接池    <-----------------
> 		client.httpClient.Transport = &http.Transport{
> 			DialContext: Timeout(connectTimeout),
> 		}
> 	}
> }
> ```
> 
> 我建议上面在新创建 http.Transport 时，能够将 IdleConnTimeout 设置成与 DefaultTransport 一致的值（90s）。

感谢您的建议，建议您使用 NewClientWithOptions函数来创建client，你可以通过设置config里的transport来设置IdleConnTimeout

**Comment by theharveyz** [comment]
@wenzuochao 嗯，是的，我改成了这个方法去创建Client，目前连接泄露的问题得到了解决。谢谢您的解答~
