### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by shiguanghuxian** [aliyun/alibaba-cloud-sdk-go#313]
[SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"afs","RegionId":"default","LocationProduct":"afs","LocationEndpointType":"openAPI"}), please check your accessKey with secret, and read the user guide

caused by:
[SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
caused by:
Get https://location-readonly.aliyuncs.com/?

一直报x509: certificate signed by unknown authority 不知哪里bug

**Comment by wenzuochao** [comment]
> [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"afs","RegionId":"default","LocationProduct":"afs","LocationEndpointType":"openAPI"}), please check your accessKey with secret, and read the user guide
> 
> caused by:
> [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
> caused by:
> Get https://location-readonly.aliyuncs.com/?
> 
> 一直报x509: certificate signed by unknown authority 不知哪里bug

我们现在的ConnectTimeout为5s，肯定是够用的，你那边能确认一下是否是网络原因导致的？一般建立链接是不需要5s的，或者您可以指定一下endpoint，这样我们就不会去帮你去请求获取endpoint了

**Comment by shiguanghuxian** [comment]
已解决
我程序在docker中运行，镜像基于alpine
需要这样
```
RUN  apk update \
  &&   apk add ca-certificates \
  &&   update-ca-certificates
```
