### ISSUE TITLE
CMS: DeleteSiteMonitors fails to umarshall response correctly

### ISSUE THREAD

**Issue by arafato** [aliyun/alibaba-cloud-sdk-go#319]
Hi--,

I'm working on Mac OS Mojave.

DeleteSiteMonitors fails to umarshall response correctly.

```
response.GetHttpContentString() outputs 

{"Data":{"count":1},"Message":"请求成功","RequestId":"816A99BB-9598-4FD1-9DCF-4C818C555397","Success":true,"Code":"200"}
```

The error object, however, is always != nil (due to the unmarshaling producing an error).

The error is

```
&errors.ClientError{errorCode:"SDK.JsonUnmarshalError", message:"Failed to unmarshal response, but you can get the data via response.GetHttpStatusCode() and response.GetHttpContentString()", originError:(*errors.errorString)(0xc420b5a020)}
```

**Comment by wenzuochao** [comment]
You can click the [Order](https://aone.alibaba-inc.com/project/787242/noAccess#userId=23275211&openTaskId=22964248)  to  track the progress.
