### ISSUE TITLE
缺少对可选择字段场景的处理

### ISSUE THREAD

**Issue by liukeyou** [aliyun/alibaba-cloud-sdk-go#323]
比如接口中有字段是可选的，但当前request序列化后传递给服务端是一个golang对应类型的缺省值
------------------------------------
有几种解法：
1. swagger方式：将必须字段作为函数参数，可选字段包在xxxRequestOps中，使用Optional包，如果set了，就加进去
2. 其他语言sdk方式（如java）：在自动生成时将所有参数设置成私有，对request的复制必须通过setXXX完成，在调用setXXX时构造json，在http请求时直接取json

**Comment by wenzuochao** [comment]
> ## 比如接口中有字段是可选的，但当前request序列化后传递给服务端是一个golang对应类型的缺省值
> 有几种解法：
> 
> 1. swagger方式：将必须字段作为函数参数，可选字段包在xxxRequestOps中，使用Optional包，如果set了，就加进去
> 2. 其他语言sdk方式（如java）：在自动生成时将所有参数设置成私有，对request的复制必须通过setXXX完成，在调用setXXX时构造json，在http请求时直接取json

感谢您的意见，sdk现在没有缺省值的，我们不会把为空的字段加入到真正的请求里

**Comment by wenzuochao** [comment]
> ## 比如接口中有字段是可选的，但当前request序列化后传递给服务端是一个golang对应类型的缺省值
> 有几种解法：
> 
> 1. swagger方式：将必须字段作为函数参数，可选字段包在xxxRequestOps中，使用Optional包，如果set了，就加进去
> 2. 其他语言sdk方式（如java）：在自动生成时将所有参数设置成私有，对request的复制必须通过setXXX完成，在调用setXXX时构造json，在http请求时直接取json

感谢您的意见，这个问题我们也思考过，比如把每个参数都设成指针，这样就可以判断是否为用户设值，还是为缺省值，但是这个对目前的 sdk 影响太大，预计会在下个大版本的时候做出修改。

**Comment by wenzuochao** [comment]
> ## 比如接口中有字段是可选的，但当前request序列化后传递给服务端是一个golang对应类型的缺省值
> 有几种解法：
> 
> 1. swagger方式：将必须字段作为函数参数，可选字段包在xxxRequestOps中，使用Optional包，如果set了，就加进去
> 2. 其他语言sdk方式（如java）：在自动生成时将所有参数设置成私有，对request的复制必须通过setXXX完成，在调用setXXX时构造json，在http请求时直接取json

感谢您的建议，请问您可以给我一个具体的例子吗？因为我们对这块其实是有做处理的。缺省值一般是不会传递给服务器的。

**Comment by liukeyou** [comment]
举个具体场景：
 需要将intfA的param1（原来的值为xxx），修改成param1=""

**Comment by wenzuochao** [comment]
> 举个具体场景：
> 需要将intfA的param1（原来的值为xxx），修改成param1=""

这个问题暂时无法解决，因为 go 的字符串缺省值就为 “”，我们无法判断这个 “” 是用户设置的，还是缺省值。想要支持这个判断的话，对现有代码的改动太大，我们会在下一个大版本的时候去支持对缺省值的判断。

**Comment by liukeyou** [comment]
所以要通过其他方式来支持可选，参照前面提的两个方案

**Comment by wenzuochao** [comment]
> 所以要通过其他方式来支持可选，参照前面提的两个方案

前面的两种方案，兼容性较差，修改之后会影响到很多用户的体验。
