### ISSUE TITLE
功能请求：iot product 增加物模型导入

### ISSUE THREAD

**Issue by stepdc** [aliyun/alibaba-cloud-sdk-go#328]
hi,在使用sdk注册自定义设备的过程中，发现没有物模型相关的API，每次创建新的设备都需要手动导入一下，可否增加相关的API哇，谢谢

**Comment by wenzuochao** [comment]
> 物模型

您具体指的是哪一个接口呢？我这边可以帮您查一下这个接口是否是开放的。

**Comment by stepdc** [comment]
已经找到这个接口是通过linkkit那边来调用的。。
