### ISSUE TITLE
短信接口缺少短信模板和短信签名的相关功能

### ISSUE THREAD

**Issue by jonyjeffry** [aliyun/alibaba-cloud-sdk-go#329]
* **产品和接口**:
* **平台**:
* **最小代码**:

**Comment by jonyjeffry** [comment]
缺少功能

**Comment by wenzuochao** [comment]
> 缺少功能

我们的产品都是由产品方发布的，我这边跟产品方确认一下，如果可以的话，我们会尽快发布具有短信模板和短信签名相关功能的 SDK。感谢您的支持。

**Comment by wenzuochao** [comment]
你好，短信接口已支持短信模板和短信签名的相关功能，麻烦您下载最新的 sdk。
