### ISSUE TITLE
1.60.136 tag多处重复

### ISSUE THREAD

**Issue by cpys** [aliyun/alibaba-cloud-sdk-go#333]
* **产品和接口**:
* **平台**:
* **最小代码**:

例：
``` alibaba-cloud-sdk-go/services/ecs/add_tags.go``` line 88, Key Value 重复

**Comment by wenzuochao** [comment]
> * **产品和接口**:
> * **平台**:
> * **最小代码**:
> 
> 例：
> ` alibaba-cloud-sdk-go/services/ecs/add_tags.go` line 88, Key Value 重复
对此我们感到非常抱歉，您可以拉取master分支的代码，我们已经将错误的 Ecs 代码回滚了。

**Comment by wenzuochao** [comment]
> > * **产品和接口**:
> > * **平台**:
> > * **最小代码**:
> > 
> > 例：
> > ` alibaba-cloud-sdk-go/services/ecs/add_tags.go` line 88, Key Value 重复
> > 对此我们感到非常抱歉，您可以拉取master分支的代码，我们已经将错误的 Ecs 代码回滚了。

您可以拉取最新的 sdk，我们已经发布了正确的 ecs 代码，感谢您的支持。
