### ISSUE TITLE
sms的问题

### ISSUE THREAD

**Issue by jonyjeffry** [aliyun/alibaba-cloud-sdk-go#334]
* **产品和接口**:
* **平台**:
* **最小代码**:

// SendSmsRequest is the request struct for api SendSms
type SendSmsRequest struct {
	*requests.RpcRequest
	SmsUpExtendCode      string           `position:"Query" name:"SmsUpExtendCode"`
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	SignName             string           `position:"Query" name:"SignName"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	PhoneNumbers         string           `position:"Query" name:"PhoneNumbers"`
	OutId                string           `position:"Query" name:"OutId"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	TemplateCode         string           `position:"Query" name:"TemplateCode"`
	TemplateParam        string           `position:"Query" name:"TemplateParam"`
}
这个request在实例化的时候没有调用RpcRequest的init（）方法 在调用SendSms方法的时候程序走到buildRequestWithSigner方法里第一行GetHeaders直接panic了，尝试调用request的initApi...时request.init()又panic了

**Comment by wenzuochao** [comment]
很抱歉对您造成困扰，你可以使用 CreateSendSmsRequest 方法，这个方法会帮您初始化RpcRequest。
