### ISSUE TITLE
能不能控制下发版本的频率，一天刷十个版本，有必要吗？

### ISSUE THREAD

**Issue by netroby** [aliyun/alibaba-cloud-sdk-go#335]
能不能控制下发版本的频率，一天刷十个版本，有必要吗？

**Comment by wenzuochao** [comment]
对此我们感到非常抱歉，为了让用户能及时使用到最新的产品 sdk，我们现在发版本是跟产品发布同步的，今天发布了多个产品 sdk，导致发版本的频率有点高。

**Comment by JacksonTian** [comment]
@netroby 抱歉，我们今天有较多的产品发布。如果不涉及到您使用的产品的话，可以暂时不用更新的。

**Comment by Golemstorm** [comment]
发布频繁就算了  也不做做向前兼容   :(

**Comment by wenzuochao** [comment]
> 发布频繁就算了 也不做做向前兼容 :(

您指的是产品 api 吗？因为现在 sdk 只支持 一个版本的产品 sdk，所以没办法做到向前兼容，不过我们可以在 changlog 里增加发布更改的产品及日期版本信息，这样的话，您就可以选择更新到某个版本，您看这样可以吗？
