### ISSUE TITLE
cdn查询所有域名接口希望增加cname是否生效状态

### ISSUE THREAD

**Issue by EverCurse** [aliyun/alibaba-cloud-sdk-go#337]
如果一个域名已经配置了 但是cname中途切走了 那么我希望DescribeUserDomains这个接口能提示cname的状态

**Comment by wenzuochao** [comment]
很抱歉，这个超出我们的权限范围，我们这边是负责产品的 sdk 的维护，无法去实现这个功能，建议您给产品方提需求，他们增加相应功能并发布对应版本的 sdk 之后，您就可以使用该功能了。
