### ISSUE TITLE
SDK包调用问题

### ISSUE THREAD

**Issue by luckydog612** [aliyun/alibaba-cloud-sdk-go#338]
使用阿里云移动推送业务时，发现push包下只有IOS相关的方法，没有安卓相关的方法，但阿里云官方库中安卓相关的方法是存在的，我找到对应的文件push_message_to_android.go上面有一个错误提示 “push_message_to_android.go doesn`t match to target system. File will be ignored by build tool.”根据后面的提示，我修改了(我使用的是Goland开发工具，File-->Setting-->Go-->Build Tags&Vendoring)对应的OS(从windows改为android)，那个错误就没了，但是编译不过去，提示安卓的方法未定义。最后试了好多次，把push_message_to_android.go的文件名改为了push_message_to_windows.go(那个windows是随便写的)，然后就可以调用了，也可以编译运行了。后来当我把push_message_toi_os.go(IOS相关的方法文件)的文件名改成push_message_to_android.go，然后IOS相关的方法也调用不了了(问题同上)，请问这是为什么？

**Comment by wenzuochao** [comment]
这个是因为 go 环境把 push_message_to_android.go 当成只在 android 环境才编译的文件。我这边会统一修改文件名，很抱歉对您造成困扰。

**Comment by wenzuochao** [comment]
您好，该问题已经解决，麻烦您拉取最新的 push 包代码。

**Comment by xiefulaithu** [comment]
https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072

@wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。

`push_message_to_android.go doesn`t match to target system. File will be ignored by build tool.` 这个问题又出现了

**Comment by wenzuochao** [comment]
> [552d359#diff-a323889a229cbdfa264a95245e7ef072](https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072)
> 
> @wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。
> 
> `push_message_to_android.go doesn't match to target system. File will be ignored by build tool.` 这个问题又出现了

产品重新发布了产品，导致旧的代码被删除，我们这边看一下能不能更好的解决这个问题

**Comment by wenzuochao** [comment]
> > [552d359#diff-a323889a229cbdfa264a95245e7ef072](https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072)
> > @wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。
> > `push_message_to_android.go doesn't match to target system. File will be ignored by build tool.` 这个问题又出现了
> 
> 产品方重新发布了产品 sdk，导致旧的代码被删除，我们这边看一下能不能更好的解决这个问题

我这边先手动更新一下，想根本解决问题还是要双 11 之后。 @ #352

**Comment by xiefulaithu** [comment]
> > > [552d359#diff-a323889a229cbdfa264a95245e7ef072](https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072)
> > > @wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。
> > > `push_message_to_android.go doesn't match to target system. File will be ignored by build tool.` 这个问题又出现了
> > 
> > 
> > 产品方重新发布了产品 sdk，导致旧的代码被删除，我们这边看一下能不能更好的解决这个问题
> 
> 我这边先手动更新一下，想根本解决问题还是要双 11 之后。 @ #352

好的，Thx！

**Comment by wenzuochao** [comment]
> [552d359#diff-a323889a229cbdfa264a95245e7ef072](https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072)
> 
> @wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。
> 
> `push_message_to_android.go doesn't match to target system. File will be ignored by build tool.` 这个问题又出现了

pr 已经合入了，您可以拉取最新的代码，相信您的问题已经得到解决了。

**Comment by xiefulaithu** [comment]
> > [552d359#diff-a323889a229cbdfa264a95245e7ef072](https://github.com/aliyun/alibaba-cloud-sdk-go/commit/552d359b638d71ed12266e8e5b69c9ba37d1e55d#diff-a323889a229cbdfa264a95245e7ef072)
> > @wenzuochao 在上面的提交中，你的 “modify push api name“ 的改动被 revert 了。
> > `push_message_to_android.go doesn't match to target system. File will be ignored by build tool.` 这个问题又出现了
> 
> pr 已经合入了，您可以拉取最新的代码，相信您的问题已经得到解决了。

已确认，问题已解决。

感谢，辛苦了！
