### ISSUE TITLE
Should never use panic for error

### ISSUE THREAD

**Issue by winlinvip** [aliyun/alibaba-cloud-sdk-go#34]
![image](https://user-images.githubusercontent.com/2777660/35250990-29539c84-0014-11e8-882e-d7b60a00d508.png)

**Comment by gaort** [comment]
@winlinvip thanks for you feedback!
This is just a sample code that we hope users understand how to use Aliyun Go SDK quickly.
And it's not the user's final code because users has their own code style.
Let's do not discuss how to deal with Go's error here :D
