### ISSUE TITLE
ecs需要新增字段

### ISSUE THREAD

**Issue by zhyc9de** [aliyun/alibaba-cloud-sdk-go#345]
struct `Instance` 补充 `PrivateIpAddresses ` 字段
参考http接口文档：https://help.aliyun.com/document_detail/25506.html?spm=a2c4g.11186623.2.28.2bf76f42Pmv8cm

**Comment by wenzuochao** [comment]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/82808b8a45c12e94d78d6766eb130d4eca2da2e5/services/ecs/describe_instances.go#L81 最新的 ecs 是有这个字段的。

**Comment by zhyc9de** [comment]
哦，不好意思，在返回结构体的`VpcAttributes `里找到了
