### ISSUE TITLE
Aliyun registry service premium(enterprise) edition support

### ISSUE THREAD

**Issue by barryz** [aliyun/alibaba-cloud-sdk-go#347]
We use ACR-Enterprise as our registry service.  The `services/cr` package does not work on  ACR-Enterprise, plz upgrade your sdk. Thanks

**Comment by wenzuochao** [comment]
> We use ACR-Enterprise as our registry service. The `services/cr` package does not work on ACR-Enterprise, plz upgrade your sdk. Thanks

Could you tell what problem had happened?

**Comment by barryz** [comment]
Aliyun registry service is the major cloud registry provider of our company. I have created several **enterprise instances** via aliyun console. Then I use the sdk `services/cr` in our integration system which to interact with aliyun. But the sdk `services/cr` does not work as expectation. So I speculated about the sdk may incompatible with **enterprise instances** .

**Comment by wenzuochao** [comment]
i can't resolve this problem  without enough message.
