### ISSUE TITLE
Typo: Use entries instead of entrys

### ISSUE THREAD

**Issue by jinmiaoluo** [aliyun/alibaba-cloud-sdk-go#353]
Like title says.

**Comment by wenzuochao** [comment]
Thank you for your support to our project. Ecs sdk is generated automatically，so though you modify this problem now, it will occur next time when the sdk is generated automatically again. So you may make a work order to Ecs developers to solve the problem fundamentally.

**Comment by wenzuochao** [comment]
Do you have any other questions? If not, we will close issue in 2 days。

**Comment by jinmiaoluo** [comment]
No, you can close issue now. 

Sent from Jinmiao Luo
