### ISSUE TITLE
能否提供一下go语言调用api网关发布的api的示例代码

### ISSUE THREAD

**Issue by tianbingchao** [aliyun/alibaba-cloud-sdk-go#356]
能否提供一下go语言调用api网关发布的api的示例代码
目前api网关管理控制台提供的示例代码没有go语言的

**Comment by wenzuochao** [comment]
你好，您可以使用 https://api.aliyun.com/#/?product=CloudAPI&api=DescribeApiHistory&params={}&tab=DEMO&lang=GO 在线调用 api。

**Comment by tianbingchao** [comment]
这里面的demo的演示都是调用阿里云官方api  我说的是怎么调用api网关发布的api
https://help.aliyun.com/document_detail/29470.html?spm=a2c4g.11174283.6.567.50317d246WfDW3

这里的

**Comment by wenzuochao** [comment]
这个目前还不在我们的服务范围之内，所以我对这一块也不清楚，您可以找一下 @ailan-gl

**Comment by wenzuochao** [comment]
我们先关闭这个 issue，如果您还有其他问题，欢迎 reopen 或者重新开启一个 issue。
