### ISSUE TITLE
Please add copyright statement (license compliance)

### ISSUE THREAD

**Issue by onlyjob** [aliyun/alibaba-cloud-sdk-go#357]
As LICENSE requires, please consider adding [copyright statement](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/LICENSE#L189).
Thanks.

https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/LICENSE#L178

**Comment by wenzuochao** [comment]
Thanks for your suggestion, we have add copyright statement at #359 .

**Comment by wenzuochao** [comment]
The pull request is merged, may I close  the issue? If you have other suggestions, you can open a new issue.
