### ISSUE TITLE
About Alibaba Cloud SDK Code Generator

### ISSUE THREAD

**Issue by flazx** [aliyun/alibaba-cloud-sdk-go#363]
浏览代码的时候发现，很多代码都是通过Alibaba Cloud SDK Code Generator生成的，这个代码生成器的代码是开源的吗？这是类似于gRpc protoc工具生成的代码吧，里头的核心代码都能自动生成吗？

**Comment by wenzuochao** [comment]
您好，生成器代码不是开源的，目前仅限内部使用

**Comment by wenzuochao** [comment]
如果没别的问题的话，我这边先关闭issue，如果您还有其他问题，欢迎重开或者另开一个issue，感谢您的支持
