### ISSUE TITLE
向文本库中添加文本，返回解析错误

### ISSUE THREAD

**Issue by baizhiwen** [aliyun/alibaba-cloud-sdk-go#370]
* **Product and API**:

![image](https://user-images.githubusercontent.com/17311712/70210959-ed1a8100-176e-11ea-9267-4e82d4cd92ec.png)

返回

// CreateKeywordResponse is the response struct for api CreateKeyword
type CreateKeywordResponse struct {
	*responses.BaseResponse
	RequestId          string   `json:"RequestId" xml:"RequestId"`
	SuccessCount       int      `json:"SuccessCount" xml:"SuccessCount"`
	InvalidKeywordList []string `json:"InvalidKeywordList" xml:"InvalidKeywordList"`
	ValidKeywordList   []string `json:"validKeywordList" xml:"validKeywordList"`
}

* **Platform**:
* **How to Reproduce**
返回解析报错
[SDK.JsonUnmarshalError] Failed to unmarshal response, but you can get the data via response.GetHttpStatusCode() and response.GetHttpContentString()\ncaused by:\ngreen.CreateKeywordResponse.ValidKeywordList: []string: fuzzyStringDecoder: not number or string or bool, error found in #10 byte of ...|ordList\":[{\"id\":3336|..., bigger context ...|{\"InvalidKeywordList\":[],\"validKeywordList\":[{\"id\":3336749,\"keyword\":\"mmmmmm\"}],\"SuccessCount\":|...

**Comment by wenzuochao** [comment]
很抱歉对您造成困扰，这个问题是后端服务器真实返回跟我们定义的不一致造成的，我们这边会尽快联系产品修改。

**Comment by wenzuochao** [comment]
跟产品方沟通过了，确实是定义的问题，不过现在封网，无法发布，您可以手动修改一下结构，后续更新的时候我们再通知您。

**Comment by baizhiwen** [comment]
> 跟产品方沟通过了，确实是定义的问题，不过现在封网，无法发布，您可以手动修改一下结构，后续更新的时候我们再通知您。

好的，谢谢。

**Comment by wenzuochao** [comment]
很抱歉让您久等了，产品方已经修改了这个问题，麻烦您拉取最新的 sdk，看一下问题是否解决，如果问题已经不存在了，麻烦您关闭一下issue。
