### ISSUE TITLE
查询可用区实例类型zone不支持

### ISSUE THREAD

**Issue by fanux** [aliyun/alibaba-cloud-sdk-go#373]
```
reate and run instance failed : SDK.ServerError
ErrorCode: OperationDenied.NoStock
Recommend: 
RequestId: 918180F7-1A8D-462E-A984-D8EE81536052
Message: The resource is out of stock in the specified zone. Please try other types, or choose other regions and zones.
```
我是通过查询实例类型接口获取到的实例类型，结果该可用区几乎所有zone都不支持该类型，查询实例类型接口应该增加zone参数。

以下代码是我想获取对应CPU核数与内存的实例类型。
```
	request := ecs.CreateDescribeInstanceTypesRequest()
	request.Scheme = "https"

	cpu, mem := getCPUandMemory(flavor)
	if cpu == 0 || mem == 0 {
		fmt.Errorf("cpu or mem is 0, can't get flavor")
		return ""
	}

	response, err := a.client.DescribeInstanceTypes(request)
	if err != nil {
		fmt.Print(err.Error())
	}

	for _, res := range response.InstanceTypes.InstanceType {
		if res.MemorySize == mem && res.CpuCoreCount == cpu {
			fmt.Printf("flavor is : %s %d %f %s", res.InstanceTypeId, res.CpuCoreCount, res.MemorySize, flavor)
			return res.InstanceTypeId
		}
	}
	return ""
```

**Comment by fanux** [comment]
查询接口并没有什么问题如在cn-beijing查询2C4G的机型，查询结果：ecs.s2.large 但是具体的zone cn-beijing-c并不支持该机型，这就非常难用了。

**Comment by fanux** [comment]
希望在request加入zone参数，或者有啥其它优雅的方式？  我想获取一个zone下面的机型（指定CPU和内存的机型）

**Comment by wenzuochao** [comment]
您好，我看了一下文档，应该是您使用的 api 有问题，您可以换一个API。https://help.aliyun.com/document_detail/25620.html?spm=a2c4g.11174283.6.1196.732a52fe51gVp2

**Comment by wenzuochao** [comment]
如果没有其他问题话，我就关闭这个 issue 了，如果您还有其他问题，欢迎重新打开这个 issue 或者另开一个 issue， 感谢您对我们项目的支持。

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/70989097-fd7f1400-20fd-11ea-89f6-5875aa8c747f.png)

调用接口没问题，这个接口本身也没问题能返回结果，只是到zone就无法使用

**Comment by wenzuochao** [comment]
DescribeInstanceTypes仅查询所有ECS实例规格的详情。如果您需要查询具体地域下可购买的实例规格，请使用DescribeAvailableResource

**Comment by fanux** [comment]
我就说阿里不会做的这么差嘛，肯定是我调错接口了, 感谢~

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/71050136-5f339280-217f-11ea-878c-6e78f2838d4c.png)
顺便提个bug,这里应该是requests.NewFloat

**Comment by wenzuochao** [comment]
感谢您的反馈，不过这个 explorer 不是我们这边负责的，我会帮您跟他们反馈。
