### ISSUE TITLE
DescribeSnapshots API: SourceDiskSize field in response

### ISSUE THREAD

**Issue by lwangrabbit** [aliyun/alibaba-cloud-sdk-go#374]
* **Product and API**:
DescribeSnapshots GO API

* **Platform**:
CentOS7 
go version go1.11.5

* **How to Reproduce**
SourceDiskSize in DescribeSnapshots GO API's response string is Integer, but in aliyun API，it should be string, and SourceDiskSize in DescribeSnapshotsResponse.Snapshots is alse String.

Detail of DescribeSnapshots GO API's response string:
{"PageNumber":1,"TotalCount":1,"PageSize":10,"RequestId":"30A5E9E0-ECD7-4FCA-BB9E-4820E060BB09","Snapshots":{"Snapshot":[{"Description":"Description","ProductCode":"","SnapshotName":"SnapshotName","SnapshotSN":"*****","Encrypted":false,**"SourceDiskSize":20**,"Progress":"100%","Usage":"none","SourceStorageType":"disk","CreationTime":"2019-12-19T12:19:49Z","Tags":{"Tag":[]},"Status":"accomplished","KMSKeyId":"","SourceDiskType":"data","SourceDiskId":"******4","SnapshotId":"*******","LastModifiedTime":"2019-12-19T12:20:51Z"}]}}

**Comment by wenzuochao** [comment]
I got it.  I will fixed it as son as possible.

**Comment by wenzuochao** [comment]
You can modify the SourceDiskSize's type to int by yourself, when i fixed it, i will tell you to pull the latest code.
