### ISSUE TITLE
服务端视频信息接口无法获取视频时长

### ISSUE THREAD

**Issue by tttlkkkl** [aliyun/alibaba-cloud-sdk-go#377]
用golang 服务端 sdk 获取视频信息，时长字段 Duration 返回0值。

* **产品和接口**:
视频点播服务，获取视频信息
* **平台**:
服务端api
* **最小代码**:
```golang
	req := vod.CreateGetVideoInfoRequest()
	req.VideoId = videoID
	rep, err := video.client.GetVideoInfo(req)
	fmt.Println(rep.Video.Duration)
```

**Comment by tttlkkkl** [comment]
视频大小只有几秒的时候必现

**Comment by wenzuochao** [comment]
> 视频大小只有几秒的时候必现

很抱歉对您造成困扰，您的意思是如果视频文件大的时候，是能正确返回一个 float 类型的数是吗

**Comment by tttlkkkl** [comment]
@wenzuochao 是的视频很小的时候返回0，视频大一些的时候是 float 数值

**Comment by wenzuochao** [comment]
您那边可以给 vod 的人提工单吗？我看了 sdk，定义的类型就是 float，现在的问题应该是 vod 的服务器返回有问题，这个我们这边解决不了。
