### ISSUE TITLE
STS: Does not allow to configure different endpoint

### ISSUE THREAD

**Issue by arafato** [aliyun/alibaba-cloud-sdk-go#388]
Hi--, 

currently it is not possible to configure a different endpoint for STS. The default `sts.aliyuncs.com` is always used.
This feature is needed for performance reasons (the default endpoint is hosted in China resulting in big latency from calls outside of China). It is also needed to be aligned with Terraform since it supports overriding the STS endpoint (https://www.terraform.io/docs/providers/alicloud/index.html#sts)

**Comment by wenzuochao** [comment]
> endpoint

How do you configure a different endpoint for STS?  It should be allowed by sdk.

**Comment by arafato** [comment]
OK, then the issue is in the Terraform provider since it does not use these methods. Thanks!
