### ISSUE TITLE
Mqtt鉴权申请Token的service没有找到

### ISSUE THREAD

**Issue by lubaoyilang** [aliyun/alibaba-cloud-sdk-go#389]
链接 ：[https://help.aliyun.com/document_detail/54276.html?spm=a2c4g.11186623.6.574.16a257d2ajoDhz](url)

请帮忙看一下

**Comment by wenzuochao** [comment]
请问您是在哪使用的这个产品呢？我看了我们的产品列表，没有相关的 SDK。

**Comment by lubaoyilang** [comment]
@wenzuochao 

用的 MQ系列产品中，MQTT 微消息队列。
需要 生成 Token 鉴权

**Comment by wenzuochao** [comment]
> @wenzuochao
> 
> 用的 MQ系列产品中，MQTT 微消息队列。
> 需要 生成 Token 鉴权

能发一下产品 sdk 的链接吗？

**Comment by lubaoyilang** [comment]
@wenzuochao 

https://help.aliyun.com/document_detail/54274.html?spm=a2c4g.11186623.6.573.67b631de8hPTuX

**Comment by wenzuochao** [comment]
> @wenzuochao
> 
> https://help.aliyun.com/document_detail/54274.html?spm=a2c4g.11186623.6.573.67b631de8hPTuX

产品 SDK 是由产品负责生成，我们无法控制产品提供那些 api，如果您想相关的需求，可以给产品方提工单。
