### ISSUE TITLE
Error on calling several APIs: Specified signature nonce was used already

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#39]
**[Description]:**

When calling the following APIs:
- vpc.DescribeVpcs (HostId: vpc.ap-southeast-2.aliyuncs.com)
- slb.DescribeLoadBalancers (HostId: slb.ap-southeast-3.aliyuncs.com)
- rds.DescribeDBInstances (HostId: rds.ap-southeast-3.aliyuncs.com)

They return the common error:
> SDK.ServerError 400 Bad Request {"Recommend":"https://error-center.aliyun.com/status/search?Keyword=SignatureNonceUsed&source=PopGw","Message":"Specified signature nonce was used already.","RequestId":"4BC02B9F-6E54-4346-9B2C-5B9896F66540","HostId":"rds.ap-southeast-3.aliyuncs.com","Code":"SignatureNonceUsed"}

**[Context]:**
1. This error doesn't always occur, just sometimes within lots of requests.
2. It seems all the errors occured in "ap-southeast-x" pattern regions. (But not sure!)

**Comment by gaort** [comment]
@jancco2012 
Thanks for your feedback!
This is a bug and has been fixed in 0.9.1, update your sdk and this situation will go away.

Before 0.9.1, when there's a  timeout or server-side error, sdk will automatically retry, if the server received the previous request, this problem occurs.
