### ISSUE TITLE
ecs Instance struct 字段有重复

### ISSUE THREAD

**Issue by chanyipiaomiao** [aliyun/alibaba-cloud-sdk-go#392]
services/ecs/struct_instance.go  CPU有2个  OsType 有2个
go1.13.8 window 运行不通过 报错: Duplicated key 'ostype' in struct ecs.Instance

**Comment by wenzuochao** [comment]
对此我们感到非常抱歉，您可以先手动修改重复的字段，如果成功运行了，我们这边按照您的修改发个版本。

**Comment by chanyipiaomiao** [comment]
删除  CPU                        int                                  `json:"CPU" xml:"CPU"`

**Comment by chanyipiaomiao** [comment]
删除 CPU  int  `json:"CPU" xml:"CPU"`       OsType  string `json:"OsType" xml:"OsType"` 可以正常运行

**Comment by wenzuochao** [comment]
这个结构体会被多个api使用，删除了这两个属性，会导致其他api的返回出现缺失，如果我们要发版本的话，只能考虑修改字段名，您试一下修改字段名能不能解决您的问题。

**Comment by chanyipiaomiao** [comment]
我把重复字段中的一个重命名之后,可以正常运行. 不过还有个建议,能不能tag里面加上 mongodb的tag 比如: `json:"Memory" xml:"Memory" bson:Memory`

**Comment by wenzuochao** [comment]
这个很抱歉，sdk只提供最基本的调用api服务，tag里加上其他的字段的需求我们无法满足。
