### ISSUE TITLE
希望SDK支持下kubernetes AttachInstance接口

### ISSUE THREAD

**Issue by knightXun** [aliyun/alibaba-cloud-sdk-go#393]
https://www.alibabacloud.com/help/zh/doc-detail/86807.htm?spm=a2c63.p38356.b99.457.28c754aa24Ndn2 这份文档里面有AttachInstance到kubernetes的Restful接口，但是SDK里面没有，使用起来非常麻烦，希望在SDK里面直接添加一下，这样比较方便。

**Comment by wenzuochao** [comment]
> https://www.alibabacloud.com/help/zh/doc-detail/86807.htm?spm=a2c63.p38356.b99.457.28c754aa24Ndn2 这份文档里面有AttachInstance到kubernetes的Restful接口，但是SDK里面没有，使用起来非常麻烦，希望在SDK里面直接添加一下，这样比较方便。

sdk 目前是根据产品配置的数据来生成 api的，我刚才看了一下，没搜到该接口的相关信息，您可以跟产品那边提一下需求，或者你可以使用 common request 来实现 https://github.com/aliyun/alibaba-cloud-sdk-go#roa-request

**Comment by knightXun** [comment]
@wenzuochao 这个项目提供dinding群之类的么？方便交流

**Comment by wenzuochao** [comment]
> @wenzuochao 这个项目提供dinding群之类的么？方便交流

没有的。你可以直接去给产品提工单

**Comment by wenzuochao** [comment]
我这边先关闭 issue，如果您还有问题，欢迎重新提 issue或者重新打开这个issue。
