### ISSUE TITLE
cmd的QueryMetricList怎么不见了

### ISSUE THREAD

**Issue by zeusro** [aliyun/alibaba-cloud-sdk-go#396]
* **产品和接口**:
cms 的 QueryMetricList 接口

API 文档: 
https://help.aliyun.com/document_detail/141669.html?spm=5176.11065259.1996646101.searchclickresult.32242c63n2tptG

* **平台**:

github.com/aliyun/alibaba-cloud-sdk-go v1.61.35

mac

* **最小代码**:
无

**Comment by zeusro** [comment]
找到了,现在叫`DescribeMetricList`
你们能不能更新一下产品文档?

**Comment by zeusro** [comment]
https://help.aliyun.com/document_detail/51936.html?spm=a2c4g.11186623.2.22.25f2750e1pxeLJ

这个接口, Datapoints内容明明是  json ,但是为什么定义的确实 string?

是因为你们没泛化 Datapoints 这个字段,觉得它无法用一个固定的结构体描述吗?

**Comment by wenzuochao** [comment]
> [DescribeMetricList](https://help.aliyun.com/document_detail/51936.html?spm=a2c4g.11186623.2.22.25f2750e1pxeLJ)
> 
> 这个接口, Datapoints内容明明是 json ,但是为什么定义的确实 string?
> 
> 是因为你们没泛化 Datapoints 这个字段,觉得它无法用一个固定的结构体描述吗?

产品文档是由产品那边编写的，我们这边没权限去修改，您可以给 cms 产品方提工单

**Comment by zeusro** [comment]
> > [DescribeMetricList](https://help.aliyun.com/document_detail/51936.html?spm=a2c4g.11186623.2.22.25f2750e1pxeLJ)
> > 这个接口, Datapoints内容明明是 json ,但是为什么定义的确实 string?
> > 是因为你们没泛化 Datapoints 这个字段,觉得它无法用一个固定的结构体描述吗?
> 
> 产品文档是由产品那边编写的，我们这边没权限去修改，您可以给 cms 产品方提工单

知道了,那第二个问题呢,我发现你们Datapoints的结构是string,golang SDK也是定义string.

但里面其实是另外一个json text.

这个又是什么原因

**Comment by wenzuochao** [comment]
> > > [DescribeMetricList](https://help.aliyun.com/document_detail/51936.html?spm=a2c4g.11186623.2.22.25f2750e1pxeLJ)
> > > 这个接口, Datapoints内容明明是 json ,但是为什么定义的确实 string?
> > > 是因为你们没泛化 Datapoints 这个字段,觉得它无法用一个固定的结构体描述吗?
> > 
> > 
> > 产品文档是由产品那边编写的，我们这边没权限去修改，您可以给 cms 产品方提工单
> 
> 知道了,那第二个问题呢,我发现你们Datapoints的结构是string,golang SDK也是定义string.
> 
> 但里面其实是另外一个json text.
> 
> 这个又是什么原因

我们这边负责提供工具而已，产品的api配置，是由产品那边弄的，因为他们才清楚应该定义成什么类型，我们只是负责根据他们的配置生成 sdk 来给用户使用。如果您发现产品的返回跟定义的类型不一致，你可以给产品那边提工单。

**Comment by zeusro** [comment]
Thx.
