### ISSUE TITLE
[Feature Request] API XXXRequest.Invoke(c *sdk.Client) (*XXXResponse, error)

### ISSUE THREAD

**Issue by morlay** [aliyun/alibaba-cloud-sdk-go#4]
希望能提供如题接口，并且 Request 组合的 *requests.RpcRequest 可以隐藏，方便使用。

```go
type DescribeVpcsRequest struct {
	ResourceOwnerId      int64  `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string `position:"Query" name:"ResourceOwnerAccount"`
	VpcId                string `position:"Query" name:"VpcId"`
	OwnerAccount         string `position:"Query" name:"OwnerAccount"`
	Name                 string `position:"Query" name:"Name"`
	PageSize             int    `position:"Query" name:"PageSize"`
	IsDefault            string `position:"Query" name:"IsDefault"`
	OwnerId              int64  `position:"Query" name:"OwnerId"`
	PageNumber           int    `position:"Query" name:"PageNumber"`
}

func (r DescribeVpcsRequest) Invoke(client *sdk.Client) (response *DescribeVpcsResponse, err error) {
	req := struct {
		*requests.RpcRequest
		DescribeVpcsRequest
	}{
		&requests.RpcRequest{},
		r,
	}
	req.InitWithApiInfo("Vpc", "2016-04-28", "DescribeVpcs", "vpc", "")

	resp := struct {
		*responses.BaseResponse
		DescribeVpcsResponse
	}{
		BaseResponse: &responses.BaseResponse{},
	}
	response = &resp.DescribeVpcsResponse

	err = client.DoAction(&req, &resp)
	return
}
```
(https://github.com/morlay/aliyun-go/blob/master/clients/vpc/describe_vpcs.go#L11-L43)

以方便混合使用
```go
package main

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/morlay/aliyun-go/clients/ecs"
	"github.com/morlay/aliyun-go/clients/vpc"
	"fmt"
)

func main() { 
    // 创建通用 Client 实例
    client, err := sdk.NewClientWithAccessKey(
        "<your-region-id>", 			// 您的可用区ID
        "<your-access-key-id>", 		// 您的 Access Key ID
        "<your-access-key-secret>")		// 您的 Access Key Secret
    if err != nil {
    	// 异常处理
    	panic(err)
    }
    
    {
    	// 创建 ecs API 请求并设置参数
        req := ecs.DescribeInstancesRequest{
            IoOptimized: "true",
        }
        // 请求接口
        response, err := req.Invoke(client)
        if err != nil {
            panic(err)
        }
        fmt.Println(response)
    }
    
    {
       // 创建 vpc API 请求并设置参数
       req := vpc.DescribeVRoutersRequest{}
       // 请求接口
       response, err := req.Invoke(client)
       if err != nil {
           panic(err)
       }
       fmt.Println(response)
    }
}
```

另外，https://github.com/morlay/aliyun-go 已经迁移使用 官方 sdk.Client 了。
同时发现一些问题。
* Java SDK RoaRequest 会指定 POST，而 GO SDK 中没有定义，是不需要？还是别的原因（比如 cs: https://github.com/aliyun/aliyun-openapi-java-sdk/blob/master/aliyun-java-sdk-cs/src/main/java/com/aliyuncs/cs/model/v20151215/AttachInstancesRequest.java#L33, https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/cs/attach_instances.go#L74）
* Java SDK 每个 Request super 中 第四个参数，在 Go 中都没有指定，这个也是不必须的么？
![image](https://user-images.githubusercontent.com/1667873/34237248-931562d0-e636-11e7-845a-94bfafbeab63.png)

**Comment by gaort** [comment]
@morlay 
十分感谢您的反馈！
1. request.Invoke(client) 的调用风格可能不太符合面向对象的使用习惯，并且易与client.ApiFoo(request)产生混淆，我们可能暂时不会开放类似风格的接口，实在抱歉。
2. 这个的确是Go SDK生成器的一个BUG，我们会尽快fix并发布新版。
3. 这个“第四个参数”是用于EndpointResolver中LocationResolver的参数之一，虽然不是必须，但是应该不会全都没有值，我会尽快确认下，如果是bug会尽快修复。
再次感谢您的支持与反馈

**Comment by morlay** [comment]
@gaort 谢谢回复

关于 1， 如果无法提供，能否避免 request 用 CreateXXX 创建，Client Method 同样可以使用 issue 提交方式隐藏 *requests.RpcRequest 等。

**Comment by gaort** [comment]
@morlay 
内嵌*requests.RpcRequest是因为某些场景下，用户可能需要修改一些通用参数，比如Method、Scheme等。
因为使用了内嵌，如果直接使用request:=xxxRequest{} 的方式去新建对象的话，在修改Method等值时，会出现非法指针的错误，因此开放了CreateXXX 方法以供普通用户创建request，并可以在需要时修改其中的任意参数。

**Comment by morlay** [comment]
@gaort 
其实按照现在生成代码的使用，*requests.RpcRequest 的 指针 是非必须的

比如这样写也完全没有问题的
```go
type DescribeVpcsRequest struct {
        requests.RpcRequest
	ResourceOwnerId      int64  `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string `position:"Query" name:"ResourceOwnerAccount"`
}

func main() {
  req := DescribeVpcsRequest{}
  req.Method = "POST"
  req.InitWithApiInfo(....)
```

go 里的非法指针报错是在于是否能寻址，而不是 “&” 标记
上面代码中 当 DescribeVpcsRequest{} 被赋值到 req 后，requests.RpcRequest 的指针方法同样可以使用。

Inline 写法这样会报错 `(DescribeVpcsRequest{}.InitWithApiInfo(....))` 但是 这样可以`(&DescribeVpcsRequest{}).InitWithApiInfo(....)`

所以 Request 和 Response 的 base 都可以不要指针

**Comment by gaort** [comment]
@morlay 非常感谢您的分享
您说的没错，如果内嵌的是非指针类型的requests.RpcRequest，是可以直接通过{}赋值的

但是这样会带来一个问题：
当我们调用`req.BaseFoo()`时，很可能是`值传递`而非`引用传递`的场景，举例说明:

假设我们有个基础类
```go
type BaseReq  struct{
    value string
}

func (req *BaseReq)initCase1()(){
    req.value = "test1"
}

func (req BaseReq)initCase2()(){
    req.value = "test2"
}
```

如果我们将这个BaseReq，分别以指针/非指针的方式内嵌到struct A/B
```go
type A struct{
   BaseReq
}

type B struct{
   *BaseReq
}
```
实际的结果是，A仅可以组合到initCase2()方法，而B可以组合到initCase1()、initCase2()两个方法，[参考1](https://segmentfault.com/q/1010000002687684)
并且，如果我们对A类的对象 a 调用 `a.initCase2()`，实际上，a.value不会被赋值为“test2”，而是继续为空。[参考2](http://blog.csdn.net/u013790019/article/details/45397287)

简单讲，因为我们需要
1. 避免无意义的复制占用内存
1. 在各个Request/Response中，使用Base/Roa/RpcResquest三个类的`引用传递`方法
所以，我们必须内嵌一个指针型的类型。

**Comment by morlay** [comment]
@gaort 

A 和 B 都能组合到两个方法，initCase2 执行的时候都不会对覆写原值 

运行后详见日志 https://play.golang.org/p/xiLXwgzOQe1
```go
package main

import (
	"fmt"
)

type BaseReq  struct{
    Value string
}

func (req *BaseReq) Init()  {
    req.Value = "test1"
}

func (req BaseReq) SetAndClone() *BaseReq {
    req.Value = "test2"
    return &req
}

type A struct{
   BaseReq
}

type B struct{
   *BaseReq
}


func main() {
	a := A{}
	a.Init() 
	fmt.Println("a.Value", a.Value)
	fmt.Println("========")
	a2 := a.SetAndClone() 
	fmt.Println("a.Value", a.Value)	
	fmt.Println("a2.Value", a2.Value)	
	fmt.Println("========")
	a2.Value = "1"
	fmt.Println("a.Value", a.Value)
	fmt.Println("a2.Value", a2.Value)
	fmt.Println("========")
	
	b := B{
	  BaseReq: &BaseReq{},
	}
	b.Init() 
	fmt.Println("b.Value", b.Value)
	fmt.Println("========")
	b2 := b.SetAndClone() 
	fmt.Println("b.Value", b.Value)	
	fmt.Println("b2.Value", b2.Value)
	fmt.Println("========")
	b2.Value = "1"
	fmt.Println("b.Value", b.Value)
	fmt.Println("b2.Value", b2.Value)
}
```
![image](https://user-images.githubusercontent.com/1667873/34245225-ee6d345a-e663-11e7-9e3c-77ad78c6f06d.png)

* 非指针 receiver 的方法，很多时候需要有返回值，这里确实会复制。
* 指针 receiver 的方法， 如你所说，有内存开销的考量（https://tour.golang.org/methods/8），但 A 组合 BaseReq 后，使用 Init 同样是指针 receiver 的方法，BaseReq 同 A 一同实例化，并无复制一说（和当前代码中调用方法无区别）

**Comment by gaort** [comment]
@morlay 多谢您的反馈&分享
受教，看来是我被[参考1](https://segmentfault.com/q/1010000002687684)误导了
我们会尽快修改下sdk中的相关代码，以支持 `req:=XXXRequest{}`的创建方式
出于兼容性的考虑，CreateXXXRequest的方法会保留
再次感谢您的反馈，与您交流真的很愉快

**Comment by morlay** [comment]
@gaort

要不还是给加个 Invoke 方法嘛 😈 
和你讨论后，我把提案也简化了下，可以这样：
```go
func (c *VpcClient) DescribeVpcs(req *DescribeVpcsRequest) (resp *DescribeVpcsResponse, err error) {
   return req.Invoke(&c.Client)
}

func (req *DescribeVpcsRequest) Invoke(client *sdk.Client) (resp *DescribeVpcsResponse, err error) {
	req.InitWithApiInfo("Vpc", "2016-04-28", "DescribeVpcs", "vpc", "")
	resp = &DescribeVpcsResponse{}
	err = client.DoAction(req, resp)
	return
}
```
https://github.com/morlay/aliyun-go/blob/master/clients/vpc/describe_vpcs.go

**Comment by gaort** [comment]
@morlay 
实在抱歉，添加一个新的入口，很有可能会对其他用户造成困扰，我们应尽量保证sdk的简洁、简单
不知您是有什么样的需求，需要这样的入口来支持呢？

**Comment by morlay** [comment]
@gaort

算是一种风格吧，阿里云子产品众多，这种写法可以避免给每一个子产品预设 Client。
这个也还好了，Request 类型的问题更急迫点，https://github.com/aliyun/alibaba-cloud-sdk-go/pull/6

**Comment by gaort** [comment]
@morlay 
同时使用多个产品的情况下，使用commonApi也是一种可以考虑的方式，能够做到一个client发送任意请求

**Comment by gaort** [comment]
@morlay 
您提到的两个问题，已经在0.7.8中修复 :D
