### ISSUE TITLE
求不要更新了，老子更不动了

### ISSUE THREAD

**Issue by axetroy** [aliyun/alibaba-cloud-sdk-go#401]
看看发行版本

快一点的 1-2 小时发布一个新版本，一天 5-6 个版本是常事

难道就没有一个发布周期计划表吗？

我的 Github Bot 每天提醒我更新 sdk 的版本，一天几次，很烦

并且这个发布计划就不合理，是什么样的 BUG 需要紧急修复，连续发两个版本的？

还是说为了做项目总结

> 这个季度，我们的 SDK 发布了 500 多个版本 balabala...

**Comment by boshueryi** [comment]
给你点个赞

**Comment by boshueryi** [comment]
老铁不容易啊

**Comment by wenzuochao** [comment]
我们现在发布版本是跟产品的更新有关的，有产品更新api的时候，就会自动发布一个版本，是为了让用户能更快的用上最新版本的 api。

**Comment by AxiosCros** [comment]
因为所有的产品 sdk 都在这一个库中，所以任何一个产品 sdk 的发布，都会使这个项目的版本号增加。

**Comment by wenzuochao** [comment]
如果您没有其他问题的话，我这边先关闭 issue，后续您还有其他的问题，欢迎重新打开 issue 或者开一个新的 issue。

**Comment by greenhat616** [comment]
@wenzuochao 
![image](https://user-images.githubusercontent.com/41122242/92497462-f53aac00-f22b-11ea-9f79-517e7eff45c7.png)
兄弟，发布计划赶紧上吧。随手找了个昨天的发布版本历史，一个特性光截图区就重复了 3 次。相比功能未完成发布我觉得应该是存在 bug 吧.... 妥善测试后的发布比快速迭代对客户更好。试想一下：快速迭代中恰好客户更新模块到了存在特定版本问题的模块（之前没有这个问题，下个版本也修复了），并且发布线上。这种灾难性后果是难以承担的。

![image](https://user-images.githubusercontent.com/41122242/92497822-67ab8c00-f22c-11ea-9809-185bb030455d.png)
P.S 本以为过几个月后会趋于稳定，但是现在已经 4 年（2017第一次 commit）了，还是月更 100 小版本。

**Comment by wenzuochao** [comment]
我们现在发布版本是跟产品的更新有关的，有产品更新api的时候，就会自动发布一个版本，是为了让用户能更快的用上最新版本的 api。为所有的产品 sdk 都在这一个库中，所以任何一个产品 sdk 的发布，都会使这个项目的版本号增加。这个问题我们会在最新版本的[sdk](https://github.com/aliyun/alibabacloud-sdk)中解决，不过新版本sdk跟旧版本是不兼容的
