### ISSUE TITLE
struct missing fields

### ISSUE THREAD

**Issue by afghanistanyn** [aliyun/alibaba-cloud-sdk-go#403]
according to the doc , the struct SQLSlowRecord   in services/rds/struct_sql_slow_record.go is missing field QueryTimeMS

ref: https://help.aliyun.com/document_detail/26289.html

**Comment by wenzuochao** [comment]
I'm sorry for that. you can use [the  latest version](https://github.com/aliyun/alibaba-cloud-sdk-go/releases/tag/v1.61.70).
