### ISSUE TITLE
The specified parameter "SystemDisk.Size" is not valid

### ISSUE THREAD

**Issue by soWill666** [aliyun/alibaba-cloud-sdk-go#405]
SDK.ServerError
ErrorCode: InvalidParameter
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidParameter&source=PopGw
RequestId: ********
Message: The specified parameter "SystemDisk.Size" is not valid.

**Comment by soWill666** [comment]
go version go1.13 darwin/amd64
alibaba-cloud-sdk-go@v1.61.78

**Comment by wenzuochao** [comment]
麻烦提供一下产品id

**Comment by soWill666** [comment]
ecs.CreateCreateInstanceRequest

**Comment by wenzuochao** [comment]
请问您传的SystemDisk.Size 是多大呢，这个参数取值范围是20～500

**Comment by soWill666** [comment]
你好 检查了一下 是参数值不对  打扰了
