### ISSUE TITLE
dts DescribeSynchronizationJobs SDK.JsonUnmarshalError

### ISSUE THREAD

**Issue by SecretSun** [aliyun/alibaba-cloud-sdk-go#407]
Get DTS response error:  [SDK.JsonUnmarshalError] Failed to unmarshal response, but you can get the data via response.GetHttpStatusCode() and response.GetHttpContentString()
caused by:
dts.DescribeSynchronizationJobsResponse.SynchronizationInstances: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|stances":[{"Status":|..., bigger context ...|TotalRecordCount":102,"SynchronizationInstances":[{"Status":"Initializing","SynchronizationObjects":|...

github.com/aliyun/alibaba-cloud-sdk-go v1.61.78

**Comment by wenzuochao** [comment]
It's my fault. I have releaseed a new version v1.61.79. Please pull the latest codes and try again.
