### ISSUE TITLE
return nil using RamRoleArnSigner.GetSessionCredential

### ISSUE THREAD

**Issue by fanyinghao** [aliyun/alibaba-cloud-sdk-go#409]
after call with `client, err := sdk.NewClientWithRamRoleArnAndPolicy(...)` , I want to get sessionCredential from the client, so I use `RamRoleArnSigner.GetSessionCredential` but got nil. 

I look at source code and found it does not init the `sessionCredential` with `signer.updateCredential()`.

I could call `signer.GetExtraParam()` first but I don't think it's a good idea.

**Comment by wenzuochao** [comment]
When you create a client,  the sessionCredential is nil. When you call api with the client, sdk will call  `signer.updateCredential()`  automatically， then the sessionCredential will be filled. If you just want to get sessionCredential, you can [AssumeRole](https://help.aliyun.com/document_detail/28763.html?spm=a2c4g.11174283.6.800.6cd3566260GubH)
