### ISSUE TITLE
Unauthorized when using describePrice

### ISSUE THREAD

**Issue by kapilatrey95** [aliyun/alibaba-cloud-sdk-go#416]
{
	"RequestId": "A1D4442D-BA0D-44FB-A002-33A156B105BC",
	"HostId": "ecs.aliyuncs.com",
	"Code": "InvalidAction.Unauthorized",
	"Message": "The specified action is not valid."
}

**Comment by wenzuochao** [comment]
Does your accesskey have access to call ecs apis?

**Comment by JacksonTian** [comment]
这个接口可能需要特殊授权。请你提工单咨询一下。

**Comment by kapilatrey95** [comment]
I couldn't find a way to do so, could you point me in the right direction?

**Comment by wenzuochao** [comment]
You can look at the [document](https://www.alibabacloud.com/help/doc-detail/62184.htm?spm=a2c63.p38356.879954.8.22a761d1swJE8C#concept-vdd-rmk-xdb), it may help you.

**Comment by kapilatrey95** [comment]
Thanks, I didn't provide my user access to AliyunECSFullAccess, closing this issue :-)
