### ISSUE TITLE
The specified parameter "InstanceIds" is not valid.

### ISSUE THREAD

**Issue by NigelZHANG** [aliyun/alibaba-cloud-sdk-go#419]
在调用这个包创建CreateDescribeInstancesRequest的时候：
"github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"
里面有个参数InstanceIds，定义的是string类型，执行时却报了下面的错误：
`ErrorCode: InvalidParameter  
        Recommend: 
        RequestId: CEF6FC59-4014-4345-A472-3DFF7F9987F7
        Message: The specified parameter "InstanceIds" is not valid.
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0`
你们有具体的示例要什么格式的字符串吗，你们应该在后台分割了字符串

**Comment by wenzuochao** [comment]
你可以看一下这个api文档：https://help.aliyun.com/document_detail/25506.html?spm=a2c4g.11174283.6.1228.6b8d52fe5jdRaf
