### ISSUE TITLE
Alibaba Cloud SDK Code Generator

### ISSUE THREAD

**Issue by alteholz** [aliyun/alibaba-cloud-sdk-go#420]
Lots of files contain comments like "Code generated by Alibaba Cloud SDK Code Generator."

Unfortunately I did not find any documentation on how to use that generator.
Can you please add some documentation on how to obtain it, use it and how to get the original stuff that the generator uses to create all those file.

**Comment by wenzuochao** [comment]
The generator uses inner apis to generate product codes. That means it's useless for you. If you need latest product codes, you can open an issue and put forward the demand.

**Comment by alteholz** [comment]
I am trying to package terraform[1] for Debian. In order to support the Alibaba Cloud, one dependency of terraform is golang-github-aliyun-alibaba-cloud-sdk-go-dev, which I already prepared[2]. Unfortunately this package is not yet accepted, because it contains generated files, which are not in the "preferred form for modification". Due to Debian's policy to only allow open source software that can be built completely from real sources, there are only two options: either you also publish the generator and the inner APIs under an open source license so that everybody can build/modify the SDK on their own; or the Debian version of terraform won't have support for the Alibaba Cloud.

Given your comment, I am afraid the latter is the only option i really have :-(

[1] https://github.com/hashicorp/terraform
[2]https://ftp-master.debian.org/new/golang-github-aliyun-alibaba-cloud-sdk-go_1.61.18-1.html

**Comment by wenzuochao** [comment]
AlibabaCloud has [terraform](https://github.com/terraform-providers/terraform-provider-alicloud), it may help you.

**Comment by 18767156402** [comment]
go: github.com/aliyun/alibaba-cloud-sdk-go@v1.61.226: Get https://proxy.golang.org/github.com/aliyun/alibaba-cloud-sdk-go/@v/v1.61.226.mod: dial tcp 34.64.4.17:443: conn
ect: connection refused

这个是找七牛还是阿里云呀

**Comment by alteholz** [comment]
Yes, but according to their mod.go a dependency of that terraform-provider is again github.com/aliyun/alibaba-cloud-sdk-go, which I cannot use, because not all sources are available.

**Comment by wenzuochao** [comment]
> Yes, but according to their mod.go a dependency of that terraform-provider is again github.com/aliyun/alibaba-cloud-sdk-go, which I cannot use, because not all sources are available.

If the product SDK you need is not in the library, you can ask us for it, and we will generate the corresponding SDK for you.

**Comment by wenzuochao** [comment]
Do you have any other questions？ If not， I will close in three days.
