### ISSUE TITLE
单元测试时对sdk的请求进行mock处理

### ISSUE THREAD

**Issue by zjkyz8** [aliyun/alibaba-cloud-sdk-go#421]
系统中引入了该sdk，在进行单元测试时，需要将对外的请求进行mock处理，请帮忙确认能否通过jarcoal/httpmock 进行mock处理

**Comment by wenzuochao** [comment]
只要能mock一个server，然后把mock的url作为endpoint，就能实现mock请求 https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/integration/api_test.go#L208

**Comment by zjkyz8** [comment]
endpoint只能在request上被替换掉吗？是否有func直接替换或者通过配置全局替换呢，示例中是每个request替换的

**Comment by wenzuochao** [comment]
import (
   "github.com/aliyun/alibaba-cloud-sdk-go/sdk/endpoints"
)

endpoints.AddEndpointMapping("REGION_ID", "PRODUCT_ID", "ENDPOINT")

**Comment by wenzuochao** [comment]
如果你使用同一个region。同一个产品，那么就会访问同一个endpoint

**Comment by wenzuochao** [comment]
请问您的问题解决了吗？没问题的话，麻烦关一下 issue

**Comment by zjkyz8** [comment]
部分解决了吧，mockserver是可以，但是准备数据非常费劲，基本上是从头写起，是否可以考虑暴露底层的http.Client 而非endpoint ,这样可以利用成熟的httpmock 框架

**Comment by wenzuochao** [comment]
> 部分解决了吧，mockserver是可以，但是准备数据非常费劲，基本上是从头写起，是否可以考虑暴露底层的http.Client 而非endpoint ,这样可以利用成熟的httpmock 框架

这个我们这边没有相关的安排，目前只能 mockserver
