### ISSUE TITLE
能否提供一个 green 包下 TextScan 的使用示例

### ISSUE THREAD

**Issue by smartwalle** [aliyun/alibaba-cloud-sdk-go#431]
如题，谢谢

**Comment by wenzuochao** [comment]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/docs/11-Endpoint-CN.md#endpoint 你可以看一下这个示例，先创建client，然后封装 request，发送请求

**Comment by smartwalle** [comment]
```
var aliCloudGreenClient, _ = green.NewClientWithAccessKey(aliCloudRegionId, aliCloudAccessKeyId, aliCloudAccessKeySecret)
var req = green.CreateTextScanRequest()
 // 如何设置参数？？
aliCloudGreenClient.TextScan(req)
```

**Comment by wenzuochao** [comment]
req.ClientInfo = "client info" 这样就能给参数赋值了

**Comment by smartwalle** [comment]
是把 https://help.aliyun.com/document_detail/70439.html?spm=a2c4g.11186623.6.666.2d3d7544SjRmLI 中的请求参数序列化成 JSON 字符串赋值给 req.ClientInfo 吗？

**Comment by wenzuochao** [comment]
你可以提工单给 green 的产品咨询一下，具体 api 调用我这边也不清楚，我看了文档，跟 sdk 里的定义有差距。

**Comment by smartwalle** [comment]
麻烦你内部沟通一下，让作者来解释一下吧，这个东西真看不懂怎么使用。

**Comment by smartwalle** [comment]
@jxyowen @Qingtang-SDK

**Comment by JacksonTian** [comment]
@smartwalle 参考下 https://api.aliyun.com/#/?product=Green&version=2018-05-09&api=TextScan&params={}&tab=DEMO&lang=GO

**Comment by smartwalle** [comment]
@JacksonTian 多谢
