### ISSUE TITLE
slb的sdk不感知服务端返回的error code和error message？

### ISSUE THREAD

**Issue by wZH-CN** [aliyun/alibaba-cloud-sdk-go#434]
* **产品和接口**:
调用slb的DeleteLoadBalancer方法：https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/slb/delete_load_balancer.go#L89
这里的response似乎并不感知返回的error code和error message？
我需要读取这样的error code:
![image](https://user-images.githubusercontent.com/58815225/86991727-5fa28200-c1d2-11ea-9ecb-b1b61116d624.png)
然而这是sdk里的response 结构体：
![image](https://user-images.githubusercontent.com/58815225/86991740-6b8e4400-c1d2-11ea-99c3-530b4cf22442.png)
Code，Message等字段在这里是缺失的啊？
* **平台**:
go version: go1.13.9 linux/amd64
sdk version in go.mod:  github.com/aliyun/alibaba-cloud-sdk-go v1.61.235
* **最小代码**:

**Comment by wenzuochao** [comment]
错误返回的信息在 err 里，你可以通过err.Error() 获取到这些信息

**Comment by wZH-CN** [comment]
> 错误返回的信息在 err 里，你可以通过err.Error() 获取到这些信息
err里面是上图中Code的字符串还是Message的字符串？

**Comment by wenzuochao** [comment]
都有的，你可以打印一个看一下

**Comment by wZH-CN** [comment]
> 都有的，你可以打印一个看一下

把错误信息放到error里面是哪块代码的逻辑？我想看下代码

**Comment by wenzuochao** [comment]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/errors/server_error.go#L47

**Comment by wZH-CN** [comment]
> https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/errors/server_error.go#L47

太好了，非常感谢！
