### ISSUE TITLE
[suggest] SDK client support sending request with context.

### ISSUE THREAD

**Issue by pkgplus** [aliyun/alibaba-cloud-sdk-go#435]
* **Product and API**: SDK client
* **Platform**: linux
* **How to Reproduce**: anytime

The `DoAction` method of  sdk `Client` can't support calling with context, can I add `SetContext(ctx context.Context)` and `GetContext() context.Context` methods to `AcsRequest` interface?

**Comment by wenzuochao** [comment]
The sdk won‘t add new feature. You can focus on our new sdk. It may support context in the future. https://github.com/aliyun/alibabacloud-sdk

**Comment by pkgplus** [comment]
> The sdk won‘t add new feature. You can focus on our new sdk. It may support context in the future. https://github.com/aliyun/alibabacloud-sdk

Alright. My understanding is that the repo name is not stable?  the repo name is suffix with date? When will plan to release the new sdk client with context?

**Comment by wenzuochao** [comment]
There is no plan to support context， but if we're going to support context, it must be in the new repo.
