### ISSUE TITLE
Missing region (cn-wulanchabu) from ECS endpoint map

### ISSUE THREAD

**Issue by sagikazarmark** [aliyun/alibaba-cloud-sdk-go#440]
* **Product and API**: ECS (SDK version: v1.60.267, but the latest is also affected)
* **Platform**:
* **How to Reproduce** Call the `DescribeZones` action for `cn-wulanchabu` region

When trying to call the DescribeZones action for the cn-wulanchabu region, the request fails with the following error:

```
DescribeZones API call problem: SDK.ServerError\nErrorCode: InvalidOperation.NotSupportedEndpoint\nRecommend: \nRequestId: 743DE90F-B77C-48F0-9382-D684FE3072D3\nMessage: The specified endpoint can't operate this region. Please use API DescribeRegions to get the appropriate endpoint, or upgrade your SDK to latest version.
```

As far as I can tell, ECS is available in this region, but on a different endpoint, therefore not listing it in the SDK causes the API requests to fail.

**Comment by wenzuochao** [comment]
You can pull the latest codes and try again. The latest release is 1.61.380.

**Comment by sagikazarmark** [comment]
As I pointed out, the latest version is also affected: https://github.com/aliyun/alibaba-cloud-sdk-go/blob/v1.61.380/services/ecs/endpoint.go

**Comment by wenzuochao** [comment]
Have you set the domain by yourself? You can only set the regionid, the sdk can set the endpoint for you.

**Comment by sagikazarmark** [comment]
Yeah, I do set the domain.

Tried leaving it empty, got the following error:

```
 DescribeZones API call problem: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"","RegionId":"eu-central-1","LocationProduct":"","LocationEndpointType":""}), please check your accessKey with secret, and read the user guide
```

Following this example: https://github.com/aliyun/alibaba-cloud-sdk-go#roa-request

Although I wonder how the SDK sets the endpoint, if it doesn't have the region in the endpoint list. `ecs.aliyuncs.com` (which I guess is the default) doesn't work with this region.

**Comment by wenzuochao** [comment]
> Yeah, I do set the domain.
> 
> Tried leaving it empty, got the following error:
> 
> ```
>  DescribeZones API call problem: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"","RegionId":"eu-central-1","LocationProduct":"","LocationEndpointType":""}), please check your accessKey with secret, and read the user guide
> ```
> 
> Following this example: https://github.com/aliyun/alibaba-cloud-sdk-go#roa-request
> 
> Although I wonder how the SDK sets the endpoint, if it doesn't have the region in the endpoint list. `ecs.aliyuncs.com` (which I guess is the default) doesn't work with this region.

Do you use the latest codes? It may not appear in the latest codes.

**Comment by sagikazarmark** [comment]
What do you mean by latest codes? I've just upgraded to 1.61.380.

**Comment by wenzuochao** [comment]
You can set the environment variable `DEBUG=sdk`， and try again. You can see the process of request. I have called the ecs api and got the response successfully.
```sh
> Host: ecs.cn-wulanchabu.aliyuncs.com
> x-sdk-client: golang/1.0.0
> x-sdk-invoke-type: normal
> Accept-Encoding: identity
> x-sdk-core-version: 0.0.1
> Content-Type: application/x-www-form-urlencoded
> User-Agent: AlibabaCloud (darwin; amd64) Golang/1.14.3 Core/0.0.1
>
 Retry Times: 0.
< HTTP/1.1 200 OK
< Date: Thu, 06 Aug 2020 01:18:19 GMT
< Content-Type: application/json;charset=utf-8
< Connection: keep-alive
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, GET, OPTIONS
< Access-Control-Allow-Headers: X-Requested-With, X-Sequence, _aop_secret, _aop_signature
< Content-Length: 2357
< Access-Control-Max-Age: 172800
```

**Comment by sagikazarmark** [comment]
Can you give me a code sample with the SDK for the DescribeZones call in that region? I can't seem to make it work.

**Comment by wenzuochao** [comment]
```go
client, err := ecs.NewClientWithAccessKey("cn-wulanchabu", os.Getenv("ACCESS_KEY_ID"), os.Getenv("ACCESS_KEY_SECRET"))
	request := ecs.CreateDescribeZonesRequest()
	response, err := client.DescribeZones(request)
```

```sh
> Host: ecs.cn-wulanchabu.aliyuncs.com
> Content-Type: application/x-www-form-urlencoded
> x-sdk-client: golang/1.0.0
> User-Agent: AlibabaCloud (darwin; amd64) Golang/1.14.3 Core/0.0.1
> x-sdk-invoke-type: normal
> Accept-Encoding: identity
> x-sdk-core-version: 0.0.1
>
 Retry Times: 0.
< HTTP/1.1 200 OK
< Content-Length: 6143
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, GET, OPTIONS
< Access-Control-Allow-Headers: X-Requested-With, X-Sequence, _aop_secret, _aop_signature
< Date: Thu, 06 Aug 2020 07:02:47 GMT
< Content-Type: application/json;charset=utf-8
< Connection: keep-alive
< Vary: Accept-Encoding
< Access-Control-Max-Age: 172800
```

**Comment by wenzuochao** [comment]
Does it work for you?

**Comment by sagikazarmark** [comment]
Yes, it does seem to be working.

I think I found the reason why it didn't work for me:

I used the SDK client and constructed requests manually:

```go
	request := requests.NewCommonRequest()
	request.Method = "POST"
	request.ApiName = "DescribeZones"
	request.Domain = "ecs.aliyuncs.com"
	request.Version = "2014-05-26"
	request.QueryParams["RegionId"] = region
```

**Comment by wenzuochao** [comment]
Ok, Thanks for your support to our sdk!
