### ISSUE TITLE
us-east-1 区域的 polardb endpoint 配置有问题

### ISSUE THREAD

**Issue by theharveyz** [aliyun/alibaba-cloud-sdk-go#441]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/29f7c141f3d78d371d6f2eb4ec4b53d161e57f37/services/polardb/endpoint.go#L23

这个配置是同步不下来，us-east-1 区域的 polardb 的资源的。

**Comment by wenzuochao** [comment]
您使用这个endpoint访问不了吗？

**Comment by theharveyz** [comment]
> 您使用这个endpoint访问不了吗？

是的，us-east-1 的 polardb 资源获取不了。

**Comment by wenzuochao** [comment]
这个你可以给产品提工单

**Comment by theharveyz** [comment]
> 这个你可以给产品提工单

这个 endpoint 地址是预期就是如此的吗？ 为何 us-east-1 的地址配置是 ap-northeast-1 的？出于什么考虑？

**Comment by wenzuochao** [comment]
这个地址是产品方配置的，由生成到 sdk 里给用户使用。

**Comment by wenzuochao** [comment]
还有其他问题吗？没问题的话，我将关闭这个这个issue
