### ISSUE TITLE
MQTT调用接口报错

### ISSUE THREAD

**Issue by codinl** [aliyun/alibaba-cloud-sdk-go#443]
调用MQTT接口报错。

调用代码：
```
client, err := onsmqtt.NewClientWithAccessKey("eu-central-1", "****", "****")
if err != nil {
        panic(err)
	return
}

rsp, err := client.ApplyToken(onsmqtt.CreateApplyTokenRequest())
if err != nil {
        panic(err)   // 这里报错
        return
}
```

报错：

```
panic: SDK.ServerError
ErrorCode: MissingResources
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingResources&source=PopGw
RequestId: 0FD4CDB2-0C9F-4BE4-91CA-2A9A79903B37
Message: Resources is mandatory for this action. [recovered]
	panic: SDK.ServerError
ErrorCode: MissingResources
Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingResources&source=PopGw
RequestId: 0FD4CDB2-0C9F-4BE4-91CA-2A9A79903B37
Message: Resources is mandatory for this action.
```

已开通mqtt服务。
账号已经授权，AccessKeyId和AccessKeySecret没错。

@wenzuochao

**Comment by codinl** [comment]
账号已经授权

**Comment by wenzuochao** [comment]
https://help.aliyun.com/document_detail/175722.html?spm=a2c4g.11186623.6.677.5aceae8aaPPLN2 你可以看一下这个文档， Resources 是这个api的必填参数

**Comment by codinl** [comment]
建议在代码里面写demo或test，不然很容易找不到错误在哪（不知道是代码写错了，还是服务有问题，还是其他问题）。

**Comment by codinl** [comment]
我不知道有没人用go客户端跑起来整个流程(从调用sdk，到监听topic，到收发消息)，我这边跑不起来。
1. sdk令人费解，主要靠蒙。
2. 手动要后台设置topic，不知道什么鬼。不知道要搞个这玩意干什么？mqtt的topic如果动态变怎么办？
3. 服务1883测试是通的，然而用go去监听topic，没任何反应。用的这个包，github.com/eclipse/paho.mqtt.golang。同样的代码，监听自己搭的mqtt服务是可以的。

总结来说，难用，甚至我在猜测能不能用。

**Comment by wenzuochao** [comment]
sdk的调用，还是要参考产品文档的，根据文档的参数来填写，有问题的话，可以提issue咨询

**Comment by wenzuochao** [comment]
我这边先关闭 issue，如果您还有问题，可以重新打开这个 issue 或者另起一个新的 issue
