### ISSUE TITLE
阿里巴巴写的sdk，文档都没吗

### ISSUE THREAD

**Issue by codinl** [aliyun/alibaba-cloud-sdk-go#444]
阿里巴巴写的sdk，文档都没吗？至少一个示例总有吧？
我说的是mqtt go。

**Comment by codinl** [comment]
一线大厂，怎么跟个小作坊一样。

**Comment by codinl** [comment]
go的文档或demo有吗？mqtt调不通啊。

**Comment by wenzuochao** [comment]
我这边先关闭 issue，如果您还有问题，可以重新打开这个 issue 或者另起一个新的 issue
