### ISSUE TITLE
请问是否可以提供mns和oss的封装？

### ISSUE THREAD

**Issue by pwtitle** [aliyun/alibaba-cloud-sdk-go#446]
* **oss/mns**:
* **golang**:
* **最小代码**:

**Comment by wenzuochao** [comment]
oss的您可以看一下 https://github.com/aliyun/alibabacloud-oss-sdk/tree/master/golang
mns的您可以看一下https://github.com/aliyun/aliyun-mns-go-sdk?spm=a2c4g.11186623.2.12.762e2c6ctmcVZQ

**Comment by wenzuochao** [comment]
我这边先关闭 issue，您如果有使用的问题，可以在对应的仓库提issue
