### ISSUE TITLE
 EipAddress.EipAddresses.EipAddress.HasReservationData cannot unmarshal

### ISSUE THREAD

**Issue by angelznq** [aliyun/alibaba-cloud-sdk-go#447]
json: cannot unmarshal bool into Go struct field EipAddress.EipAddresses.EipAddress.HasReservationData of type string

* **Product and API**:
Product: VPC API: DescribeEipAddresses
* **Platform**:
Platform independent
* **How to Reproduce**
Use common request to test this API and unmarshal to &vpc.DescribeEipAddressesResponse{} will throw this exception.

**Comment by wenzuochao** [comment]
您的问题我们了解了，尽快为您解决

**Comment by wenzuochao** [comment]
You can pull the latest codes and try again!

**Comment by angelznq** [comment]
@wenzuochao 最新的代码也报错，我用的是commonrequest。

**Comment by angelznq** [comment]
可以了，谢谢。

**Comment by wenzuochao** [comment]
好的，那我这边关闭issue，有其他问题的话，你可以再开一个 issue，感谢您的支持
