### ISSUE TITLE
CommonRequest返回json对象unmarshal报错

### ISSUE THREAD

**Issue by angelznq** [aliyun/alibaba-cloud-sdk-go#449]
* **产品和接口**:
"R-kvstore", "r-kvstore.aliyuncs.com", "2015-01-01", "DescribeInstances"
* **平台**:
所有平台
* **错误信息**:
json: cannot unmarshal bool into Go struct field KVStoreInstance.Instances.KVStoreInstance.HasRenewChangeOrder of type string

**Comment by wenzuochao** [comment]
我们这边尽快为您处理一下

**Comment by wenzuochao** [comment]
已经处好了，您可以拉取一下最新的 sdk。
