### ISSUE TITLE
QueryMetricList Dimension Filtering not working

### ISSUE THREAD

**Issue by hasancana** [aliyun/alibaba-cloud-sdk-go#45]
Trying to filter metric datapoints based on Dimension is not working. Even though metrics with dimension key "instanceId" and value "somevalue" do not exists, the API call still returns datapoints of all metrics whatever their instanceId is.
```go
request := cms.CreateQueryMetricListRequest()
request.StartTime = time.Now().UTC().Add(-5 * time.Minute).Format(time.RFC3339)
request.EndTime = time.Now().UTC().Format(time.RFC3339)
request.Period = "60"
request.Dimensions = "{\"instanceId\":\"somevalue\"}"
request.Project = "custom_project_name"
request.Metric = "cpu_usage"
request.Method = "GET"
response, err := client.QueryMetricList(request)
````

**Comment by gaort** [comment]
@hasancana 
Thanks for your feedback!
Could you please provide a specific requestId for us to view the detailed log?

**Comment by hasancana** [comment]
@gaort 

`"RequestId":"A1B7D01D-F8F9-47C5-80D2-2F472C043EBF"`

**Comment by xiaozhen57520** [comment]
The error is due to the mismatch between the reported data and the query conditions, and the cloud monitoring will ignore the mismatched query conditions.

The data you have reported:

dimension:instanceId=xxxxxx
groupId:123456
name:cpu_mhz
value:1


It should be reported in this way：

instanceId:xxxxxx
groupId:123456
name:cpu_mhz
value:1

**Comment by hasancana** [comment]
@xiaozhen57520 I tried to report the data as you proposed, 

`{
				"groupId":102,
				"metricName":"cpu_mhz",
				"type":0,
				"instanceId":"%v",
				"values":{"value":%v}
			}`

still I cannot filter based on dimension, although now dimensions is empty.

"RequestId":"6318F694-48F4-4345-85D8-4AB286F01964"

**Comment by hasancana** [comment]
@xiaozhen57520 

This is how I am reporting metric data (new way, based on your suggestion):

`
request := cms.CreatePutCustomMetricRequest()
request.Method = "GET"
request.MetricList = "[{
				"groupId":102,
				"metricName":"cpu_mhz",
				"type":0,
				"instanceId":"xxxxxxxxxx",
				"values":{"value":10.5}
			}]"

response, err := client.PutCustomMetric(request)
`

and then query it as follows:

`
request := cms.CreateQueryMetricListRequest()
	request.StartTime = time.Now().UTC().Add(-2 * time.Minute).Format(time.RFC3339)
	request.EndTime = time.Now().UTC().Format(time.RFC3339)
	request.Period = "60"
	request.Project = "acs_customMetric_xxxxxxxxxxxxxxxx"
	request.Metric = "cpu_mhz"
	request.Dimensions = "{\"instanceId\":\"somevalue\"}"
	request.Method = "GET"
	response, err := client.QueryMetricList(request)
`

and trying to query based on some non-existing instance id, instead of returning empty Datapoint array, it returns whatever finds (i.e doest not take into account the instanceId given as part of Dimension property'. It should return data only if I specify the instanceId as "xxxxxxxxxx", otherwise empty datapoint should be returned

**Comment by xiaozhen57520** [comment]
@hasancana 

I'm very sorry, the previous answer was wrong. I wrote an example of custom metrics in JAVA, which can be referred to. repository: https://github.com/xiaozhen57520/cmsExample

**Comment by hasancana** [comment]
@xiaozhen57520 @gaort I followed the java example on Go and it's working. Thanks.

For other users who might have the same issue, here is what the request's Dimension property looks like on Go:

> request.Dimensions = `{"groupId":"102","dimension":"instanceId=xxxxxxx"}`
