### ISSUE TITLE
The path and file format of default credentials file is not consistent with that in aliyun CLI

### ISSUE THREAD

**Issue by lshmouse** [aliyun/alibaba-cloud-sdk-go#451]
* **产品和接口**:
The path of default credentials file is ~/.alibabacloud/credentials and the credentials file  is property file
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/docs/2-Client-EN.md#2-credentials-file

But The path of default credentials of aliyun CLI is ~/.aliyun/config.json, the file format is json

* **平台**:
Ubuntu

* **最小代码**:

https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/auth/credentials/provider/profile_credentials.go#L40

```
$aliyun configure
$ ls ~/.aliyun/config.json
```

**Comment by wenzuochao** [comment]
If you use cli， you  just use `~/.aliyun/config.json`. `~/.alibabacloud/credentials` is useless for cli.

**Comment by lshmouse** [comment]
In my opinion, aliyun go sdk and cli should use the same credential path and format. Different path and format of default credential
path in two products is confused for the developers. Is there any standard for the credential path and format? We can change the code and keep consistent for the config.

**Comment by wenzuochao** [comment]
If you use the cli, it's not necessary for you to focus on how the sdk work.

**Comment by wenzuochao** [comment]
If you have no other questions, I will close the issue in three days. Thanks for your support to the sdk.
