### ISSUE TITLE
support dry-run

### ISSUE THREAD

**Issue by frbimo** [aliyun/alibaba-cloud-sdk-go#466]
Is this support dry-run? it is wasting resource if i need to test deployment response by actually using my resource on aliyun.
If it is related to https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/docs/6-Debug-EN.md , please emphasis the document so we will know what it is doing when we set `DEBUG=sdk `

**Comment by wenzuochao** [comment]
It doesn't support dry-run. When you set `DEBUG=sdk`, the sdk just print the process of the request, such as request headers, url and response headers.

**Comment by frbimo** [comment]
@wenzuochao  any way to let me know how to validate the request in advance?

**Comment by wenzuochao** [comment]
You can use the [new version SDK](https://github.com/aliyun/alibabacloud-sdk). New SDK will validate the request params whether required.

**Comment by JacksonTian** [comment]
@frbimo some products' OpenAPI not support dry-run. In Alibaba Cloud, just a little products support dry-run.

**Comment by frbimo** [comment]
@wenzuochao i see, thanks for the reply eventhough i preferr rpc than call sdk api.
@JacksonTian just my 2cent but from dev perspective, kinda hard to test request rather than send a real request. Anyway thanks for the info.

Closing this issue
