### ISSUE TITLE
go build编译后的文件在没有go环境的环境执行报错

### ISSUE THREAD

**Issue by xiaoxin01** [aliyun/alibaba-cloud-sdk-go#47]
环境：ubuntu 14.04
直接在装有go环境的环境执行go build产生的文件，可以正常运行，将文件cp到没有go环境的ubuntu 14.04下执行报错：（调用的方法为：RefreshObjectCaches）

```
panic: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Cdn","RegionId":"cn-hangzhou","LocationProduct":"","LocationEndpointType":""}), please check the user guide
```

请问该如何解决，谢谢！

**Comment by gaort** [comment]
@xiaoxin01 
感谢反馈
这种情况下，您可以进行以下尝试：
1. 更新到最新版
2. 如果问题没有解决，建议您手动配置endpoint，可以参考文档"常见问题"https://help.aliyun.com/document_detail/66230.html

**Comment by xiaoxin01** [comment]
@gaort
目前使用 glide 获取sdk版本是1.0.1
手动设定 request.Domain 的地址(actiontrail.cn-hangzhou.aliyuncs.com)之后，报另外一个错误：

```
panic: SDK.ServerError
ErrorCode: InvalidVersion
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidVersion&source=PopGw
RequestId: E0E42498-25DB-407F-99D6-BFE005D314C4
Message: Specified parameter Version is not valid.
```

请问设定正确吗？

**Comment by gaort** [comment]
@xiaoxin01 
您好，这个问题应该是endpoint设定问题
帮您查看了下，您可以使用cdn.aliyuncs.com作为endpoint

**Comment by xiaoxin01** [comment]
@gaort 
感谢帮忙,设定 cdn.aliyuncs.com 之后,在没有go环境的机器也可以正常运行了!
