### ISSUE TITLE
更新太过频繁

### ISSUE THREAD

**Issue by zk-123** [aliyun/alibaba-cloud-sdk-go#471]
一天之内更新了四个版本，文档还没到位(=_=)。
![image](https://user-images.githubusercontent.com/18661009/102086478-1f1af480-3e53-11eb-9eed-3e5ac69b2b68.png)

**Comment by wenzuochao** [comment]
为了让客户能更快用上最新的产品 SDK，我们这边每次更新产品 SDK 的时候都会发布新版本，所以建议您感知您使用的产品SDK的变更。
