### ISSUE TITLE
ACK(K8S) 各种 Describe 均为 HTTP 透传结果，无响应结构体返回

### ISSUE THREAD

**Issue by SecretSun** [aliyun/alibaba-cloud-sdk-go#475]
* **产品和接口**: github.com/aliyun/alibaba-cloud-sdk-go/services/cs
* **平台**: Linux
* **最小代码**: 
```
// github.com/aliyun/alibaba-cloud-sdk-go v1.61.881
csClient, err := cs.NewClientWithAccessKey("cn-shanghai", "xxxxx", "xxxxx")
if err != nil {
	fmt.Print(err.Error())
}

csRequest := cs.CreateDescribeClusterNodePoolsRequest()
csRequest.Scheme = "https"
csRequest.ClusterId = "xxxxx"
csResponse, err := csClient.DescribeClusterNodePools(csRequest)
if err != nil {
	fmt.Print(err.Error())
}
fmt.Print(csResponse)
 ```
* **问题**: 直接透传返回 string，麻烦完善对应结构体，提升用户工程效率。已经翻阅所有 Describe 相关 Code 均为相同问题；不排除其他非 Describe 接口也存在类似问题。

**Comment by wenzuochao** [comment]
如果您想要非透传的形式，您可以使用新的[SDK](https://github.com/aliyun/alibabacloud-go-sdk/tree/master/cs-20151215)，使用文档可以参考：https://github.com/aliyun/alibabacloud-go-sdk/tree/master/docs

**Comment by SecretSun** [comment]
亲，还是这个 SDK 上面分装下结构体吧，这个问题肯定不是困扰我这个第一个用户了。

**Comment by wenzuochao** [comment]
产品 SDK 都是自动生成的，cs 透传是由网关那边决定的，SDK这边没法做额外的处理。

**Comment by SecretSun** [comment]
好吧感谢
