### ISSUE TITLE
文档就写了个创建 client，后面如何跟对应的组件发送请求都没有，垃圾中的战斗鸡？

### ISSUE THREAD

**Issue by kong62** [aliyun/alibaba-cloud-sdk-go#483]
文档就写了个创建 client，后面如何跟对应的组件发送请求都没有，垃圾中的战斗鸡？

**Comment by JacksonTian** [comment]
亲，推荐使用 OpenAPI 开发者门户搭配使用：https://next.api.aliyun.com/api/Ecs/2014-05-26/DescribeRegions?params={}&sdkStyle=old&lang=GO 

有详细的例子，联动参数输入，可在线调试。
