### ISSUE TITLE
怎么做到token 轮转更新

### ISSUE THREAD

**Issue by l1b0k** [aliyun/alibaba-cloud-sdk-go#484]
Credential 存在定期轮转情况，代码考虑使用  NewProviderChain 来配置鉴权信息

如果使用  sdk/auth/credentials/providers/instance_metadata.go 去获取 Credential
看起来没有处理 Expiration 

问题：
1. SDK 是否可以支持对 Expiration 的 处理，主动更新 Credential ？

**Comment by JacksonTian** [comment]
对 ecs ram role 的情况，是默认支持了 token 刷新的。
