### ISSUE TITLE
failed to apply ali cloud vms 

### ISSUE THREAD

**Issue by kakaZhou719** [aliyun/alibaba-cloud-sdk-go#493]
when i apply ali cloud vms.  it seems like return SDK error .
my local PC is default centos EDT time.
do i need to reset my PC time as CST time to support signature calculation for ali cloud AKSK？
 
![image](https://user-images.githubusercontent.com/83740799/119787031-5b26ab00-bf03-11eb-943a-c86fa47ca8c2.png)

after i sync my local PC to CST time fixed this issue . i wondering if it is alicloud SDK issue ? pls have a investigate.

* **Product and API**:
* **Platform**:
* **How to Reproduce**

**Comment by kakaZhou719** [comment]
@JacksonTian

**Comment by JacksonTian** [comment]
We use following code to get timestamp:

```go
func GetTimeInFormatISO8601() (timeStr string) {
	gmt := time.FixedZone("GMT", 0)

	return time.Now().In(gmt).Format("2006-01-02T15:04:05Z")
}
```

**Comment by kakaZhou719** [comment]
@JacksonTian ,According to your suggestion, we need to reset the time zone before new Client?

**Comment by kakaZhou719** [comment]
hello ?

**Comment by JacksonTian** [comment]
不确定。感觉问题更可能出现在你机器的时间不同步导致的

**Comment by kakaZhou719** [comment]
嗯嗯，对的，我同步完时间就可以成功。所以我的问题是：在使用咱们SDK的时候需不需要在我的代码中，重新设置时间？才能规避这个问题。

**Comment by JacksonTian** [comment]
建议是对主机的时间做一个监控。

**Comment by JacksonTian** [comment]
issue 我先关了，如果有问题，随时重新打开。
