### ISSUE TITLE
dds： 获取机器信息

### ISSUE THREAD

**Issue by wanglong001** [aliyun/alibaba-cloud-sdk-go#515]
alibaba-cloud-sdk-go@v1.61.974

dds.DescribeDBInstances

获取不到 分片机器的信息：

![image](https://user-images.githubusercontent.com/14817376/126602587-e967a777-7d13-413a-92e1-38fe8ff75fd9.png)

```
region := "cn-shanghai"
config := sdk.NewConfig()
config.HttpTransport = defaultHttpTransport
config.WithTimeout(10 * time.Second)
client, err := dds.NewClientWithOptions(region, config, credentials.NewAccessKeyCredential(
"",
"",
))
request := dds.CreateDescribeDBInstancesRequest()
response, err := client.DescribeDBInstances(request)
fmt.Println(response)
```
return

```
{"TotalCount":0,"RequestId":"D6D98DAA-69BA-4C67-A5A8-AD0EFCE0CCE9","PageSize":30,"PageNumber":1,"DBInstances":{"DBInstance":[]}}
```

**Comment by JacksonTian** [comment]
The biz issue should submit a work order. http://selfservice.console.aliyun.com/ticket/createIndex?spm=5176.19720258.ace-homepage-2020-service-tab.29.5ef32c4afVbckg
