### ISSUE TITLE
老版本dns报错

### ISSUE THREAD

**Issue by timchine** [aliyun/alibaba-cloud-sdk-go#540]
github.com/aliyun/alibaba-cloud-sdk-go v1.61.1168
我使用这个版本,调用dns报错SDK.ServerError\nErrorCode: DomainRecordNotBelongToUser\nRecommend: https://error-center.aliyun.com/status/search?Keyword=DomainRecordNotBelongToUser&source=PopGw\nRequestId: 25CAD175-BC3F-5D92-8BA0-5EADC4184C0D\nMessage: The DNS record does not exist in your account

**Comment by JacksonTian** [comment]
报错显示，这个域名不属于您。
