### ISSUE TITLE
ram： GetGroup 缺少字段

### ISSUE THREAD

**Issue by wanglong001** [aliyun/alibaba-cloud-sdk-go#545]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/ram/struct_group_in_get_group.go

缺少 `GroupId` 字段

在网页上API调试是有的：
![image](https://user-images.githubusercontent.com/14817376/145321511-64d716bf-5193-4b58-9804-601fe5208f8a.png)

**Comment by JacksonTian** [comment]
这是因为 SDK 更新不及时导致的。
