### ISSUE TITLE
本地可运行，.exe上传至阿里云后出错

### ISSUE THREAD

**Issue by newhow** [aliyun/alibaba-cloud-sdk-go#55]
package util
import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
)

func SendSMS(PhoneNumbers, SignName, TemplateCode, TemplateParam string) error {
	client, _ := sdk.NewClientWithAccessKey("cn-shanghai", "xxxx", "yyyy")
	request := requests.NewCommonRequest()
	request.Domain = "dysmsapi.aliyuncs.com"
	request.Version = "2017-05-25"
	request.ApiName = "SendSms"
	request.QueryParams["PhoneNumbers"] = PhoneNumbers
	request.QueryParams["SignName"] = SignName
	request.QueryParams["TemplateCode"] = TemplateCode   
	request.QueryParams["TemplateParam"] = TemplateParam 
	response, err := client.ProcessCommonRequest(request)
	if err != nil {
		fmt.Println(err)
		return err
	} else if r := response.GetHttpContentString(); !strings.Contains(r, `"Message":"OK"`) {
		{
			err = fmt.Errorf(r)
		}
	}
	return err
}

/////////////////////////////////////
以上是util包中SendSMS代码，main 中调用 util.SendSMS，编译后在本机(windows 10)运行良好，将编译好的.exe文件上传至阿里云的ECS(windows server)，出现错误：
////////////////////////////////////
panic: open c:\go\lib\time\zoneinfo.zip: The system cannot find the path specified.

goroutine 23 [running]:
github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils.GetTimeInFormatISO8601(0x7d0980, 0xc04230a030)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/utils.go:57 +0x149
github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.completeRpcSignParams(0xa71700, 0xc042034120, 0xa6d3e0, 0xc042004028, 0x84b790, 0xb)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:42 +0x1e8
github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.signRpcRequest(0xa71700, 0xc042034120, 0xa6d3e0, 0xc042004028, 0x84b790, 0xb)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:26 +0x71
github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.Sign(0xa71700, 0xc042034120, 0xa6d3e0, 0xc042004028, 0x84b790, 0xb, 0x77b99c, 0x8)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signer.go:87 +0x2a2
github.com/aliyun/alibaba-cloud-sdk-go/sdk.buildHttpRequest(0xa71700, 0xc042034120, 0xa6d3e0, 0xc042004028, 0x84b790, 0xb, 0x8, 0x8, 0xc042004030)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:235 +0x8b
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc042308000, 0xa71700, 0xc042034120, 0xa6d5c0, 0xc042004038, 0x0, 0x0, 0x1, 0xc0420320c0)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:192 +0x3c4
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc042308000, 0xa71700, 0xc042034120, 0xa6d5c0, 0xc042004038, 0x0, 0xc042304240)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:151 +0x6c
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).ProcessCommonRequest(0xc042308000, 0xc042034120, 0x84c6e9, 0xd, 0xc0423042f8)
        D:/OneDrive/code/gopath/src/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:341 +0xae
hao/util.SendSMS(0xc042008210, 0xb, 0x84c328, 0xc, 0x84be6c, 0xc, 0xc04200a440, 0x11, 0x11, 0xc042071080)

**Comment by newhow** [comment]
我觉着某种windows下编译的exe文件应该可以运行在另外的windows操作系统，只要两者都是64位的。Am I wrong?

**Comment by gaort** [comment]
@newhow 
这个问题，是go语言的一个坑，您可以google下这个路径，会发现很多项目都在讨论它。
简单来说，是由于go的time包，需要一个zoneinfo.zip文件才能执行，而没安装过的windows机器上不会有这个文件的。

一个有效的解决方法：
1. 您需要使用go1.10.x
2. 参考这段代码https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/utils/utils.go#L31
3. 将1.10中，time包里的LoadLocationFromTZData func，赋值给utils.LoadLocationFromTZData
4. 将编译机器(随便哪个安装了go的win/linux都成)上的zoneinfo.zip，复制到运行机器上，然后将ioutils.Readfile返回的[]byte赋值给utils.TZData
