### ISSUE TITLE
v1.61.1423编译不过

### ISSUE THREAD

**Issue by zhenfeipeng2** [aliyun/alibaba-cloud-sdk-go#550]
sdk/client.go:674

![image](https://user-images.githubusercontent.com/97150047/148171470-cdce65b3-7166-43e3-b868-6085df85d625.png)  

ServerError中没有这个字段  
![image](https://user-images.githubusercontent.com/97150047/148171548-e5f14117-6ac1-423d-8509-adb06d7110e6.png)  

请尽快修复，谢谢

* **Product and API**:
* **Platform**:
* **How to Reproduce**

**Comment by JacksonTian** [comment]
It's fixed. Thank you for your feedback.
