### ISSUE TITLE
不支持asapi中oss调用

### ISSUE THREAD

**Issue by ioito** [aliyun/alibaba-cloud-sdk-go#559]
https://help.aliyun.com/apsara/enterprise/v_3_13_0_20201215/oss/ascm-enterprise-developer-guide/python-sdk-1_3348956.html?spm=a2c4g.14484438.10001.143

* **产品和接口**:
OSS及相关接口
* **平台**:
飞天专有云，asapi

* **最小代码**:

**Comment by JacksonTian** [comment]
本 SDK 里不包含对 OSS 的支持。
