### ISSUE TITLE
[ADB MySql] Unsupported column type: 245

### ISSUE THREAD

**Issue by eric-chao** [aliyun/alibaba-cloud-sdk-go#563]
[ADB MySql]

adb mysql version: 3.1.3.8

mysql column type: json array, e.g.  ["basketball", "football"] 

sdk: golang gorm

ERROR:

Error 1815: [9001, 2022042418393617201618417503453302922] Unsupported column type: 245

**Comment by eric-chao** [comment]
![image](https://user-images.githubusercontent.com/13026384/165016783-83841cc2-4611-4218-8c18-1a330d08242e.png)

![image](https://user-images.githubusercontent.com/13026384/165016794-f61de834-8155-41d1-b3eb-07131c466837.png)

**Comment by eric-chao** [comment]
Create Table `t_beneficiary` (
 `id` bigint NOT NULL AUTO_INCREMENT COMMENT '',
 `name` varchar COMMENT '',
 `doc_id` varchar NOT NULL COMMENT 'document id',
 `doc_type` varchar NOT NULL COMMENT 'document type',
 `receipt_info` json NOT NULL COMMENT '',
 `beneficiary_type` tinyint DEFAULT '1' COMMENT 'beneficiary type',
 `country` varchar COMMENT '',
 `created_at` datetime COMMENT '',
 `updated_at` datetime COMMENT '',
 primary key (`id`)
) DISTRIBUTE BY HASH(`id`) INDEX_ALL='Y' STORAGE_POLICY='HOT' BLOCK_SIZE=8192;

**Comment by JacksonTian** [comment]
Please submit a work order at https://selfservice.console.aliyun.com/ticket/createIndex?spm=5176.12818093.top-nav.ditem-sub.3b4d16d0EhWbQw
