### ISSUE TITLE
调用ListPolicies，Panic

### ISSUE THREAD

**Issue by chuyali** [aliyun/alibaba-cloud-sdk-go#576]
```
package main

import (
	"fmt"

	"github.com/aliyun/alibaba-cloud-sdk-go/services/resourcemanager"
)

func main() {
	//构建阿里云客户端时需要设置AccessKey ID和AccessKey Secret。
	client, err := resourcemanager.NewClientWithAccessKey("cn-zhangjiakou.log.aliyuncs.com", "***", "***")

	//构建请求对象。
	request := resourcemanager.CreateListPoliciesRequest()
	//发起请求，并得到响应。
	response, err := client.ListPolicies(request)
	if err != nil {
		fmt.Print(err.Error())
	}
	fmt.Printf("response is %#v\n", response)
}
```

发生Panic,请问是哪有问题？

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x131df10]

goroutine 1 [running]:
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).buildRequestWithSigner(0xc000194000, 0x145a9e0, 0xc000146280, 0x0, 0x0, 0x0, 0x0, 0x145a2c0)
        /Users/zhuyun/go/pkg/mod/github.com/aliyun/alibaba-cloud-sdk-go@v1.61.1783/sdk/client.go:418 +0x530
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc000194000, 0x145a9e0, 0xc000146280, 0x1457038, 0xc0001462d0, 0x0, 0x0, 0x0, 0x0)
        /Users/zhuyun/go/pkg/mod/github.com/aliyun/alibaba-cloud-sdk-go@v1.61.1783/sdk/client.go:555 +0x169
github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc000194000, 0x145a9e0, 0xc000146280, 0x1457038, 0xc0001462d0, 0xc00018a420, 0xc00012c270)
        /Users/zhuyun/go/pkg/mod/github.com/aliyun/alibaba-cloud-sdk-go@v1.61.1783/sdk/client.go:346 +0xa3c
github.com/aliyun/alibaba-cloud-sdk-go/services/resourcemanager.(*Client).ListPolicies(0xc000194000, 0xc000146280, 0x13d1ae1, 0x18, 0x13d4a90)
        /Users/zhuyun/go/pkg/mod/github.com/aliyun/alibaba-cloud-sdk-go@v1.61.1783/services/resourcemanager/list_policies.go:26 +0x98
main.main()
        /Users/zhuyun/go/src/gitlab.jiagouyun.com/cloudcare-tools/sls_ak_sk.go:16 +0x9c
exit status 2

**Comment by JacksonTian** [comment]
https://api.aliyun.com/api/ResourceManager/2020-03-31/ListPolicies?sdkStyle=old&tab=DEMO&lang=GO 请参考我们的在线示例。
