### ISSUE TITLE
sdk does not support windows

### ISSUE THREAD

**Issue by xiaozhu36** [aliyun/alibaba-cloud-sdk-go#60]
When use this sdk to create alicloud resource, there is a following bug:
 
```
panic: open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path specified.
```
 and after check `/usr/local/go/src/time/zoneinfo.go` , line 273-278 have the following annotation：

```
// The time zone database needed by LoadLocation may not be
// present on all systems, especially non-Unix systems.
// LoadLocation looks in the directory or uncompressed zip file
// named by the ZONEINFO environment variable, if any, then looks in
// known installation locations on Unix systems,
// and finally looks in $GOROOT/lib/time/zoneinfo.zip.
```

Could the issue be fixed?

**Comment by gaort** [comment]
@xiaozhu36 
This is a problem with the go language.
if you use go1.10 or higher，You can refer to the comment to solve：
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/utils/utils.go#L30
