### ISSUE TITLE
the *_android.go or *_ios.go just like *_test.go will be ignored by b…

### ISSUE THREAD

**Issue by MWangxj** [aliyun/alibaba-cloud-sdk-go#61]
the push service as push_message_to_android.go & push_notice_to_android.go, this file name will be ignore by the compile, you should rename it like your *i_os.go ,like that……

**Comment by JacksonTian** [comment]
Why these files are ignored by compiler? Could you show me the case?

**Comment by lizebang** [comment]
@JacksonTian 
Files ending with `_android.go` can only be compiled if GOOS=android.
This just like `_windows.go`, `_unix.go`, etc.

**Comment by wenzuochao** [comment]
> @JacksonTian
> Files ending with `_android.go` can only be compiled if GOOS=android.
> This just like `_windows.go`, `_unix.go`, etc.

We have merged a pr about it . Hope it can help you. Thanks for your support to our project.#221
