### ISSUE TITLE
alibabacloud-go-sdk、alibaba-cloud-sdk-go 应该使用哪一个？

### ISSUE THREAD

**Issue by jacobwwang** [aliyun/alibaba-cloud-sdk-go#614]
我需要接入`移动推送`的 SDK，但是发现这两个仓库 `alibabacloud-go-sdk` 和 `alibaba-cloud-sdk-go` 都有提供，请问这两者有什么区别和联系，谢谢。

**Comment by JacksonTian** [comment]
新项目推荐用 alibabacloud-go-sdk。它是以产品为粒度提供的包。
