### ISSUE TITLE
Incorrect data type: rds.Backup.BackupSize

### ISSUE THREAD

**Issue by ghost** [aliyun/alibaba-cloud-sdk-go#62]
According to document: https://help.aliyun.com/document_detail/26273.html, the data type of rds.Backup.BackupSize should be long, but in current codes it's 'int'.

**Comment by wenzuochao** [comment]
> According to document: https://help.aliyun.com/document_detail/26273.html, the data type of rds.Backup.BackupSize should be long, but in current codes it's 'int'.

Thanks for your correction. I have tested the api, and found that It's a fault of the writer who writes the document. I have remind him of modify the data type of rds.Backup.BackupSize.
