### ISSUE TITLE
No API CreateAutoProvisioningGroup

### ISSUE THREAD

**Issue by jwcesign** [aliyun/alibaba-cloud-sdk-go#658]
The corresponding doc: https://help.aliyun.com/zh/ecs/developer-reference/api-ecs-2014-05-26-createautoprovisioninggroup?spm=a2c4g.11186623.0.0.53013beduR8ZBH

**Comment by CodeSpaceiiii** [comment]
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/ecs/create_auto_provisioning_group.go

Already have it, please refer to it.
