### ISSUE TITLE
Instance status should be const

### ISSUE THREAD

**Issue by aiden0z** [aliyun/alibaba-cloud-sdk-go#71]
I only find instance status definition in [integration](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/246a2ae35275109b72c7de684aa92246b90cb19d/integration/ecs_test.go#L18) package. All instance status should located in ecs package. like:

```golang
const (
	InstanceStatusCreating = "Creating"
	InstanceStatusPending  = "Pending"
	InstanceStatusRunning  = "Running"
	InstanceStatusStarting = "Starting"

	InstanceStatusStopped  = "Stopped"
	InstanceStatusStopping = "Stopping"
	InstanceStatusDeleted  = "Deleted"
)
```

**Comment by jxyowen** [comment]
The integration package is used for test, these definition shoud be defined by user.
