### ISSUE TITLE
Request SDKs of Logging service, messaging service and function compute

### ISSUE THREAD

**Issue by changkun** [aliyun/alibaba-cloud-sdk-go#73]
1. SDK of SLS only contains open account operations, please provide a complete SDK
2. The current repository doesn't contain any SDK of messaging service MNS, please provide one
3. The SDK of function compute only distributed in another repo, could you please integrate them into this repo

**Comment by changkun** [comment]
I would say Alibaba Cloud is literally nobody takes care of customer request.

**Comment by jxyowen** [comment]
These SDKs are not in these repo, you can find them in their help documents :https://help.aliyun.com

**Comment by changkun** [comment]
@jxyowen Thanks for your reply. 

Unfortunately, Messaging Service doesn't provide SDK for Go even in an external repository.

This issue intends to request an integration of various difference SDKs, users don't need to verify for documentation (sometimes docs are not synced with the source code, and users do not read docs but code). Another benefit of combining all services SDK into this repo is to manage dependencies easier across multiple services, such as common request params.

At the moment, as an instance, request marshal and unmarshal are self-implemented in different SDKs. As a user, I don't like manage vendors in that way.

So, please, try to integrate SLS and Function Compute into this repo and also provide the SDK of Messaging Service in Go.
