### ISSUE TITLE
Can't change an (expired) STS token inside an OSS client

### ISSUE THREAD

**Issue by matyix** [aliyun/alibaba-cloud-sdk-go#77]
There is a problem with STS tokens we encounter. Our use case is similar to the one documented here https://www.alibabacloud.com/help/doc-detail/54579.htm?spm=a2c63.p38356.a3.2.173c3461fmtaEf but with Golang instead of Python. 

The issue is with accessing the OSS API from Golang code with STS tokens, this is certainly possible, but the STS tokens are expiring, and there is no way to `change the tokens inside an existing OSS client`, although in the https://github.com/aliyun/alibaba-cloud-sdk-go the tokens are refreshed on-demand.

 Are there any plans to change this behavior our this is not the correct way to use the API? Currently, we have to throw away the OSS client every time the token expires, and users of the API have to implement the same pattern at every use case.

**Comment by jxyowen** [comment]
Hi matyix, you can open issue here :https://github.com/aliyun/aliyun-oss-go-sdk ,or open a support ticket.Thanks!

**Comment by matyix** [comment]
Thanks.
