### ISSUE TITLE
[Feature Request]When will oss be ready?

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#8]
I wonder when the SDK for oss will be ready? Do you have any schedule? Thanks!

**Comment by gaort** [comment]
@jancco2012 thanks for your feedback!
you can get official oss go sdk from here: https://github.com/aliyun/aliyun-oss-go-sdk

**Comment by jancco2012** [comment]
I got it! Thank you!
