### ISSUE TITLE
Support SDK for OpenSearch

### ISSUE THREAD

**Issue by zyfdegh** [aliyun/alibaba-cloud-sdk-go#80]
It seems there is no relevent codes in this repo about Ali OpenSearch, so will it be supported in coming days?

**Comment by wenzuochao** [comment]
> It seems there is no relevent codes in this repo about Ali OpenSearch, so will it be supported in coming days?

Thank you for your advice, we have added OpenSearch into SDk now, welcome to download lastest codes.
