### ISSUE TITLE
Slb create_v_server_group BackendServers type is string, is it right?

### ISSUE THREAD

**Issue by regardfs** [aliyun/alibaba-cloud-sdk-go#84]
Hi, 
I have seen in this page: [`https://help.aliyun.com/document_detail/35215.html?spm=a2c4g.11186623.6.763.J7b8y5`], `*BackendServers*` is a list ,
```
BackendServers=[
    {"ServerId":"vm-233","Port":"80","Weight":"100"},
    {"ServerId":"vm-232","Port":"90","Weight":"100"},
    {"ServerId":"vm-231","Port":"70","Weight":"100"}
]
```
but in this sdk, `*BackendServers*` is a string[`https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/slb/create_v_server_group.go#L87`], so ,How can i use this method to create v_server_group, could u provide an example?

**Comment by jxyowen** [comment]
try code below, use backendServersStr as the value of BackendServers
```
backendServersList := []map[string]string{
    {"ServerId":"vm-233","Port":"80","Weight":"100"},
    {"ServerId":"vm-232","Port":"90","Weight":"100"},
    {"ServerId":"vm-231","Port":"70","Weight":"100"},
}

    backendServersBytes, err := json.Marshal(backendServersList)
	if err != nil {
		fmt.Print(err)
		return
	}

	backendServersStr := string(backendServersBytes)
```

**Comment by wenzuochao** [comment]
> Hi,
> I have seen in this page: [`https://help.aliyun.com/document_detail/35215.html?spm=a2c4g.11186623.6.763.J7b8y5`], `*BackendServers*` is a list ,
> 
> ```
> BackendServers=[
>     {"ServerId":"vm-233","Port":"80","Weight":"100"},
>     {"ServerId":"vm-232","Port":"90","Weight":"100"},
>     {"ServerId":"vm-231","Port":"70","Weight":"100"}
> ]
> ```
> but in this sdk, `*BackendServers*` is a string[`https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/slb/create_v_server_group.go#L87`], so ,How can i use this method to create v_server_group, could u provide an example?

Thanks for your question, but in [`https://help.aliyun.com/document_detail/35215.html?spm=a2c4g.11186623.6.763.J7b8y5`] now , `*BackendServers*` is a string. You  can use it in this way which is commented by jxyowen.
