### ISSUE TITLE
how to use https?

### ISSUE THREAD

**Issue by liukeyou** [aliyun/alibaba-cloud-sdk-go#85]
how to use https?

**Comment by aylei** [comment]
I use the `Scheme` config for https
https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/sdk/config.go#L33

**Comment by tyrannosaurus-becks** [comment]
@liukeyou here is also an example of how I create one particular client that can be used for other clients:
```
config := sdk.NewConfig()
config.Scheme = "https"
client, err := kms.NewClientWithOptions(region, config, creds)
```

**Comment by chrisliu529** [comment]
It's easy to config the scheme to https with the code snippet by @tyrannosaurus-becks above.
However, it seems *very* strange today to use HTTP scheme by default. Why don't we use HTTPS by default?

**Comment by JacksonTian** [comment]
Change HTTP to HTTPS by default will cause compatible issue. We will change it in next major version.
