### ISSUE TITLE
ECS stop instance

### ISSUE THREAD

**Issue by ElanUpper** [aliyun/alibaba-cloud-sdk-go#86]
hello experts,

I use following code to stop a ECS instance, but not work.

```
// stop instance
stopRequest := requests.NewCommonRequest()
stopRequest.ApiName = "StopInstance"
stopRequest.QueryParams["InstanceId"] = "i-m5e10******"
stopRequest.QueryParams["ForceStop"] = "true"
//stopRequest.Domain = "xxx"
actionRequest := stopRequest

// action  ecsClient: already with credential
if response, err := ecsClient.ProcessCommonRequest(actionRequest); err != nil {
  log.Println(errHandle(err))
} else {
  fmt.Print(response.GetHttpContentString())
}
```
and here is the error message:
 Client ErrorCode:  SDK.CanNotResolveEndpoint , Error Message:  Can not resolve endpoint(param = {"Domain":"","Product":"","RegionId":"cn-qingdao","LocationProduct":"","LocationEndpointType":""}), please check your accessKey with secret, and read the user guide

I check the guide, I need to set stopRequest.Domain. But currently we don't need the domain. and the official sample don't contain the parameter domain.  should you give me some help? thank you.

**Comment by xiaozhu36** [comment]
@ElanUpper I think you did not set AccessKey and SecretKey, and please check.

**Comment by JacksonTian** [comment]
Set the Domain please.
