### ISSUE TITLE
Error: SDK.CanNotResolveEndpoint on DescribeRegions

### ISSUE THREAD

**Issue by jancco2012** [aliyun/alibaba-cloud-sdk-go#9]
**1. Error when calling the API**

When calling ecs.Client.DescribeRegions, the following error returned:
> [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Ecs","RegionId":"cn-qingdao","LocationProduct":"","LocationEndpoint":""}), please check the user guide

And calling codes are as following:

`input := aliecs.CreateDescribeRegionsRequest()`
`output, err := m.GetEcsClient().DescribeRegions(input)`

**2. What the meanings of the fields**

In ecs package, there is the following definition:
> type DescribeRegionsRequest struct {
	*requests.RpcRequest
	ResourceOwnerAccount string `position:"Query" name:"ResourceOwnerAccount"`
	ResourceOwnerId      string `position:"Query" name:"ResourceOwnerId"`
	OwnerAccount         string `position:"Query" name:"OwnerAccount"`
	OwnerId              string `position:"Query" name:"OwnerId"`
}

Can you help clarifying the meanings and differences of the following 4 fields? (I didn't find any clues from official document: https://help.aliyun.com/document_detail/25609.html.)

- ResourceOwnerAccount
- ResourceOwnerId
- OwnerAccount
- OwnerId

Thanks!

**Comment by morlay** [comment]
Hi @jancco2012 

Those clients couldn't be invoked without `regionId` value,  you can use `cn-beijing` as default value to solve the question 1.

Question 2. Maybe they are just for something like role control. 
In fact, I picked AST from Java SDK, there are on more  `ProductType` https://github.com/morlay/aliyun-go/blob/master/clients/vpc/describe_regions.go#L17, which is not in their docs.

**Comment by gaort** [comment]
@jancco2012 
thanks for your feedback.
1. I'm very sorry it's a bug, we will fix this soon
you can add these codes before send request to skip the bug codes
```go
    input := aliecs.CreateDescribeRegionsRequest()
    input.Domain = "ecs.aliyuncs.com"
    output, err := m.GetEcsClient().DescribeRegions(input)
```
you can find the 'Domain' param value from here:
https://help.aliyun.com/document_detail/25489.html

2. these params are optional, in most cases you can ignore them

**Comment by jancco2012** [comment]
@morlay Thanks for you replies!
And if possible, could you help asking the meanings of the 4 fields from your Java team? Maybe we'll use them in the future.

**Comment by jancco2012** [comment]
@gaort Thanks for the workaround your suggested!
And in the document (https://help.aliyun.com/document_detail/25489.html), term "Domain" doesn't appear, so could I take "Domain" as the same conception as "Endpoint"?

**Comment by gaort** [comment]
@jancco2012 
yes
"Endpoint" means the host where to send the http request, so it's also called "Host" or "Domain"

**Comment by jancco2012** [comment]
@gaort 
OK, I got it. Thank you!

**Comment by jancco2012** [comment]
@gaort I found this issue had been fixed for most of the services, but it still exists in ESS service.

And the tested version is: https://github.com/aliyun/alibaba-cloud-sdk-go/commit/02cfceb8fae6781741d7e1c39b719b3d085e1e75
